@startuml
skinparam linetype ortho
title <size:20> **simplified** and **grouped per namespace**</size>
note "Your are analyzing:\n **simplified** and **grouped per namespace**\n\n==Filter==\nYou can click either the namespaces \nor class names for filtering them and their\ndirect dependencies.\n\n==Select other==\n*  **detailed** and **grouped per namespace**:\n   [[-diagram-detailed-grouped-per-namespace.svg]]\n* Full diagram **simplified** and **grouped per namespace**:\n   [[full-diagram-simplified-grouped-per-namespace.svg]]\n* Home:\n   [[index.html]]" as FloatingNote
class Variable [[Variable-diagram-simplified-grouped-per-namespace.svg]] #yellow {
}
class Method [[Method-diagram-simplified-grouped-per-namespace.svg]] #yellow {
}
class SubDataStructure [[SubDataStructure-diagram-simplified-grouped-per-namespace.svg]] #yellow {
}
class CompilationUnit [[CompilationUnit-diagram-simplified-grouped-per-namespace.svg]] #yellow {
}
class VoidVisitorAdapter_BRQTO_Void_BRQTC [[VoidVisitorAdapter_BRQTO_Void_BRQTC-diagram-simplified-grouped-per-namespace.svg]] #yellow {
}
class PrintStream [[PrintStream-diagram-simplified-grouped-per-namespace.svg]] #yellow {
}
class HandleDeepness [[HandleDeepness-diagram-simplified-grouped-per-namespace.svg]] #yellow {
}
class AnnotationDeclaration [[AnnotationDeclaration-diagram-simplified-grouped-per-namespace.svg]] #yellow {
}
class Void [[Void-diagram-simplified-grouped-per-namespace.svg]] #yellow {
}
class AnnotationMemberDeclaration [[AnnotationMemberDeclaration-diagram-simplified-grouped-per-namespace.svg]] #yellow {
}
class ArrayAccessExpr [[ArrayAccessExpr-diagram-simplified-grouped-per-namespace.svg]] #yellow {
}
class ArrayCreationExpr [[ArrayCreationExpr-diagram-simplified-grouped-per-namespace.svg]] #yellow {
}
class ArrayCreationLevel [[ArrayCreationLevel-diagram-simplified-grouped-per-namespace.svg]] #yellow {
}
class ArrayInitializerExpr [[ArrayInitializerExpr-diagram-simplified-grouped-per-namespace.svg]] #yellow {
}
class ArrayType [[ArrayType-diagram-simplified-grouped-per-namespace.svg]] #yellow {
}
class AssertStmt [[AssertStmt-diagram-simplified-grouped-per-namespace.svg]] #yellow {
}
class AssignExpr [[AssignExpr-diagram-simplified-grouped-per-namespace.svg]] #yellow {
}
class BinaryExpr [[BinaryExpr-diagram-simplified-grouped-per-namespace.svg]] #yellow {
}
class BlockComment [[BlockComment-diagram-simplified-grouped-per-namespace.svg]] #yellow {
}
class BlockStmt [[BlockStmt-diagram-simplified-grouped-per-namespace.svg]] #yellow {
}
class BooleanLiteralExpr [[BooleanLiteralExpr-diagram-simplified-grouped-per-namespace.svg]] #yellow {
}
class BreakStmt [[BreakStmt-diagram-simplified-grouped-per-namespace.svg]] #yellow {
}
class CastExpr [[CastExpr-diagram-simplified-grouped-per-namespace.svg]] #yellow {
}
class CatchClause [[CatchClause-diagram-simplified-grouped-per-namespace.svg]] #yellow {
}
class CharLiteralExpr [[CharLiteralExpr-diagram-simplified-grouped-per-namespace.svg]] #yellow {
}
class ClassExpr [[ClassExpr-diagram-simplified-grouped-per-namespace.svg]] #yellow {
}
class ClassOrInterfaceDeclaration [[ClassOrInterfaceDeclaration-diagram-simplified-grouped-per-namespace.svg]] #yellow {
}
class ClassOrInterfaceType [[ClassOrInterfaceType-diagram-simplified-grouped-per-namespace.svg]] #yellow {
}
class ConditionalExpr [[ConditionalExpr-diagram-simplified-grouped-per-namespace.svg]] #yellow {
}
class ConstructorDeclaration [[ConstructorDeclaration-diagram-simplified-grouped-per-namespace.svg]] #yellow {
}
class ContinueStmt [[ContinueStmt-diagram-simplified-grouped-per-namespace.svg]] #yellow {
}
class DoStmt [[DoStmt-diagram-simplified-grouped-per-namespace.svg]] #yellow {
}
class DoubleLiteralExpr [[DoubleLiteralExpr-diagram-simplified-grouped-per-namespace.svg]] #yellow {
}
class EmptyStmt [[EmptyStmt-diagram-simplified-grouped-per-namespace.svg]] #yellow {
}
class EnclosedExpr [[EnclosedExpr-diagram-simplified-grouped-per-namespace.svg]] #yellow {
}
class EnumConstantDeclaration [[EnumConstantDeclaration-diagram-simplified-grouped-per-namespace.svg]] #yellow {
}
class EnumDeclaration [[EnumDeclaration-diagram-simplified-grouped-per-namespace.svg]] #yellow {
}
class ExplicitConstructorInvocationStmt [[ExplicitConstructorInvocationStmt-diagram-simplified-grouped-per-namespace.svg]] #yellow {
}
class ExpressionStmt [[ExpressionStmt-diagram-simplified-grouped-per-namespace.svg]] #yellow {
}
class FieldAccessExpr [[FieldAccessExpr-diagram-simplified-grouped-per-namespace.svg]] #yellow {
}
class FieldDeclaration [[FieldDeclaration-diagram-simplified-grouped-per-namespace.svg]] #yellow {
}
class ForEachStmt [[ForEachStmt-diagram-simplified-grouped-per-namespace.svg]] #yellow {
}
class ForStmt [[ForStmt-diagram-simplified-grouped-per-namespace.svg]] #yellow {
}
class IfStmt [[IfStmt-diagram-simplified-grouped-per-namespace.svg]] #yellow {
}
class ImportDeclaration [[ImportDeclaration-diagram-simplified-grouped-per-namespace.svg]] #yellow {
}
class InitializerDeclaration [[InitializerDeclaration-diagram-simplified-grouped-per-namespace.svg]] #yellow {
}
class InstanceOfExpr [[InstanceOfExpr-diagram-simplified-grouped-per-namespace.svg]] #yellow {
}
class IntegerLiteralExpr [[IntegerLiteralExpr-diagram-simplified-grouped-per-namespace.svg]] #yellow {
}
class IntersectionType [[IntersectionType-diagram-simplified-grouped-per-namespace.svg]] #yellow {
}
class JavadocComment [[JavadocComment-diagram-simplified-grouped-per-namespace.svg]] #yellow {
}
class LabeledStmt [[LabeledStmt-diagram-simplified-grouped-per-namespace.svg]] #yellow {
}
class LambdaExpr [[LambdaExpr-diagram-simplified-grouped-per-namespace.svg]] #yellow {
}
class LineComment [[LineComment-diagram-simplified-grouped-per-namespace.svg]] #yellow {
}
class LocalClassDeclarationStmt [[LocalClassDeclarationStmt-diagram-simplified-grouped-per-namespace.svg]] #yellow {
}
class LongLiteralExpr [[LongLiteralExpr-diagram-simplified-grouped-per-namespace.svg]] #yellow {
}
class MarkerAnnotationExpr [[MarkerAnnotationExpr-diagram-simplified-grouped-per-namespace.svg]] #yellow {
}
class MemberValuetuple [[MemberValuetuple-diagram-simplified-grouped-per-namespace.svg]] #yellow {
}
class MethodCallExpr [[MethodCallExpr-diagram-simplified-grouped-per-namespace.svg]] #yellow {
}
class MethodDeclaration [[MethodDeclaration-diagram-simplified-grouped-per-namespace.svg]] #yellow {
}
class MethodReferenceExpr [[MethodReferenceExpr-diagram-simplified-grouped-per-namespace.svg]] #yellow {
}
class ModuleDeclaration [[ModuleDeclaration-diagram-simplified-grouped-per-namespace.svg]] #yellow {
}
class ModuleExportsDirective [[ModuleExportsDirective-diagram-simplified-grouped-per-namespace.svg]] #yellow {
}
class ModuleOpensDirective [[ModuleOpensDirective-diagram-simplified-grouped-per-namespace.svg]] #yellow {
}
class ModuleProvidesDirective [[ModuleProvidesDirective-diagram-simplified-grouped-per-namespace.svg]] #yellow {
}
class ModuleRequiresDirective [[ModuleRequiresDirective-diagram-simplified-grouped-per-namespace.svg]] #yellow {
}
class ModuleUsesDirective [[ModuleUsesDirective-diagram-simplified-grouped-per-namespace.svg]] #yellow {
}
class Name [[Name-diagram-simplified-grouped-per-namespace.svg]] #yellow {
}
class NameExpr [[NameExpr-diagram-simplified-grouped-per-namespace.svg]] #yellow {
}
class Nodelist [[Nodelist-diagram-simplified-grouped-per-namespace.svg]] #yellow {
}
class NormalAnnotationExpr [[NormalAnnotationExpr-diagram-simplified-grouped-per-namespace.svg]] #yellow {
}
class NullLiteralExpr [[NullLiteralExpr-diagram-simplified-grouped-per-namespace.svg]] #yellow {
}
class ObjectCreationExpr [[ObjectCreationExpr-diagram-simplified-grouped-per-namespace.svg]] #yellow {
}
class PackageDeclaration [[PackageDeclaration-diagram-simplified-grouped-per-namespace.svg]] #yellow {
}
class Parameter [[Parameter-diagram-simplified-grouped-per-namespace.svg]] #yellow {
}
class PrimitiveType [[PrimitiveType-diagram-simplified-grouped-per-namespace.svg]] #yellow {
}
class ReturnStmt [[ReturnStmt-diagram-simplified-grouped-per-namespace.svg]] #yellow {
}
class SimpleName [[SimpleName-diagram-simplified-grouped-per-namespace.svg]] #yellow {
}
class SingleMemberAnnotationExpr [[SingleMemberAnnotationExpr-diagram-simplified-grouped-per-namespace.svg]] #yellow {
}
class StringLiteralExpr [[StringLiteralExpr-diagram-simplified-grouped-per-namespace.svg]] #yellow {
}
class SuperExpr [[SuperExpr-diagram-simplified-grouped-per-namespace.svg]] #yellow {
}
class SwitchEntry [[SwitchEntry-diagram-simplified-grouped-per-namespace.svg]] #yellow {
}
class SwitchStmt [[SwitchStmt-diagram-simplified-grouped-per-namespace.svg]] #yellow {
}
class SynchronizedStmt [[SynchronizedStmt-diagram-simplified-grouped-per-namespace.svg]] #yellow {
}
class ThisExpr [[ThisExpr-diagram-simplified-grouped-per-namespace.svg]] #yellow {
}
class ThrowStmt [[ThrowStmt-diagram-simplified-grouped-per-namespace.svg]] #yellow {
}
class TryStmt [[TryStmt-diagram-simplified-grouped-per-namespace.svg]] #yellow {
}
class TypeExpr [[TypeExpr-diagram-simplified-grouped-per-namespace.svg]] #yellow {
}
class TypeParameter [[TypeParameter-diagram-simplified-grouped-per-namespace.svg]] #yellow {
}
class UnaryExpr [[UnaryExpr-diagram-simplified-grouped-per-namespace.svg]] #yellow {
}
class UnionType [[UnionType-diagram-simplified-grouped-per-namespace.svg]] #yellow {
}
class UnknownType [[UnknownType-diagram-simplified-grouped-per-namespace.svg]] #yellow {
}
class UnparsableStmt [[UnparsableStmt-diagram-simplified-grouped-per-namespace.svg]] #yellow {
}
class VariableDeclarationExpr [[VariableDeclarationExpr-diagram-simplified-grouped-per-namespace.svg]] #yellow {
}
class VariableDeclarator [[VariableDeclarator-diagram-simplified-grouped-per-namespace.svg]] #yellow {
}
class VoidType [[VoidType-diagram-simplified-grouped-per-namespace.svg]] #yellow {
}
class WhileStmt [[WhileStmt-diagram-simplified-grouped-per-namespace.svg]] #yellow {
}
class WildcardType [[WildcardType-diagram-simplified-grouped-per-namespace.svg]] #yellow {
}
class DumperOptions.FlowStyle [[DumperOptions.FlowStyle-diagram-simplified-grouped-per-namespace.svg]] #yellow {
}
class Mark [[Mark-diagram-simplified-grouped-per-namespace.svg]] #yellow {
}
class dictpingNode [[dictpingNode-diagram-simplified-grouped-per-namespace.svg]] #yellow {
}
class SequenceNode [[SequenceNode-diagram-simplified-grouped-per-namespace.svg]] #yellow {
}
class Yaml [[Yaml-diagram-simplified-grouped-per-namespace.svg]] #yellow {
}
class PrintWriter [[PrintWriter-diagram-simplified-grouped-per-namespace.svg]] #yellow {
}
class EnumTest [[EnumTest-diagram-simplified-grouped-per-namespace.svg]] #yellow {
}
class .Vehicle [[.Vehicle-diagram-simplified-grouped-per-namespace.svg]] #yellow {
}
class Type [[Type-diagram-simplified-grouped-per-namespace.svg]] #yellow {
}
class Optional_DOT_empty [[Optional_DOT_empty-diagram-simplified-grouped-per-namespace.svg]] #yellow {
}
class Path [[Path-diagram-simplified-grouped-per-namespace.svg]] #yellow {
}
' Closing all previous_sub_namespace_list namespace None because file analysis is finished.
namespace Examples [[Examples-diagram-simplified-grouped-per-namespace.svg]] {
namespace Examples.BadDesign [[Examples.BadDesign-diagram-simplified-grouped-per-namespace.svg]] {
  class Examples.BadDesign.DB [[Examples.BadDesign.DB-diagram-simplified-grouped-per-namespace.svg]] #yellow {
  }
'Compared namespace Examples.BadDesign [[Examples.BadDesign-diagram-simplified-grouped-per-namespace.svg]] { with last element of   }
' Closing all previous_sub_namespace_list namespace None because file analysis is finished.
' Closing namespace BadDesign
}
' Closing namespace Examples
}
namespace Examples [[Examples-diagram-simplified-grouped-per-namespace.svg]] {
namespace Examples.BadDesign [[Examples.BadDesign-diagram-simplified-grouped-per-namespace.svg]] {
namespace Examples.BadDesign.BasicExample [[Examples.BadDesign.BasicExample-diagram-simplified-grouped-per-namespace.svg]] {
    interface Examples.BadDesign.BasicExample.IExample [[Examples.BadDesign.BasicExample.IExample-diagram-simplified-grouped-per-namespace.svg]] #yellow {
    }
    class Examples.BadDesign.BasicExample.Useless [[Examples.BadDesign.BasicExample.Useless-diagram-simplified-grouped-per-namespace.svg]] #yellow {
    }
    class Examples.BadDesign.BasicExample.ClassExample_DOT_InnerClassExample [[Examples.BadDesign.BasicExample.ClassExample_DOT_InnerClassExample-diagram-simplified-grouped-per-namespace.svg]] #yellow {
    }
    class Examples.BadDesign.BasicExample.ClassExample_DOT_InnerClassExample_DOT_classInMethodExample [[Examples.BadDesign.BasicExample.ClassExample_DOT_InnerClassExample_DOT_classInMethodExample-diagram-simplified-grouped-per-namespace.svg]] #yellow {
    }
    class Examples.BadDesign.BasicExample.BaseExample_DOT_EnumTest [[Examples.BadDesign.BasicExample.BaseExample_DOT_EnumTest-diagram-simplified-grouped-per-namespace.svg]] #yellow {
    }
    class Examples.BadDesign.BasicExample.ClassExample [[Examples.BadDesign.BasicExample.ClassExample-diagram-simplified-grouped-per-namespace.svg]] #yellow {
    }
    class Examples.BadDesign.BasicExample.BaseExample [[Examples.BadDesign.BasicExample.BaseExample-diagram-simplified-grouped-per-namespace.svg]] #yellow {
    }
    abstract class Examples.BadDesign.BasicExample.AbstractBaseExample [[Examples.BadDesign.BasicExample.AbstractBaseExample-diagram-simplified-grouped-per-namespace.svg]] #yellow {
    }
'Compared namespace Examples.BadDesign.BasicExample [[Examples.BadDesign.BasicExample-diagram-simplified-grouped-per-namespace.svg]] { with last element of     }
' Closing all previous_sub_namespace_list namespace None because file analysis is finished.
' Closing namespace BasicExample
}
' Closing namespace BadDesign
}
' Closing namespace Examples
}
namespace Examples [[Examples-diagram-simplified-grouped-per-namespace.svg]] {
namespace Examples.BadDesign [[Examples.BadDesign-diagram-simplified-grouped-per-namespace.svg]] {
namespace Examples.BadDesign.BasicExample [[Examples.BadDesign.BasicExample-diagram-simplified-grouped-per-namespace.svg]] {
namespace Examples.BadDesign.BasicExample.SideExample [[Examples.BadDesign.BasicExample.SideExample-diagram-simplified-grouped-per-namespace.svg]] {
      class Examples.BadDesign.BasicExample.SideExample.SideTestEnum [[Examples.BadDesign.BasicExample.SideExample.SideTestEnum-diagram-simplified-grouped-per-namespace.svg]] #yellow {
      }
      class Examples.BadDesign.BasicExample.SideExample.SideExample [[Examples.BadDesign.BasicExample.SideExample.SideExample-diagram-simplified-grouped-per-namespace.svg]] #yellow {
      }
'Compared namespace Examples.BadDesign.BasicExample.SideExample [[Examples.BadDesign.BasicExample.SideExample-diagram-simplified-grouped-per-namespace.svg]] { with last element of       }
' Closing all previous_sub_namespace_list namespace None because file analysis is finished.
' Closing namespace SideExample
}
' Closing namespace BasicExample
}
' Closing namespace BadDesign
}
' Closing namespace Examples
}
namespace Examples [[Examples-diagram-simplified-grouped-per-namespace.svg]] {
namespace Examples.BadDesign [[Examples.BadDesign-diagram-simplified-grouped-per-namespace.svg]] {
namespace Examples.BadDesign.CarExample [[Examples.BadDesign.CarExample-diagram-simplified-grouped-per-namespace.svg]] {
    class Examples.BadDesign.CarExample.Vehicle [[Examples.BadDesign.CarExample.Vehicle-diagram-simplified-grouped-per-namespace.svg]] #yellow {
    }
    class Examples.BadDesign.CarExample.Car [[Examples.BadDesign.CarExample.Car-diagram-simplified-grouped-per-namespace.svg]] #yellow {
    }
'Compared namespace Examples.BadDesign.CarExample [[Examples.BadDesign.CarExample-diagram-simplified-grouped-per-namespace.svg]] { with last element of     }
' Closing all previous_sub_namespace_list namespace None because file analysis is finished.
' Closing namespace CarExample
}
' Closing namespace BadDesign
}
' Closing namespace Examples
}
namespace Examples [[Examples-diagram-simplified-grouped-per-namespace.svg]] {
namespace Examples.BadDesign [[Examples.BadDesign-diagram-simplified-grouped-per-namespace.svg]] {
namespace Examples.BadDesign.CarExample [[Examples.BadDesign.CarExample-diagram-simplified-grouped-per-namespace.svg]] {
namespace Examples.BadDesign.CarExample.CarParts [[Examples.BadDesign.CarExample.CarParts-diagram-simplified-grouped-per-namespace.svg]] {
      class Examples.BadDesign.CarExample.CarParts.Driver [[Examples.BadDesign.CarExample.CarParts.Driver-diagram-simplified-grouped-per-namespace.svg]] #yellow {
      }
      class Examples.BadDesign.CarExample.CarParts.Seats [[Examples.BadDesign.CarExample.CarParts.Seats-diagram-simplified-grouped-per-namespace.svg]] #yellow {
      }
      class Examples.BadDesign.CarExample.CarParts.Wheels [[Examples.BadDesign.CarExample.CarParts.Wheels-diagram-simplified-grouped-per-namespace.svg]] #yellow {
      }
      class Examples.BadDesign.CarExample.CarParts.Doors [[Examples.BadDesign.CarExample.CarParts.Doors-diagram-simplified-grouped-per-namespace.svg]] #yellow {
      }
'Compared namespace Examples.BadDesign.CarExample.CarParts [[Examples.BadDesign.CarExample.CarParts-diagram-simplified-grouped-per-namespace.svg]] { with last element of       }
' Closing all previous_sub_namespace_list namespace None because file analysis is finished.
' Closing namespace CarParts
}
' Closing namespace CarExample
}
' Closing namespace BadDesign
}
' Closing namespace Examples
}
namespace Examples [[Examples-diagram-simplified-grouped-per-namespace.svg]] {
namespace Examples.BadDesign [[Examples.BadDesign-diagram-simplified-grouped-per-namespace.svg]] {
namespace Examples.BadDesign.FakeEntitities [[Examples.BadDesign.FakeEntitities-diagram-simplified-grouped-per-namespace.svg]] {
    class Examples.BadDesign.FakeEntitities.Invoice [[Examples.BadDesign.FakeEntitities.Invoice-diagram-simplified-grouped-per-namespace.svg]] #yellow {
    }
    class Examples.BadDesign.FakeEntitities.Item [[Examples.BadDesign.FakeEntitities.Item-diagram-simplified-grouped-per-namespace.svg]] #yellow {
    }
    class Examples.BadDesign.FakeEntitities.Customer [[Examples.BadDesign.FakeEntitities.Customer-diagram-simplified-grouped-per-namespace.svg]] #yellow {
    }
    class Examples.BadDesign.FakeEntitities.User [[Examples.BadDesign.FakeEntitities.User-diagram-simplified-grouped-per-namespace.svg]] #yellow {
    }
    class Examples.BadDesign.FakeEntitities.Complaints [[Examples.BadDesign.FakeEntitities.Complaints-diagram-simplified-grouped-per-namespace.svg]] #yellow {
    }
'Compared namespace Examples.BadDesign.FakeEntitities [[Examples.BadDesign.FakeEntitities-diagram-simplified-grouped-per-namespace.svg]] { with last element of     }
' Closing all previous_sub_namespace_list namespace None because file analysis is finished.
' Closing namespace FakeEntitities
}
' Closing namespace BadDesign
}
' Closing namespace Examples
}
namespace Examples [[Examples-diagram-simplified-grouped-per-namespace.svg]] {
namespace Examples.BetterDesign [[Examples.BetterDesign-diagram-simplified-grouped-per-namespace.svg]] {
  class Examples.BetterDesign.DBCustomers [[Examples.BetterDesign.DBCustomers-diagram-simplified-grouped-per-namespace.svg]] #yellow {
  }
  class Examples.BetterDesign.DBCar [[Examples.BetterDesign.DBCar-diagram-simplified-grouped-per-namespace.svg]] #yellow {
  }
'Compared namespace Examples.BetterDesign [[Examples.BetterDesign-diagram-simplified-grouped-per-namespace.svg]] { with last element of   }
' Closing all previous_sub_namespace_list namespace None because file analysis is finished.
' Closing namespace BetterDesign
}
' Closing namespace Examples
}
namespace Examples [[Examples-diagram-simplified-grouped-per-namespace.svg]] {
namespace Examples.BetterDesign [[Examples.BetterDesign-diagram-simplified-grouped-per-namespace.svg]] {
namespace Examples.BetterDesign.CarExample [[Examples.BetterDesign.CarExample-diagram-simplified-grouped-per-namespace.svg]] {
    class Examples.BetterDesign.CarExample.Vehicle [[Examples.BetterDesign.CarExample.Vehicle-diagram-simplified-grouped-per-namespace.svg]] #yellow {
    }
    class Examples.BetterDesign.CarExample.Car [[Examples.BetterDesign.CarExample.Car-diagram-simplified-grouped-per-namespace.svg]] #yellow {
    }
'Compared namespace Examples.BetterDesign.CarExample [[Examples.BetterDesign.CarExample-diagram-simplified-grouped-per-namespace.svg]] { with last element of     }
' Closing all previous_sub_namespace_list namespace None because file analysis is finished.
' Closing namespace CarExample
}
' Closing namespace BetterDesign
}
' Closing namespace Examples
}
namespace Examples [[Examples-diagram-simplified-grouped-per-namespace.svg]] {
namespace Examples.BetterDesign [[Examples.BetterDesign-diagram-simplified-grouped-per-namespace.svg]] {
namespace Examples.BetterDesign.CarExample [[Examples.BetterDesign.CarExample-diagram-simplified-grouped-per-namespace.svg]] {
namespace Examples.BetterDesign.CarExample.CarParts [[Examples.BetterDesign.CarExample.CarParts-diagram-simplified-grouped-per-namespace.svg]] {
      class Examples.BetterDesign.CarExample.CarParts.Wheels [[Examples.BetterDesign.CarExample.CarParts.Wheels-diagram-simplified-grouped-per-namespace.svg]] #yellow {
      }
      class Examples.BetterDesign.CarExample.CarParts.Seats [[Examples.BetterDesign.CarExample.CarParts.Seats-diagram-simplified-grouped-per-namespace.svg]] #yellow {
      }
      class Examples.BetterDesign.CarExample.CarParts.Driver [[Examples.BetterDesign.CarExample.CarParts.Driver-diagram-simplified-grouped-per-namespace.svg]] #yellow {
      }
      class Examples.BetterDesign.CarExample.CarParts.Doors [[Examples.BetterDesign.CarExample.CarParts.Doors-diagram-simplified-grouped-per-namespace.svg]] #yellow {
      }
'Compared namespace Examples.BetterDesign.CarExample.CarParts [[Examples.BetterDesign.CarExample.CarParts-diagram-simplified-grouped-per-namespace.svg]] { with last element of       }
' Closing all previous_sub_namespace_list namespace None because file analysis is finished.
' Closing namespace CarParts
}
' Closing namespace CarExample
}
' Closing namespace BetterDesign
}
' Closing namespace Examples
}
namespace Examples [[Examples-diagram-simplified-grouped-per-namespace.svg]] {
namespace Examples.BetterDesign [[Examples.BetterDesign-diagram-simplified-grouped-per-namespace.svg]] {
namespace Examples.BetterDesign.FakeEntitities [[Examples.BetterDesign.FakeEntitities-diagram-simplified-grouped-per-namespace.svg]] {
    class Examples.BetterDesign.FakeEntitities.Item [[Examples.BetterDesign.FakeEntitities.Item-diagram-simplified-grouped-per-namespace.svg]] #yellow {
    }
    class Examples.BetterDesign.FakeEntitities.Customer [[Examples.BetterDesign.FakeEntitities.Customer-diagram-simplified-grouped-per-namespace.svg]] #yellow {
    }
    class Examples.BetterDesign.FakeEntitities.Invoice [[Examples.BetterDesign.FakeEntitities.Invoice-diagram-simplified-grouped-per-namespace.svg]] #yellow {
    }
    class Examples.BetterDesign.FakeEntitities.Complaints [[Examples.BetterDesign.FakeEntitities.Complaints-diagram-simplified-grouped-per-namespace.svg]] #yellow {
    }
    class Examples.BetterDesign.FakeEntitities.User [[Examples.BetterDesign.FakeEntitities.User-diagram-simplified-grouped-per-namespace.svg]] #yellow {
    }
'Compared namespace Examples.BetterDesign.FakeEntitities [[Examples.BetterDesign.FakeEntitities-diagram-simplified-grouped-per-namespace.svg]] { with last element of     }
' Closing all previous_sub_namespace_list namespace None because file analysis is finished.
' Closing namespace FakeEntitities
}
' Closing namespace BetterDesign
}
' Closing namespace Examples
}
namespace preadapter [[preadapter-diagram-simplified-grouped-per-namespace.svg]] {
class preadapter.Logger [[preadapter.Logger-diagram-simplified-grouped-per-namespace.svg]] #yellow {
}
class preadapter.LoggingType [[preadapter.LoggingType-diagram-simplified-grouped-per-namespace.svg]] #yellow {
}
class preadapter.Revenger [[preadapter.Revenger-diagram-simplified-grouped-per-namespace.svg]] #yellow {
}
'Compared namespace preadapter [[preadapter-diagram-simplified-grouped-per-namespace.svg]] { with last element of }
' Closing all previous_sub_namespace_list namespace None because file analysis is finished.
' Closing namespace preadapter
}
namespace preadapter [[preadapter-diagram-simplified-grouped-per-namespace.svg]] {
namespace preadapter.domain [[preadapter.domain-diagram-simplified-grouped-per-namespace.svg]] {
  class preadapter.domain.Datastructure [[preadapter.domain.Datastructure-diagram-simplified-grouped-per-namespace.svg]] #yellow {
  }
  class preadapter.domain.Datastructure_DOT_Method [[preadapter.domain.Datastructure_DOT_Method-diagram-simplified-grouped-per-namespace.svg]] #yellow {
  }
  class preadapter.domain.Datastructure_DOT_Static [[preadapter.domain.Datastructure_DOT_Static-diagram-simplified-grouped-per-namespace.svg]] #yellow {
  }
  class preadapter.domain.Datastructure_DOT_Variable [[preadapter.domain.Datastructure_DOT_Variable-diagram-simplified-grouped-per-namespace.svg]] #yellow {
  }
  class preadapter.domain.Datastructure_DOT_SubDataStructure [[preadapter.domain.Datastructure_DOT_SubDataStructure-diagram-simplified-grouped-per-namespace.svg]] #yellow {
  }
  class preadapter.domain.ASTVisitorDebug_DOT_HandleDeepness [[preadapter.domain.ASTVisitorDebug_DOT_HandleDeepness-diagram-simplified-grouped-per-namespace.svg]] #yellow {
  }
  class preadapter.domain.ASTVisitorDebug [[preadapter.domain.ASTVisitorDebug-diagram-simplified-grouped-per-namespace.svg]] #yellow {
  }
  class preadapter.domain.Datastructure_DOT_Method_DOT_ParameterType [[preadapter.domain.Datastructure_DOT_Method_DOT_ParameterType-diagram-simplified-grouped-per-namespace.svg]] #yellow {
  }
  class preadapter.domain.ASTVisitor_DOT_HandleDeepness [[preadapter.domain.ASTVisitor_DOT_HandleDeepness-diagram-simplified-grouped-per-namespace.svg]] #yellow {
  }
  class preadapter.domain.ASTVisitor [[preadapter.domain.ASTVisitor-diagram-simplified-grouped-per-namespace.svg]] #yellow {
  }
  class preadapter.domain.ASTVisitor_DOT_ObjectType [[preadapter.domain.ASTVisitor_DOT_ObjectType-diagram-simplified-grouped-per-namespace.svg]] #yellow {
  }
  class preadapter.domain.Datastructure_DOT_Method_DOT_Variable [[preadapter.domain.Datastructure_DOT_Method_DOT_Variable-diagram-simplified-grouped-per-namespace.svg]] #yellow {
  }
'Compared namespace preadapter.domain [[preadapter.domain-diagram-simplified-grouped-per-namespace.svg]] { with last element of   }
' Closing all previous_sub_namespace_list namespace None because file analysis is finished.
' Closing namespace domain
}
' Closing namespace preadapter
}
namespace preadapter [[preadapter-diagram-simplified-grouped-per-namespace.svg]] {
namespace preadapter.infrastructure [[preadapter.infrastructure-diagram-simplified-grouped-per-namespace.svg]] {
  class preadapter.infrastructure.CreateYML [[preadapter.infrastructure.CreateYML-diagram-simplified-grouped-per-namespace.svg]] #yellow {
  }
'Compared namespace preadapter.infrastructure [[preadapter.infrastructure-diagram-simplified-grouped-per-namespace.svg]] { with last element of   }
' Closing all previous_sub_namespace_list namespace None because file analysis is finished.
' Closing namespace infrastructure
}
' Closing namespace preadapter
}
namespace preadapter [[preadapter-diagram-simplified-grouped-per-namespace.svg]] {
namespace preadapter.service [[preadapter.service-diagram-simplified-grouped-per-namespace.svg]] {
  class preadapter.service.AnalyzeAST [[preadapter.service.AnalyzeAST-diagram-simplified-grouped-per-namespace.svg]] #yellow {
  }
  class preadapter.service.RecursiveFileProcessor [[preadapter.service.RecursiveFileProcessor-diagram-simplified-grouped-per-namespace.svg]] #yellow {
  }
'Compared namespace preadapter.service [[preadapter.service-diagram-simplified-grouped-per-namespace.svg]] { with last element of   }
' Closing all previous_sub_namespace_list namespace None because file analysis is finished.
' Closing namespace service
}
' Closing namespace preadapter
}
 ' *************************************** 
 ' *************************************** 
 ' *************************************** 
' Class relations extracted from namespace:
' 
' Class relations extracted from namespace:
' Examples.BadDesign
Examples.BadDesign.DB .[#6060BB].> Examples.BadDesign.FakeEntitities.User  : uses 
Examples.BadDesign.DB .[#6060BB].> Examples.BadDesign.FakeEntitities.Customer  : uses 
Examples.BadDesign.DB .[#6060BB].> Examples.BadDesign.FakeEntitities.Item  : uses 
Examples.BadDesign.DB .[#6060BB].> Examples.BadDesign.FakeEntitities.Invoice  : uses 
Examples.BadDesign.DB .[#6060BB].> Examples.BadDesign.FakeEntitities.Complaints  : uses 
Examples.BadDesign.DB .[#6060BB].> Examples.BadDesign.CarExample.Car  : uses 
Examples.BadDesign.DB .[#6060BB].> Examples.BadDesign.CarExample.CarParts.Driver  : uses 
Examples.BadDesign.DB .[#6060BB].> Examples.BadDesign.CarExample.CarParts.Wheels  : uses 
Examples.BadDesign.DB .[#6060BB].> Examples.BadDesign.CarExample.CarParts.Doors  : uses 
Examples.BadDesign.DB .[#6060BB].> Examples.BadDesign.CarExample.CarParts.Seats  : uses 
' Class relations extracted from namespace:
' Examples.BadDesign.BasicExample
Examples.BadDesign.BasicExample.IExample .[#6060BB].> Examples.BadDesign.BasicExample.Useless  : uses 
Examples.BadDesign.BasicExample.Useless *-[#10BB10]- Examples.BadDesign.DB 
Examples.BadDesign.BasicExample.Useless -[#909090]-> Examples.BadDesign.BasicExample.SideExample.SideTestEnum  : uses 
Examples.BadDesign.BasicExample.ClassExample_DOT_InnerClassExample +-[#10BBBB]- Examples.BadDesign.BasicExample.ClassExample_DOT_InnerClassExample_DOT_classInMethodExample 
Examples.BadDesign.BasicExample.BaseExample <|-[#red]- Examples.BadDesign.BasicExample.ClassExample
Examples.BadDesign.BasicExample.ClassExample +-[#10BBBB]- Examples.BadDesign.BasicExample.ClassExample_DOT_InnerClassExample 
Examples.BadDesign.BasicExample.ClassExample *-[#10BB10]- Examples.BadDesign.BasicExample.Useless 
Examples.BadDesign.BasicExample.ClassExample *-[#10BB10]- EnumTest 
Examples.BadDesign.BasicExample.ClassExample .[#6060BB].> Examples.BadDesign.BasicExample.Useless  : uses 
Examples.BadDesign.BasicExample.ClassExample -[#909090]-> Examples.BadDesign.BasicExample.BaseExample  : uses 
Examples.BadDesign.BasicExample.ClassExample .[#6060BB].> Examples.BadDesign.BasicExample.IExample  : uses 
Examples.BadDesign.BasicExample.AbstractBaseExample <|-[#red]- Examples.BadDesign.BasicExample.BaseExample
Examples.BadDesign.BasicExample.BaseExample +-[#10BBBB]- Examples.BadDesign.BasicExample.BaseExample_DOT_EnumTest 
Examples.BadDesign.BasicExample.BaseExample .[#6060BB].> Examples.BadDesign.BasicExample.Useless  : uses 
Examples.BadDesign.BasicExample.AbstractBaseExample .[#6060BB].> Examples.BadDesign.BasicExample.Useless  : uses 
' Class relations extracted from namespace:
' Examples.BadDesign.BasicExample.SideExample
Examples.BadDesign.BasicExample.SideExample.SideExample *-[#10BB10]- Examples.BadDesign.DB 
Examples.BadDesign.BasicExample.SideExample.SideExample .[#6060BB].> Examples.BadDesign.BasicExample.SideExample.SideTestEnum  : uses 
' Class relations extracted from namespace:
' Examples.BadDesign.CarExample
Examples.BadDesign.CarExample.Vehicle *-[#10BB10]- Examples.BadDesign.DB 
Examples.BadDesign.CarExample.CarParts.Driver <|-[#red]- Examples.BadDesign.CarExample.Car
Examples.BadDesign.CarExample.Car *-[#10BB10]- Examples.BadDesign.CarExample.CarParts.Wheels 
Examples.BadDesign.CarExample.Car *-[#10BB10]- Examples.BadDesign.CarExample.Vehicle 
Examples.BadDesign.CarExample.Car *-[#10BB10]- Examples.BadDesign.DB 
Examples.BadDesign.CarExample.Car .[#6060BB].> Examples.BadDesign.CarExample.CarParts.Doors  : uses 
Examples.BadDesign.CarExample.Car -[#909090]-> Examples.BadDesign.CarExample.CarParts.Seats  : uses 
' Class relations extracted from namespace:
' Examples.BadDesign.CarExample.CarParts
Examples.BadDesign.CarExample.CarParts.Driver *-[#10BB10]- Examples.BadDesign.DB 
Examples.BadDesign.CarExample.CarParts.Seats *-[#10BB10]- Examples.BadDesign.DB 
Examples.BadDesign.CarExample.CarParts.Wheels *-[#10BB10]- Examples.BadDesign.DB 
Examples.BadDesign.CarExample.CarParts.Doors *-[#10BB10]- Examples.BadDesign.DB 
' Class relations extracted from namespace:
' Examples.BadDesign.FakeEntitities
' Class relations extracted from namespace:
' Examples.BetterDesign
Examples.BetterDesign.DBCustomers .[#6060BB].> Examples.BetterDesign.FakeEntitities.Customer  : uses 
Examples.BetterDesign.DBCustomers .[#6060BB].> Examples.BetterDesign.FakeEntitities.Invoice  : uses 
Examples.BetterDesign.DBCustomers .[#6060BB].> Examples.BetterDesign.FakeEntitities.Item  : uses 
Examples.BetterDesign.DBCustomers .[#6060BB].> Examples.BetterDesign.FakeEntitities.Complaints  : uses 
Examples.BetterDesign.DBCustomers .[#6060BB].> Examples.BetterDesign.FakeEntitities.User  : uses 
Examples.BetterDesign.DBCar .[#6060BB].> Examples.BetterDesign.CarExample.CarParts.Driver  : uses 
Examples.BetterDesign.DBCar .[#6060BB].> Examples.BetterDesign.CarExample.Car  : uses 
Examples.BetterDesign.DBCar .[#6060BB].> Examples.BetterDesign.CarExample.CarParts.Seats  : uses 
Examples.BetterDesign.DBCar .[#6060BB].> Examples.BetterDesign.CarExample.CarParts.Doors  : uses 
Examples.BetterDesign.DBCar .[#6060BB].> Examples.BetterDesign.CarExample.CarParts.Wheels  : uses 
' Class relations extracted from namespace:
' Examples.BetterDesign.CarExample
Examples.BetterDesign.CarExample.Vehicle *-[#10BB10]- Examples.BetterDesign.DBCar 
.Vehicle <|-[#red]- Examples.BetterDesign.CarExample.Car
Examples.BetterDesign.CarExample.Car *-[#10BB10]- Examples.BetterDesign.CarExample.CarParts.Wheels 
Examples.BetterDesign.CarExample.Car *-[#10BB10]- Examples.BetterDesign.CarExample.CarParts.Seats 
Examples.BetterDesign.CarExample.Car *-[#10BB10]- Examples.BetterDesign.CarExample.CarParts.Driver 
Examples.BetterDesign.CarExample.Car *-[#10BB10]- Examples.BetterDesign.CarExample.CarParts.Doors 
Examples.BetterDesign.CarExample.Car .[#6060BB].> Examples.BetterDesign.CarExample.CarParts.Doors  : uses 
' Class relations extracted from namespace:
' Examples.BetterDesign.CarExample.CarParts
Examples.BetterDesign.CarExample.CarParts.Wheels *-[#10BB10]- Examples.BetterDesign.DBCar 
Examples.BetterDesign.CarExample.CarParts.Seats *-[#10BB10]- Examples.BetterDesign.DBCar 
Examples.BetterDesign.CarExample.CarParts.Driver *-[#10BB10]- Examples.BetterDesign.DBCar 
Examples.BetterDesign.CarExample.CarParts.Doors *-[#10BB10]- Examples.BetterDesign.DBCar 
' Class relations extracted from namespace:
' Examples.BetterDesign.FakeEntitities
' Class relations extracted from namespace:
' preadapter
preadapter.Logger *-[#10BB10]- preadapter.LoggingType 
preadapter.Revenger -[#909090]-> preadapter.Logger  : uses 
' Class relations extracted from namespace:
' preadapter.domain
preadapter.domain.Datastructure +-[#10BBBB]- preadapter.domain.Datastructure_DOT_Method 
preadapter.domain.Datastructure +-[#10BBBB]- preadapter.domain.Datastructure_DOT_Static 
preadapter.domain.Datastructure +-[#10BBBB]- preadapter.domain.Datastructure_DOT_Variable 
preadapter.domain.Datastructure +-[#10BBBB]- preadapter.domain.Datastructure_DOT_SubDataStructure 
preadapter.domain.Datastructure *-[#10BB10]- preadapter.Logger 
preadapter.domain.Datastructure -[#909090]-> Variable  : uses 
preadapter.domain.Datastructure -[#909090]-> Method  : uses 
preadapter.domain.Datastructure -[#909090]-> SubDataStructure  : uses 
preadapter.domain.Datastructure .[#6060BB].> SubDataStructure  : uses 
preadapter.domain.Datastructure_DOT_Method +-[#10BBBB]- preadapter.domain.Datastructure_DOT_Method_DOT_ParameterType 
preadapter.domain.Datastructure_DOT_Method +-[#10BBBB]- preadapter.domain.Datastructure_DOT_Method_DOT_Variable 
VoidVisitorAdapter_BRQTO_Void_BRQTC <|-[#red]- preadapter.domain.ASTVisitorDebug
preadapter.domain.ASTVisitorDebug +-[#10BBBB]- preadapter.domain.ASTVisitorDebug_DOT_HandleDeepness 
preadapter.domain.ASTVisitorDebug *-[#10BB10]- PrintStream 
preadapter.domain.ASTVisitorDebug *-[#10BB10]- HandleDeepness 
preadapter.domain.ASTVisitorDebug .[#6060BB].> AnnotationDeclaration  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> Void  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> AnnotationMemberDeclaration  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> ArrayAccessExpr  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> ArrayCreationExpr  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> ArrayCreationLevel  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> ArrayInitializerExpr  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> ArrayType  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> AssertStmt  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> AssignExpr  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> BinaryExpr  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> BlockComment  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> BlockStmt  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> BooleanLiteralExpr  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> BreakStmt  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> CastExpr  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> CatchClause  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> CharLiteralExpr  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> ClassExpr  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> ClassOrInterfaceDeclaration  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> ClassOrInterfaceType  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> CompilationUnit  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> ConditionalExpr  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> ConstructorDeclaration  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> ContinueStmt  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> DoStmt  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> DoubleLiteralExpr  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> EmptyStmt  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> EnclosedExpr  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> EnumConstantDeclaration  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> EnumDeclaration  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> ExplicitConstructorInvocationStmt  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> ExpressionStmt  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> FieldAccessExpr  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> FieldDeclaration  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> ForEachStmt  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> ForStmt  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> IfStmt  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> ImportDeclaration  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> InitializerDeclaration  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> InstanceOfExpr  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> IntegerLiteralExpr  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> IntersectionType  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> JavadocComment  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> LabeledStmt  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> LambdaExpr  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> LineComment  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> LocalClassDeclarationStmt  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> LongLiteralExpr  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> MarkerAnnotationExpr  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> MemberValuetuple  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> MethodCallExpr  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> MethodDeclaration  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> MethodReferenceExpr  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> ModuleDeclaration  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> ModuleExportsDirective  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> ModuleOpensDirective  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> ModuleProvidesDirective  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> ModuleRequiresDirective  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> ModuleUsesDirective  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> Name  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> NameExpr  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> Nodelist  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> NormalAnnotationExpr  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> NullLiteralExpr  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> ObjectCreationExpr  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> PackageDeclaration  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> Parameter  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> PrimitiveType  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> ReturnStmt  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> SimpleName  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> SingleMemberAnnotationExpr  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> StringLiteralExpr  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> SuperExpr  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> SwitchEntry  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> SwitchStmt  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> SynchronizedStmt  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> ThisExpr  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> ThrowStmt  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> TryStmt  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> TypeExpr  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> TypeParameter  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> UnaryExpr  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> UnionType  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> UnknownType  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> UnparsableStmt  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> VariableDeclarationExpr  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> VariableDeclarator  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> VoidType  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> WhileStmt  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> WildcardType  : uses 
preadapter.domain.ASTVisitorDebug -[#909090]-> CompilationUnit  : uses 
VoidVisitorAdapter_BRQTO_Void_BRQTC <|-[#red]- preadapter.domain.ASTVisitor
preadapter.domain.ASTVisitor +-[#10BBBB]- preadapter.domain.ASTVisitor_DOT_ObjectType 
preadapter.domain.ASTVisitor +-[#10BBBB]- preadapter.domain.ASTVisitor_DOT_HandleDeepness 
preadapter.domain.ASTVisitor *-[#10BB10]- preadapter.Logger 
preadapter.domain.ASTVisitor *-[#10BB10]- preadapter.domain.Datastructure 
preadapter.domain.ASTVisitor *-[#10BB10]- HandleDeepness 
preadapter.domain.ASTVisitor .[#6060BB].> ClassOrInterfaceDeclaration  : uses 
preadapter.domain.ASTVisitor -[#909090]-> preadapter.domain.Datastructure_DOT_SubDataStructure  : uses 
preadapter.domain.ASTVisitor .[#6060BB].> Type  : uses 
preadapter.domain.ASTVisitor .[#6060BB].> MethodDeclaration  : uses 
preadapter.domain.ASTVisitor .[#6060BB].> Void  : uses 
preadapter.domain.ASTVisitor -[#909090]-> Optional_DOT_empty  : uses 
preadapter.domain.ASTVisitor -[#909090]-> VariableDeclarator  : uses 
preadapter.domain.ASTVisitor -[#909090]-> preadapter.domain.Datastructure_DOT_Method  : uses 
preadapter.domain.ASTVisitor .[#6060BB].> FieldDeclaration  : uses 
preadapter.domain.ASTVisitor .[#6060BB].> PackageDeclaration  : uses 
preadapter.domain.ASTVisitor .[#6060BB].> ImportDeclaration  : uses 
preadapter.domain.ASTVisitor .[#6060BB].> EnumConstantDeclaration  : uses 
preadapter.domain.ASTVisitor .[#6060BB].> EnumDeclaration  : uses 
preadapter.domain.ASTVisitor .[#6060BB].> VariableDeclarator  : uses 
preadapter.domain.ASTVisitor -[#909090]-> CompilationUnit  : uses 
' Class relations extracted from namespace:
' preadapter.infrastructure
preadapter.infrastructure.CreateYML *-[#10BB10]- DumperOptions.FlowStyle 
preadapter.infrastructure.CreateYML *-[#10BB10]- Mark 
preadapter.infrastructure.CreateYML .[#6060BB].> dictpingNode  : uses 
preadapter.infrastructure.CreateYML .[#6060BB].> SequenceNode  : uses 
preadapter.infrastructure.CreateYML -[#909090]-> SequenceNode  : uses 
preadapter.infrastructure.CreateYML .[#6060BB].> preadapter.domain.Datastructure  : uses 
preadapter.infrastructure.CreateYML .[#6060BB].> preadapter.Logger  : uses 
preadapter.infrastructure.CreateYML -[#909090]-> preadapter.domain.Datastructure_DOT_SubDataStructure  : uses 
preadapter.infrastructure.CreateYML -[#909090]-> Yaml  : uses 
preadapter.infrastructure.CreateYML -[#909090]-> PrintWriter  : uses 
' Class relations extracted from namespace:
' preadapter.service
preadapter.service.AnalyzeAST .[#6060BB].> preadapter.Logger  : uses 
preadapter.service.AnalyzeAST -[#909090]-> preadapter.domain.Datastructure  : uses 
preadapter.service.AnalyzeAST -[#909090]-> CompilationUnit  : uses 
preadapter.service.RecursiveFileProcessor -[#909090]-> Path  : uses 
@enduml