@startuml
skinparam linetype ortho
title <size:20> **detailed** and **grouped per namespace**</size>
note "Your are analyzing:\n **detailed** and **grouped per namespace**\n\n==Filter==\nYou can click either the namespaces \nor class names for filtering them and their\ndirect dependencies.\n\n==Select other==\n*  **simplified** and **grouped per namespace**:\n   [[-diagram-simplified-grouped-per-namespace.svg]]\n* Full diagram **detailed** and **grouped per namespace**:\n   [[full-diagram-detailed-grouped-per-namespace.svg]]\n* Home:\n   [[index.html]]" as FloatingNote
class Variable [[Variable-diagram-detailed-grouped-per-namespace.svg]] #yellow {
}
class Method [[Method-diagram-detailed-grouped-per-namespace.svg]] #yellow {
}
class SubDataStructure [[SubDataStructure-diagram-detailed-grouped-per-namespace.svg]] #yellow {
}
class CompilationUnit [[CompilationUnit-diagram-detailed-grouped-per-namespace.svg]] #yellow {
}
class VoidVisitorAdapter_BRQTO_Void_BRQTC [[VoidVisitorAdapter_BRQTO_Void_BRQTC-diagram-detailed-grouped-per-namespace.svg]] #yellow {
}
class PrintStream [[PrintStream-diagram-detailed-grouped-per-namespace.svg]] #yellow {
}
class HandleDeepness [[HandleDeepness-diagram-detailed-grouped-per-namespace.svg]] #yellow {
}
class AnnotationDeclaration [[AnnotationDeclaration-diagram-detailed-grouped-per-namespace.svg]] #yellow {
}
class Void [[Void-diagram-detailed-grouped-per-namespace.svg]] #yellow {
}
class AnnotationMemberDeclaration [[AnnotationMemberDeclaration-diagram-detailed-grouped-per-namespace.svg]] #yellow {
}
class ArrayAccessExpr [[ArrayAccessExpr-diagram-detailed-grouped-per-namespace.svg]] #yellow {
}
class ArrayCreationExpr [[ArrayCreationExpr-diagram-detailed-grouped-per-namespace.svg]] #yellow {
}
class ArrayCreationLevel [[ArrayCreationLevel-diagram-detailed-grouped-per-namespace.svg]] #yellow {
}
class ArrayInitializerExpr [[ArrayInitializerExpr-diagram-detailed-grouped-per-namespace.svg]] #yellow {
}
class ArrayType [[ArrayType-diagram-detailed-grouped-per-namespace.svg]] #yellow {
}
class AssertStmt [[AssertStmt-diagram-detailed-grouped-per-namespace.svg]] #yellow {
}
class AssignExpr [[AssignExpr-diagram-detailed-grouped-per-namespace.svg]] #yellow {
}
class BinaryExpr [[BinaryExpr-diagram-detailed-grouped-per-namespace.svg]] #yellow {
}
class BlockComment [[BlockComment-diagram-detailed-grouped-per-namespace.svg]] #yellow {
}
class BlockStmt [[BlockStmt-diagram-detailed-grouped-per-namespace.svg]] #yellow {
}
class BooleanLiteralExpr [[BooleanLiteralExpr-diagram-detailed-grouped-per-namespace.svg]] #yellow {
}
class BreakStmt [[BreakStmt-diagram-detailed-grouped-per-namespace.svg]] #yellow {
}
class CastExpr [[CastExpr-diagram-detailed-grouped-per-namespace.svg]] #yellow {
}
class CatchClause [[CatchClause-diagram-detailed-grouped-per-namespace.svg]] #yellow {
}
class CharLiteralExpr [[CharLiteralExpr-diagram-detailed-grouped-per-namespace.svg]] #yellow {
}
class ClassExpr [[ClassExpr-diagram-detailed-grouped-per-namespace.svg]] #yellow {
}
class ClassOrInterfaceDeclaration [[ClassOrInterfaceDeclaration-diagram-detailed-grouped-per-namespace.svg]] #yellow {
}
class ClassOrInterfaceType [[ClassOrInterfaceType-diagram-detailed-grouped-per-namespace.svg]] #yellow {
}
class ConditionalExpr [[ConditionalExpr-diagram-detailed-grouped-per-namespace.svg]] #yellow {
}
class ConstructorDeclaration [[ConstructorDeclaration-diagram-detailed-grouped-per-namespace.svg]] #yellow {
}
class ContinueStmt [[ContinueStmt-diagram-detailed-grouped-per-namespace.svg]] #yellow {
}
class DoStmt [[DoStmt-diagram-detailed-grouped-per-namespace.svg]] #yellow {
}
class DoubleLiteralExpr [[DoubleLiteralExpr-diagram-detailed-grouped-per-namespace.svg]] #yellow {
}
class EmptyStmt [[EmptyStmt-diagram-detailed-grouped-per-namespace.svg]] #yellow {
}
class EnclosedExpr [[EnclosedExpr-diagram-detailed-grouped-per-namespace.svg]] #yellow {
}
class EnumConstantDeclaration [[EnumConstantDeclaration-diagram-detailed-grouped-per-namespace.svg]] #yellow {
}
class EnumDeclaration [[EnumDeclaration-diagram-detailed-grouped-per-namespace.svg]] #yellow {
}
class ExplicitConstructorInvocationStmt [[ExplicitConstructorInvocationStmt-diagram-detailed-grouped-per-namespace.svg]] #yellow {
}
class ExpressionStmt [[ExpressionStmt-diagram-detailed-grouped-per-namespace.svg]] #yellow {
}
class FieldAccessExpr [[FieldAccessExpr-diagram-detailed-grouped-per-namespace.svg]] #yellow {
}
class FieldDeclaration [[FieldDeclaration-diagram-detailed-grouped-per-namespace.svg]] #yellow {
}
class ForEachStmt [[ForEachStmt-diagram-detailed-grouped-per-namespace.svg]] #yellow {
}
class ForStmt [[ForStmt-diagram-detailed-grouped-per-namespace.svg]] #yellow {
}
class IfStmt [[IfStmt-diagram-detailed-grouped-per-namespace.svg]] #yellow {
}
class ImportDeclaration [[ImportDeclaration-diagram-detailed-grouped-per-namespace.svg]] #yellow {
}
class InitializerDeclaration [[InitializerDeclaration-diagram-detailed-grouped-per-namespace.svg]] #yellow {
}
class InstanceOfExpr [[InstanceOfExpr-diagram-detailed-grouped-per-namespace.svg]] #yellow {
}
class IntegerLiteralExpr [[IntegerLiteralExpr-diagram-detailed-grouped-per-namespace.svg]] #yellow {
}
class IntersectionType [[IntersectionType-diagram-detailed-grouped-per-namespace.svg]] #yellow {
}
class JavadocComment [[JavadocComment-diagram-detailed-grouped-per-namespace.svg]] #yellow {
}
class LabeledStmt [[LabeledStmt-diagram-detailed-grouped-per-namespace.svg]] #yellow {
}
class LambdaExpr [[LambdaExpr-diagram-detailed-grouped-per-namespace.svg]] #yellow {
}
class LineComment [[LineComment-diagram-detailed-grouped-per-namespace.svg]] #yellow {
}
class LocalClassDeclarationStmt [[LocalClassDeclarationStmt-diagram-detailed-grouped-per-namespace.svg]] #yellow {
}
class LongLiteralExpr [[LongLiteralExpr-diagram-detailed-grouped-per-namespace.svg]] #yellow {
}
class MarkerAnnotationExpr [[MarkerAnnotationExpr-diagram-detailed-grouped-per-namespace.svg]] #yellow {
}
class MemberValuetuple [[MemberValuetuple-diagram-detailed-grouped-per-namespace.svg]] #yellow {
}
class MethodCallExpr [[MethodCallExpr-diagram-detailed-grouped-per-namespace.svg]] #yellow {
}
class MethodDeclaration [[MethodDeclaration-diagram-detailed-grouped-per-namespace.svg]] #yellow {
}
class MethodReferenceExpr [[MethodReferenceExpr-diagram-detailed-grouped-per-namespace.svg]] #yellow {
}
class ModuleDeclaration [[ModuleDeclaration-diagram-detailed-grouped-per-namespace.svg]] #yellow {
}
class ModuleExportsDirective [[ModuleExportsDirective-diagram-detailed-grouped-per-namespace.svg]] #yellow {
}
class ModuleOpensDirective [[ModuleOpensDirective-diagram-detailed-grouped-per-namespace.svg]] #yellow {
}
class ModuleProvidesDirective [[ModuleProvidesDirective-diagram-detailed-grouped-per-namespace.svg]] #yellow {
}
class ModuleRequiresDirective [[ModuleRequiresDirective-diagram-detailed-grouped-per-namespace.svg]] #yellow {
}
class ModuleUsesDirective [[ModuleUsesDirective-diagram-detailed-grouped-per-namespace.svg]] #yellow {
}
class Name [[Name-diagram-detailed-grouped-per-namespace.svg]] #yellow {
}
class NameExpr [[NameExpr-diagram-detailed-grouped-per-namespace.svg]] #yellow {
}
class Nodelist [[Nodelist-diagram-detailed-grouped-per-namespace.svg]] #yellow {
}
class NormalAnnotationExpr [[NormalAnnotationExpr-diagram-detailed-grouped-per-namespace.svg]] #yellow {
}
class NullLiteralExpr [[NullLiteralExpr-diagram-detailed-grouped-per-namespace.svg]] #yellow {
}
class ObjectCreationExpr [[ObjectCreationExpr-diagram-detailed-grouped-per-namespace.svg]] #yellow {
}
class PackageDeclaration [[PackageDeclaration-diagram-detailed-grouped-per-namespace.svg]] #yellow {
}
class Parameter [[Parameter-diagram-detailed-grouped-per-namespace.svg]] #yellow {
}
class PrimitiveType [[PrimitiveType-diagram-detailed-grouped-per-namespace.svg]] #yellow {
}
class ReturnStmt [[ReturnStmt-diagram-detailed-grouped-per-namespace.svg]] #yellow {
}
class SimpleName [[SimpleName-diagram-detailed-grouped-per-namespace.svg]] #yellow {
}
class SingleMemberAnnotationExpr [[SingleMemberAnnotationExpr-diagram-detailed-grouped-per-namespace.svg]] #yellow {
}
class StringLiteralExpr [[StringLiteralExpr-diagram-detailed-grouped-per-namespace.svg]] #yellow {
}
class SuperExpr [[SuperExpr-diagram-detailed-grouped-per-namespace.svg]] #yellow {
}
class SwitchEntry [[SwitchEntry-diagram-detailed-grouped-per-namespace.svg]] #yellow {
}
class SwitchStmt [[SwitchStmt-diagram-detailed-grouped-per-namespace.svg]] #yellow {
}
class SynchronizedStmt [[SynchronizedStmt-diagram-detailed-grouped-per-namespace.svg]] #yellow {
}
class ThisExpr [[ThisExpr-diagram-detailed-grouped-per-namespace.svg]] #yellow {
}
class ThrowStmt [[ThrowStmt-diagram-detailed-grouped-per-namespace.svg]] #yellow {
}
class TryStmt [[TryStmt-diagram-detailed-grouped-per-namespace.svg]] #yellow {
}
class TypeExpr [[TypeExpr-diagram-detailed-grouped-per-namespace.svg]] #yellow {
}
class TypeParameter [[TypeParameter-diagram-detailed-grouped-per-namespace.svg]] #yellow {
}
class UnaryExpr [[UnaryExpr-diagram-detailed-grouped-per-namespace.svg]] #yellow {
}
class UnionType [[UnionType-diagram-detailed-grouped-per-namespace.svg]] #yellow {
}
class UnknownType [[UnknownType-diagram-detailed-grouped-per-namespace.svg]] #yellow {
}
class UnparsableStmt [[UnparsableStmt-diagram-detailed-grouped-per-namespace.svg]] #yellow {
}
class VariableDeclarationExpr [[VariableDeclarationExpr-diagram-detailed-grouped-per-namespace.svg]] #yellow {
}
class VariableDeclarator [[VariableDeclarator-diagram-detailed-grouped-per-namespace.svg]] #yellow {
}
class VoidType [[VoidType-diagram-detailed-grouped-per-namespace.svg]] #yellow {
}
class WhileStmt [[WhileStmt-diagram-detailed-grouped-per-namespace.svg]] #yellow {
}
class WildcardType [[WildcardType-diagram-detailed-grouped-per-namespace.svg]] #yellow {
}
class DumperOptions.FlowStyle [[DumperOptions.FlowStyle-diagram-detailed-grouped-per-namespace.svg]] #yellow {
}
class Mark [[Mark-diagram-detailed-grouped-per-namespace.svg]] #yellow {
}
class dictpingNode [[dictpingNode-diagram-detailed-grouped-per-namespace.svg]] #yellow {
}
class SequenceNode [[SequenceNode-diagram-detailed-grouped-per-namespace.svg]] #yellow {
}
class Yaml [[Yaml-diagram-detailed-grouped-per-namespace.svg]] #yellow {
}
class PrintWriter [[PrintWriter-diagram-detailed-grouped-per-namespace.svg]] #yellow {
}
class EnumTest [[EnumTest-diagram-detailed-grouped-per-namespace.svg]] #yellow {
}
class .Vehicle [[.Vehicle-diagram-detailed-grouped-per-namespace.svg]] #yellow {
}
class Type [[Type-diagram-detailed-grouped-per-namespace.svg]] #yellow {
}
class Optional_DOT_empty [[Optional_DOT_empty-diagram-detailed-grouped-per-namespace.svg]] #yellow {
}
class Path [[Path-diagram-detailed-grouped-per-namespace.svg]] #yellow {
}
' Closing all previous_sub_namespace_list namespace None because file analysis is finished.
namespace Examples [[Examples-diagram-detailed-grouped-per-namespace.svg]] {
namespace Examples.BadDesign [[Examples.BadDesign-diagram-detailed-grouped-per-namespace.svg]] {
  class Examples.BadDesign.DB [[Examples.BadDesign.DB-diagram-detailed-grouped-per-namespace.svg]] #yellow {
    + get(<font color="6060BB">queryString:String</font>): <font color="BB6060">String</font>
    + getCarsWhere(<font color="6060BB">whereQueryString:String</font>): <font color="BB6060">String</font>
    + set(<font color="6060BB">queryString:String</font>): <font color="BB6060">void</font>
    + update(<font color="6060BB">queryString:String</font>): <font color="BB6060">void</font>
    + getUserWhere(<font color="6060BB">query:String</font>): <font color="BB6060">Examples.BadDesign.FakeEntitities.User</font>
    + getCustomerWhere(<font color="6060BB">query:String</font>): <font color="BB6060">Examples.BadDesign.FakeEntitities.Customer</font>
    + getItemWhere(<font color="6060BB">query:String</font>): <font color="BB6060">Examples.BadDesign.FakeEntitities.Item</font>
    + getInvoiceWhere(<font color="6060BB">query:String</font>): <font color="BB6060">Examples.BadDesign.FakeEntitities.Invoice</font>
    + getComplaintsWhere(<font color="6060BB">query:String</font>): <font color="BB6060">Examples.BadDesign.FakeEntitities.Complaints</font>
    + getUserHavingItem(<font color="6060BB">item:Examples.BadDesign.FakeEntitities.Item</font>): <font color="BB6060">Examples.BadDesign.FakeEntitities.User</font>
    + getCustomerFromComplaint(<font color="6060BB">complaint:Examples.BadDesign.FakeEntitities.Complaints</font>): <font color="BB6060">Examples.BadDesign.FakeEntitities.Customer</font>
    + getItemFromUser(<font color="6060BB">user:Examples.BadDesign.FakeEntitities.User</font>): <font color="BB6060">Examples.BadDesign.FakeEntitities.Item</font>
    + getInvoiceFromCustomer(<font color="6060BB">c:Examples.BadDesign.FakeEntitities.Customer</font>): <font color="BB6060">Examples.BadDesign.FakeEntitities.Invoice</font>
    + getComplaintsFromItem(<font color="6060BB">item:Examples.BadDesign.FakeEntitities.Item</font>): <font color="BB6060">Examples.BadDesign.FakeEntitities.Complaints</font>
    + getFirstUser(<font color="6060BB"></font>): <font color="BB6060">Examples.BadDesign.FakeEntitities.User</font>
    + getFirstCustomerWhere(<font color="6060BB"></font>): <font color="BB6060">Examples.BadDesign.FakeEntitities.Customer</font>
    + getFirstItem(<font color="6060BB"></font>): <font color="BB6060">Examples.BadDesign.FakeEntitities.Item</font>
    + getFirstInvoice(<font color="6060BB"></font>): <font color="BB6060">Examples.BadDesign.FakeEntitities.Invoice</font>
    + getFirstComplaints(<font color="6060BB"></font>): <font color="BB6060">Examples.BadDesign.FakeEntitities.Complaints</font>
    + getCarFromDriver(<font color="6060BB">d:Examples.BadDesign.CarExample.CarParts.Driver</font>): <font color="BB6060">Examples.BadDesign.CarExample.Car</font>
    + getDriverFromCar(<font color="6060BB">c:Examples.BadDesign.CarExample.Car</font>): <font color="BB6060">Examples.BadDesign.CarExample.CarParts.Driver</font>
    + getWheelsFromCar(<font color="6060BB">c:Examples.BadDesign.CarExample.Car</font>): <font color="BB6060">Examples.BadDesign.CarExample.CarParts.Wheels</font>
    + getDoorsFromCar(<font color="6060BB">c:Examples.BadDesign.CarExample.Car</font>): <font color="BB6060">Examples.BadDesign.CarExample.CarParts.Doors</font>
    + getSeatsFromCar(<font color="6060BB">c:Examples.BadDesign.CarExample.Car</font>): <font color="BB6060">Examples.BadDesign.CarExample.CarParts.Seats</font>
  }
'Compared namespace Examples.BadDesign [[Examples.BadDesign-diagram-detailed-grouped-per-namespace.svg]] { with last element of   }
' Closing all previous_sub_namespace_list namespace None because file analysis is finished.
' Closing namespace BadDesign
}
' Closing namespace Examples
}
namespace Examples [[Examples-diagram-detailed-grouped-per-namespace.svg]] {
namespace Examples.BadDesign [[Examples.BadDesign-diagram-detailed-grouped-per-namespace.svg]] {
namespace Examples.BadDesign.BasicExample [[Examples.BadDesign.BasicExample-diagram-detailed-grouped-per-namespace.svg]] {
    interface Examples.BadDesign.BasicExample.IExample [[Examples.BadDesign.BasicExample.IExample-diagram-detailed-grouped-per-namespace.svg]] #yellow {
      + example(<font color="6060BB">useless1:Examples.BadDesign.BasicExample.Useless, useless2:Examples.BadDesign.BasicExample.Useless</font>): <font color="BB6060">void</font>
    }
    class Examples.BadDesign.BasicExample.Useless [[Examples.BadDesign.BasicExample.Useless-diagram-detailed-grouped-per-namespace.svg]] #yellow {
      + db: Examples.BadDesign.DB
==
      + useless(<font color="6060BB"></font>): <font color="BB6060">void</font>
      - <font color="909090">useless.testEnum: Examples.BadDesign.BasicExample.SideExample.SideTestEnum</font>
--
    }
    class Examples.BadDesign.BasicExample.ClassExample_DOT_InnerClassExample [[Examples.BadDesign.BasicExample.ClassExample_DOT_InnerClassExample-diagram-detailed-grouped-per-namespace.svg]] #yellow {
    }
    class Examples.BadDesign.BasicExample.ClassExample_DOT_InnerClassExample_DOT_classInMethodExample [[Examples.BadDesign.BasicExample.ClassExample_DOT_InnerClassExample_DOT_classInMethodExample-diagram-detailed-grouped-per-namespace.svg]] #yellow {
    }
    class Examples.BadDesign.BasicExample.BaseExample_DOT_EnumTest [[Examples.BadDesign.BasicExample.BaseExample_DOT_EnumTest-diagram-detailed-grouped-per-namespace.svg]] #yellow {
    }
    class Examples.BadDesign.BasicExample.ClassExample [[Examples.BadDesign.BasicExample.ClassExample-diagram-detailed-grouped-per-namespace.svg]] #yellow {
      + memberVarUseless: Examples.BadDesign.BasicExample.Useless
      + memberVarEnumTest: EnumTest
==
      + example(<font color="6060BB">useless1:Examples.BadDesign.BasicExample.Useless, useless2:Examples.BadDesign.BasicExample.Useless</font>): <font color="BB6060">void</font>
      - <font color="909090">example.localVarBaseExample: Examples.BadDesign.BasicExample.BaseExample</font>
--
      + getExample(<font color="6060BB"></font>): <font color="BB6060">Examples.BadDesign.BasicExample.IExample</font>
      + exampleAbstract(<font color="6060BB">useless1:Examples.BadDesign.BasicExample.Useless, useless2:Examples.BadDesign.BasicExample.Useless</font>): <font color="BB6060">Examples.BadDesign.BasicExample.Useless</font>
    }
    class Examples.BadDesign.BasicExample.BaseExample [[Examples.BadDesign.BasicExample.BaseExample-diagram-detailed-grouped-per-namespace.svg]] #yellow {
      + exampleAbstract(<font color="6060BB">useless1:Examples.BadDesign.BasicExample.Useless, useless2:Examples.BadDesign.BasicExample.Useless</font>): <font color="BB6060">Examples.BadDesign.BasicExample.Useless</font>
      + otherExample(<font color="6060BB"></font>): <font color="BB6060">void</font>
    }
    abstract class Examples.BadDesign.BasicExample.AbstractBaseExample [[Examples.BadDesign.BasicExample.AbstractBaseExample-diagram-detailed-grouped-per-namespace.svg]] #yellow {
      + exampleAbstract(<font color="6060BB">useless1:Examples.BadDesign.BasicExample.Useless, useless2:Examples.BadDesign.BasicExample.Useless</font>): <font color="BB6060">Examples.BadDesign.BasicExample.Useless</font>
    }
'Compared namespace Examples.BadDesign.BasicExample [[Examples.BadDesign.BasicExample-diagram-detailed-grouped-per-namespace.svg]] { with last element of     }
' Closing all previous_sub_namespace_list namespace None because file analysis is finished.
' Closing namespace BasicExample
}
' Closing namespace BadDesign
}
' Closing namespace Examples
}
namespace Examples [[Examples-diagram-detailed-grouped-per-namespace.svg]] {
namespace Examples.BadDesign [[Examples.BadDesign-diagram-detailed-grouped-per-namespace.svg]] {
namespace Examples.BadDesign.BasicExample [[Examples.BadDesign.BasicExample-diagram-detailed-grouped-per-namespace.svg]] {
namespace Examples.BadDesign.BasicExample.SideExample [[Examples.BadDesign.BasicExample.SideExample-diagram-detailed-grouped-per-namespace.svg]] {
      class Examples.BadDesign.BasicExample.SideExample.SideTestEnum [[Examples.BadDesign.BasicExample.SideExample.SideTestEnum-diagram-detailed-grouped-per-namespace.svg]] #yellow {
        + TestEnumValue1: EnumTypePlaceHolder
        + TestEnumValue2: EnumTypePlaceHolder
==
      }
      class Examples.BadDesign.BasicExample.SideExample.SideExample [[Examples.BadDesign.BasicExample.SideExample.SideExample-diagram-detailed-grouped-per-namespace.svg]] #yellow {
        + db: Examples.BadDesign.DB
==
        + test(<font color="6060BB">testEnum:Examples.BadDesign.BasicExample.SideExample.SideTestEnum</font>): <font color="BB6060">void</font>
        + testNoParameter(<font color="6060BB"></font>): <font color="BB6060">void</font>
      }
'Compared namespace Examples.BadDesign.BasicExample.SideExample [[Examples.BadDesign.BasicExample.SideExample-diagram-detailed-grouped-per-namespace.svg]] { with last element of       }
' Closing all previous_sub_namespace_list namespace None because file analysis is finished.
' Closing namespace SideExample
}
' Closing namespace BasicExample
}
' Closing namespace BadDesign
}
' Closing namespace Examples
}
namespace Examples [[Examples-diagram-detailed-grouped-per-namespace.svg]] {
namespace Examples.BadDesign [[Examples.BadDesign-diagram-detailed-grouped-per-namespace.svg]] {
namespace Examples.BadDesign.CarExample [[Examples.BadDesign.CarExample-diagram-detailed-grouped-per-namespace.svg]] {
    class Examples.BadDesign.CarExample.Vehicle [[Examples.BadDesign.CarExample.Vehicle-diagram-detailed-grouped-per-namespace.svg]] #yellow {
      + db: Examples.BadDesign.DB
==
      + setSpeed(<font color="6060BB">speed:int</font>): <font color="BB6060">void</font>
      + getSpeed(<font color="6060BB"></font>): <font color="BB6060">int</font>
    }
    class Examples.BadDesign.CarExample.Car [[Examples.BadDesign.CarExample.Car-diagram-detailed-grouped-per-namespace.svg]] #yellow {
      + wheels: Examples.BadDesign.CarExample.CarParts.Wheels
      + vehicle: Examples.BadDesign.CarExample.Vehicle
      + db: Examples.BadDesign.DB
==
      + createCar(<font color="6060BB">doors:Examples.BadDesign.CarExample.CarParts.Doors</font>): <font color="BB6060">void</font>
      - <font color="909090">createCar.seats: Examples.BadDesign.CarExample.CarParts.Seats</font>
--
    }
'Compared namespace Examples.BadDesign.CarExample [[Examples.BadDesign.CarExample-diagram-detailed-grouped-per-namespace.svg]] { with last element of     }
' Closing all previous_sub_namespace_list namespace None because file analysis is finished.
' Closing namespace CarExample
}
' Closing namespace BadDesign
}
' Closing namespace Examples
}
namespace Examples [[Examples-diagram-detailed-grouped-per-namespace.svg]] {
namespace Examples.BadDesign [[Examples.BadDesign-diagram-detailed-grouped-per-namespace.svg]] {
namespace Examples.BadDesign.CarExample [[Examples.BadDesign.CarExample-diagram-detailed-grouped-per-namespace.svg]] {
namespace Examples.BadDesign.CarExample.CarParts [[Examples.BadDesign.CarExample.CarParts-diagram-detailed-grouped-per-namespace.svg]] {
      class Examples.BadDesign.CarExample.CarParts.Driver [[Examples.BadDesign.CarExample.CarParts.Driver-diagram-detailed-grouped-per-namespace.svg]] #yellow {
        + db: Examples.BadDesign.DB
==
        + getWeight(<font color="6060BB"></font>): <font color="BB6060">int</font>
      }
      class Examples.BadDesign.CarExample.CarParts.Seats [[Examples.BadDesign.CarExample.CarParts.Seats-diagram-detailed-grouped-per-namespace.svg]] #yellow {
        + db: Examples.BadDesign.DB
==
        + getWeight(<font color="6060BB"></font>): <font color="BB6060">int</font>
      }
      class Examples.BadDesign.CarExample.CarParts.Wheels [[Examples.BadDesign.CarExample.CarParts.Wheels-diagram-detailed-grouped-per-namespace.svg]] #yellow {
        + db: Examples.BadDesign.DB
==
        + getWeight(<font color="6060BB"></font>): <font color="BB6060">int</font>
      }
      class Examples.BadDesign.CarExample.CarParts.Doors [[Examples.BadDesign.CarExample.CarParts.Doors-diagram-detailed-grouped-per-namespace.svg]] #yellow {
        + db: Examples.BadDesign.DB
==
        + getWeight(<font color="6060BB"></font>): <font color="BB6060">int</font>
      }
'Compared namespace Examples.BadDesign.CarExample.CarParts [[Examples.BadDesign.CarExample.CarParts-diagram-detailed-grouped-per-namespace.svg]] { with last element of       }
' Closing all previous_sub_namespace_list namespace None because file analysis is finished.
' Closing namespace CarParts
}
' Closing namespace CarExample
}
' Closing namespace BadDesign
}
' Closing namespace Examples
}
namespace Examples [[Examples-diagram-detailed-grouped-per-namespace.svg]] {
namespace Examples.BadDesign [[Examples.BadDesign-diagram-detailed-grouped-per-namespace.svg]] {
namespace Examples.BadDesign.FakeEntitities [[Examples.BadDesign.FakeEntitities-diagram-detailed-grouped-per-namespace.svg]] {
    class Examples.BadDesign.FakeEntitities.Invoice [[Examples.BadDesign.FakeEntitities.Invoice-diagram-detailed-grouped-per-namespace.svg]] #yellow {
    }
    class Examples.BadDesign.FakeEntitities.Item [[Examples.BadDesign.FakeEntitities.Item-diagram-detailed-grouped-per-namespace.svg]] #yellow {
    }
    class Examples.BadDesign.FakeEntitities.Customer [[Examples.BadDesign.FakeEntitities.Customer-diagram-detailed-grouped-per-namespace.svg]] #yellow {
    }
    class Examples.BadDesign.FakeEntitities.User [[Examples.BadDesign.FakeEntitities.User-diagram-detailed-grouped-per-namespace.svg]] #yellow {
    }
    class Examples.BadDesign.FakeEntitities.Complaints [[Examples.BadDesign.FakeEntitities.Complaints-diagram-detailed-grouped-per-namespace.svg]] #yellow {
    }
'Compared namespace Examples.BadDesign.FakeEntitities [[Examples.BadDesign.FakeEntitities-diagram-detailed-grouped-per-namespace.svg]] { with last element of     }
' Closing all previous_sub_namespace_list namespace None because file analysis is finished.
' Closing namespace FakeEntitities
}
' Closing namespace BadDesign
}
' Closing namespace Examples
}
namespace Examples [[Examples-diagram-detailed-grouped-per-namespace.svg]] {
namespace Examples.BetterDesign [[Examples.BetterDesign-diagram-detailed-grouped-per-namespace.svg]] {
  class Examples.BetterDesign.DBCustomers [[Examples.BetterDesign.DBCustomers-diagram-detailed-grouped-per-namespace.svg]] #yellow {
    + getCustomer(<font color="6060BB">i:Examples.BetterDesign.FakeEntitities.Invoice</font>): <font color="BB6060">Examples.BetterDesign.FakeEntitities.Customer</font>
    + getItem(<font color="6060BB">c:Examples.BetterDesign.FakeEntitities.Complaints</font>): <font color="BB6060">Examples.BetterDesign.FakeEntitities.Item</font>
    + getInvoice(<font color="6060BB">c:Examples.BetterDesign.FakeEntitities.Customer</font>): <font color="BB6060">Examples.BetterDesign.FakeEntitities.Invoice</font>
    + getComplaints(<font color="6060BB">c:Examples.BetterDesign.FakeEntitities.Customer</font>): <font color="BB6060">Examples.BetterDesign.FakeEntitities.Complaints</font>
    + getUser(<font color="6060BB">item:Examples.BetterDesign.FakeEntitities.Item</font>): <font color="BB6060">Examples.BetterDesign.FakeEntitities.User</font>
    + getCustomer(<font color="6060BB">complaint:Examples.BetterDesign.FakeEntitities.Complaints</font>): <font color="BB6060">Examples.BetterDesign.FakeEntitities.Customer</font>
    + getItem(<font color="6060BB">user:Examples.BetterDesign.FakeEntitities.User</font>): <font color="BB6060">Examples.BetterDesign.FakeEntitities.Item</font>
    + getComplaints(<font color="6060BB">item:Examples.BetterDesign.FakeEntitities.Item</font>): <font color="BB6060">Examples.BetterDesign.FakeEntitities.Complaints</font>
    + getFirstUser(<font color="6060BB"></font>): <font color="BB6060">Examples.BetterDesign.FakeEntitities.User</font>
    + getFirstItem(<font color="6060BB"></font>): <font color="BB6060">Examples.BetterDesign.FakeEntitities.Item</font>
    + getFirstInvoice(<font color="6060BB"></font>): <font color="BB6060">Examples.BetterDesign.FakeEntitities.Invoice</font>
    + getFirstComplaints(<font color="6060BB"></font>): <font color="BB6060">Examples.BetterDesign.FakeEntitities.Complaints</font>
  }
  class Examples.BetterDesign.DBCar [[Examples.BetterDesign.DBCar-diagram-detailed-grouped-per-namespace.svg]] #yellow {
    + getCarsForDriver(<font color="6060BB">driver:Examples.BetterDesign.CarExample.CarParts.Driver</font>): <font color="BB6060">String</font>
    + updateCar(<font color="6060BB">car:Examples.BetterDesign.CarExample.Car, seats:Examples.BetterDesign.CarExample.CarParts.Seats</font>): <font color="BB6060">void</font>
    + updateCar(<font color="6060BB">car:Examples.BetterDesign.CarExample.Car, doors:Examples.BetterDesign.CarExample.CarParts.Doors</font>): <font color="BB6060">void</font>
    + sellCarTo(<font color="6060BB">car:Examples.BetterDesign.CarExample.Car, driver:Examples.BetterDesign.CarExample.CarParts.Driver</font>): <font color="BB6060">void</font>
    + getCarFromDriver(<font color="6060BB">d:Examples.BetterDesign.CarExample.CarParts.Driver</font>): <font color="BB6060">Examples.BetterDesign.CarExample.Car</font>
    + getDriverFromCar(<font color="6060BB">c:Examples.BetterDesign.CarExample.Car</font>): <font color="BB6060">Examples.BetterDesign.CarExample.CarParts.Driver</font>
    + getWheelsFromCar(<font color="6060BB">c:Examples.BetterDesign.CarExample.Car</font>): <font color="BB6060">Examples.BetterDesign.CarExample.CarParts.Wheels</font>
    + getDoorsFromCar(<font color="6060BB">c:Examples.BetterDesign.CarExample.Car</font>): <font color="BB6060">Examples.BetterDesign.CarExample.CarParts.Doors</font>
    + getSeatsFromCar(<font color="6060BB">c:Examples.BetterDesign.CarExample.Car</font>): <font color="BB6060">Examples.BetterDesign.CarExample.CarParts.Seats</font>
  }
'Compared namespace Examples.BetterDesign [[Examples.BetterDesign-diagram-detailed-grouped-per-namespace.svg]] { with last element of   }
' Closing all previous_sub_namespace_list namespace None because file analysis is finished.
' Closing namespace BetterDesign
}
' Closing namespace Examples
}
namespace Examples [[Examples-diagram-detailed-grouped-per-namespace.svg]] {
namespace Examples.BetterDesign [[Examples.BetterDesign-diagram-detailed-grouped-per-namespace.svg]] {
namespace Examples.BetterDesign.CarExample [[Examples.BetterDesign.CarExample-diagram-detailed-grouped-per-namespace.svg]] {
    class Examples.BetterDesign.CarExample.Vehicle [[Examples.BetterDesign.CarExample.Vehicle-diagram-detailed-grouped-per-namespace.svg]] #yellow {
      + db: Examples.BetterDesign.DBCar
==
      + setSpeed(<font color="6060BB">speed:int</font>): <font color="BB6060">void</font>
      + getSpeed(<font color="6060BB"></font>): <font color="BB6060">int</font>
    }
    class Examples.BetterDesign.CarExample.Car [[Examples.BetterDesign.CarExample.Car-diagram-detailed-grouped-per-namespace.svg]] #yellow {
      + wheels: Examples.BetterDesign.CarExample.CarParts.Wheels
      + seats: Examples.BetterDesign.CarExample.CarParts.Seats
      + driver: Examples.BetterDesign.CarExample.CarParts.Driver
      + doors: Examples.BetterDesign.CarExample.CarParts.Doors
==
      + createCar(<font color="6060BB">doors:Examples.BetterDesign.CarExample.CarParts.Doors</font>): <font color="BB6060">void</font>
    }
'Compared namespace Examples.BetterDesign.CarExample [[Examples.BetterDesign.CarExample-diagram-detailed-grouped-per-namespace.svg]] { with last element of     }
' Closing all previous_sub_namespace_list namespace None because file analysis is finished.
' Closing namespace CarExample
}
' Closing namespace BetterDesign
}
' Closing namespace Examples
}
namespace Examples [[Examples-diagram-detailed-grouped-per-namespace.svg]] {
namespace Examples.BetterDesign [[Examples.BetterDesign-diagram-detailed-grouped-per-namespace.svg]] {
namespace Examples.BetterDesign.CarExample [[Examples.BetterDesign.CarExample-diagram-detailed-grouped-per-namespace.svg]] {
namespace Examples.BetterDesign.CarExample.CarParts [[Examples.BetterDesign.CarExample.CarParts-diagram-detailed-grouped-per-namespace.svg]] {
      class Examples.BetterDesign.CarExample.CarParts.Wheels [[Examples.BetterDesign.CarExample.CarParts.Wheels-diagram-detailed-grouped-per-namespace.svg]] #yellow {
        + db: Examples.BetterDesign.DBCar
==
        + getWeight(<font color="6060BB"></font>): <font color="BB6060">int</font>
      }
      class Examples.BetterDesign.CarExample.CarParts.Seats [[Examples.BetterDesign.CarExample.CarParts.Seats-diagram-detailed-grouped-per-namespace.svg]] #yellow {
        + db: Examples.BetterDesign.DBCar
==
        + getWeight(<font color="6060BB"></font>): <font color="BB6060">int</font>
      }
      class Examples.BetterDesign.CarExample.CarParts.Driver [[Examples.BetterDesign.CarExample.CarParts.Driver-diagram-detailed-grouped-per-namespace.svg]] #yellow {
        + db: Examples.BetterDesign.DBCar
==
        + getWeight(<font color="6060BB"></font>): <font color="BB6060">int</font>
      }
      class Examples.BetterDesign.CarExample.CarParts.Doors [[Examples.BetterDesign.CarExample.CarParts.Doors-diagram-detailed-grouped-per-namespace.svg]] #yellow {
        + db: Examples.BetterDesign.DBCar
==
        + getWeight(<font color="6060BB"></font>): <font color="BB6060">int</font>
      }
'Compared namespace Examples.BetterDesign.CarExample.CarParts [[Examples.BetterDesign.CarExample.CarParts-diagram-detailed-grouped-per-namespace.svg]] { with last element of       }
' Closing all previous_sub_namespace_list namespace None because file analysis is finished.
' Closing namespace CarParts
}
' Closing namespace CarExample
}
' Closing namespace BetterDesign
}
' Closing namespace Examples
}
namespace Examples [[Examples-diagram-detailed-grouped-per-namespace.svg]] {
namespace Examples.BetterDesign [[Examples.BetterDesign-diagram-detailed-grouped-per-namespace.svg]] {
namespace Examples.BetterDesign.FakeEntitities [[Examples.BetterDesign.FakeEntitities-diagram-detailed-grouped-per-namespace.svg]] {
    class Examples.BetterDesign.FakeEntitities.Item [[Examples.BetterDesign.FakeEntitities.Item-diagram-detailed-grouped-per-namespace.svg]] #yellow {
    }
    class Examples.BetterDesign.FakeEntitities.Customer [[Examples.BetterDesign.FakeEntitities.Customer-diagram-detailed-grouped-per-namespace.svg]] #yellow {
    }
    class Examples.BetterDesign.FakeEntitities.Invoice [[Examples.BetterDesign.FakeEntitities.Invoice-diagram-detailed-grouped-per-namespace.svg]] #yellow {
    }
    class Examples.BetterDesign.FakeEntitities.Complaints [[Examples.BetterDesign.FakeEntitities.Complaints-diagram-detailed-grouped-per-namespace.svg]] #yellow {
    }
    class Examples.BetterDesign.FakeEntitities.User [[Examples.BetterDesign.FakeEntitities.User-diagram-detailed-grouped-per-namespace.svg]] #yellow {
    }
'Compared namespace Examples.BetterDesign.FakeEntitities [[Examples.BetterDesign.FakeEntitities-diagram-detailed-grouped-per-namespace.svg]] { with last element of     }
' Closing all previous_sub_namespace_list namespace None because file analysis is finished.
' Closing namespace FakeEntitities
}
' Closing namespace BetterDesign
}
' Closing namespace Examples
}
namespace preadapter [[preadapter-diagram-detailed-grouped-per-namespace.svg]] {
class preadapter.Logger [[preadapter.Logger-diagram-detailed-grouped-per-namespace.svg]] #yellow {
  + loggingType: preadapter.LoggingType
==
  - log(<font color="6060BB">logType:String, text:String, startText:String</font>): <font color="BB6060">void</font>
  - <font color="909090">log.result: String[]</font>
--
  + logError(<font color="6060BB">text:String, startText:String</font>): <font color="BB6060">void</font>
  + logError(<font color="6060BB">text:String</font>): <font color="BB6060">void</font>
  + logWarning(<font color="6060BB">text:String, startText:String</font>): <font color="BB6060">void</font>
  + logWarning(<font color="6060BB">text:String</font>): <font color="BB6060">void</font>
  + logInfo(<font color="6060BB">text:String, startText:String</font>): <font color="BB6060">void</font>
  + logInfo(<font color="6060BB">text:String</font>): <font color="BB6060">void</font>
  + logDebug(<font color="6060BB">text:String, startText:String</font>): <font color="BB6060">void</font>
  + logDebug(<font color="6060BB">text:String</font>): <font color="BB6060">void</font>
  + logTrace(<font color="6060BB">text:String, startText:String</font>): <font color="BB6060">void</font>
  + logTrace(<font color="6060BB">text:String</font>): <font color="BB6060">void</font>
}
class preadapter.LoggingType [[preadapter.LoggingType-diagram-detailed-grouped-per-namespace.svg]] #yellow {
  + TRACE: EnumTypePlaceHolder
  + DEBUG: EnumTypePlaceHolder
  + INFO: EnumTypePlaceHolder
  + WARNING: EnumTypePlaceHolder
  + ERROR: EnumTypePlaceHolder
==
  + getValue(<font color="6060BB"></font>): <font color="BB6060">int</font>
}
class preadapter.Revenger [[preadapter.Revenger-diagram-detailed-grouped-per-namespace.svg]] #yellow {
  + main(<font color="6060BB">args:String</font>): <font color="BB6060">void</font>
  - <font color="909090">main.from_dir: String</font>
  - <font color="909090">main.to_dir: String</font>
  - <font color="909090">main.logger: preadapter.Logger</font>
  - <font color="909090">main.index: int</font>
--
}
'Compared namespace preadapter [[preadapter-diagram-detailed-grouped-per-namespace.svg]] { with last element of }
' Closing all previous_sub_namespace_list namespace None because file analysis is finished.
' Closing namespace preadapter
}
namespace preadapter [[preadapter-diagram-detailed-grouped-per-namespace.svg]] {
namespace preadapter.domain [[preadapter.domain-diagram-detailed-grouped-per-namespace.svg]] {
  class preadapter.domain.Datastructure [[preadapter.domain.Datastructure-diagram-detailed-grouped-per-namespace.svg]] #yellow {
    + class_to_datastructure: dict[String,SubDataStructure]
    + namespace_to_datastructures: dict[String,list[SubDataStructure]]
    + namespace_to_namespace_list: dict[String,list[String]]
    + skip_types: list[String]
    + logger: preadapter.Logger
==
    + ResolveClassNames(<font color="6060BB"></font>): <font color="BB6060">void</font>
    - <font color="909090">ResolveClassNames.variables: list[Variable]</font>
    - <font color="909090">ResolveClassNames.variable: Variable</font>
    - <font color="909090">ResolveClassNames.index: int</font>
    - <font color="909090">ResolveClassNames.index: int</font>
    - <font color="909090">ResolveClassNames.index: int</font>
    - <font color="909090">ResolveClassNames.method: Method</font>
    - <font color="909090">ResolveClassNames.subDataStructure: SubDataStructure</font>
--
    - CorrectClassScope(<font color="6060BB">subDataStructure:SubDataStructure, classNameList:list[String], isAnymousCall:boolean</font>): <font color="BB6060">void</font>
    - <font color="909090">CorrectClassScope.index: int</font>
--
    + GetFQDNForUsedClassName(<font color="6060BB">subDataStructure:SubDataStructure, classUsage:String, isAnonymousCall:boolean, mostProbableNamespace:String</font>): <font color="BB6060">String</font>
    - <font color="909090">GetFQDNForUsedClassName.className: String</font>
    - <font color="909090">GetFQDNForUsedClassName.classnameList: list[String]</font>
    - <font color="909090">GetFQDNForUsedClassName.finalClassName: String</font>
    - <font color="909090">GetFQDNForUsedClassName.fittingClassNames: list[String]</font>
    - <font color="909090">GetFQDNForUsedClassName.classNameFromImports: list[String]</font>
    - <font color="909090">GetFQDNForUsedClassName.classNameEndingInPackageImport: list[String]</font>
    - <font color="909090">GetFQDNForUsedClassName.fqdnClassName: String</font>
    - <font color="909090">GetFQDNForUsedClassName.fqdnFromPackageImport: list[String]</font>
    - <font color="909090">GetFQDNForUsedClassName.bestFittingClassNames: list[String]</font>
--
    + get_skip_types(<font color="6060BB"></font>): <font color="BB6060">list[String]</font>
--
    + append_sub_datastructure(<font color="6060BB">sub_datastructure:SubDataStructure</font>): <font color="BB6060">void</font>
    - <font color="909090">append_sub_datastructure.fqdn_class_name: String</font>
    - <font color="909090">append_sub_datastructure.namespace_name: String</font>
--
    + append_class(<font color="6060BB">filename:String, filemodule:String, usings:list[String], fqdn_class_name:String, nameSpaceList:list[String]</font>): <font color="BB6060">SubDataStructure</font>
    - <font color="909090">append_class.sub_datastructure: SubDataStructure</font>
--
    + get_classname_list(<font color="6060BB"></font>): <font color="BB6060">list[String]</font>
    + get_datastructures_from_class_name(<font color="6060BB">class_name:String</font>): <font color="BB6060">SubDataStructure</font>
  }
  class preadapter.domain.Datastructure_DOT_Method [[preadapter.domain.Datastructure_DOT_Method-diagram-detailed-grouped-per-namespace.svg]] #yellow {
  }
  class preadapter.domain.Datastructure_DOT_Static [[preadapter.domain.Datastructure_DOT_Static-diagram-detailed-grouped-per-namespace.svg]] #yellow {
  }
  class preadapter.domain.Datastructure_DOT_Variable [[preadapter.domain.Datastructure_DOT_Variable-diagram-detailed-grouped-per-namespace.svg]] #yellow {
  }
  class preadapter.domain.Datastructure_DOT_SubDataStructure [[preadapter.domain.Datastructure_DOT_SubDataStructure-diagram-detailed-grouped-per-namespace.svg]] #yellow {
  }
  class preadapter.domain.ASTVisitorDebug_DOT_HandleDeepness [[preadapter.domain.ASTVisitorDebug_DOT_HandleDeepness-diagram-detailed-grouped-per-namespace.svg]] #yellow {
  }
  class preadapter.domain.ASTVisitorDebug [[preadapter.domain.ASTVisitorDebug-diagram-detailed-grouped-per-namespace.svg]] #yellow {
    + out: PrintStream
    + deepness: HandleDeepness
==
    + visit(<font color="6060BB">n:AnnotationDeclaration, arg:Void</font>): <font color="BB6060">void</font>
    + visit(<font color="6060BB">n:AnnotationMemberDeclaration, arg:Void</font>): <font color="BB6060">void</font>
    + visit(<font color="6060BB">n:ArrayAccessExpr, arg:Void</font>): <font color="BB6060">void</font>
    + visit(<font color="6060BB">n:ArrayCreationExpr, arg:Void</font>): <font color="BB6060">void</font>
    + visit(<font color="6060BB">n:ArrayCreationLevel, arg:Void</font>): <font color="BB6060">void</font>
    + visit(<font color="6060BB">n:ArrayInitializerExpr, arg:Void</font>): <font color="BB6060">void</font>
    + visit(<font color="6060BB">n:ArrayType, arg:Void</font>): <font color="BB6060">void</font>
    + visit(<font color="6060BB">n:AssertStmt, arg:Void</font>): <font color="BB6060">void</font>
    + visit(<font color="6060BB">n:AssignExpr, arg:Void</font>): <font color="BB6060">void</font>
    + visit(<font color="6060BB">n:BinaryExpr, arg:Void</font>): <font color="BB6060">void</font>
    + visit(<font color="6060BB">n:BlockComment, arg:Void</font>): <font color="BB6060">void</font>
    + visit(<font color="6060BB">n:BlockStmt, arg:Void</font>): <font color="BB6060">void</font>
    + visit(<font color="6060BB">n:BooleanLiteralExpr, arg:Void</font>): <font color="BB6060">void</font>
    + visit(<font color="6060BB">n:BreakStmt, arg:Void</font>): <font color="BB6060">void</font>
    + visit(<font color="6060BB">n:CastExpr, arg:Void</font>): <font color="BB6060">void</font>
    + visit(<font color="6060BB">n:CatchClause, arg:Void</font>): <font color="BB6060">void</font>
    + visit(<font color="6060BB">n:CharLiteralExpr, arg:Void</font>): <font color="BB6060">void</font>
    + visit(<font color="6060BB">n:ClassExpr, arg:Void</font>): <font color="BB6060">void</font>
    + visit(<font color="6060BB">n:ClassOrInterfaceDeclaration, arg:Void</font>): <font color="BB6060">void</font>
    + visit(<font color="6060BB">n:ClassOrInterfaceType, arg:Void</font>): <font color="BB6060">void</font>
    + visit(<font color="6060BB">n:CompilationUnit, arg:Void</font>): <font color="BB6060">void</font>
    + visit(<font color="6060BB">n:ConditionalExpr, arg:Void</font>): <font color="BB6060">void</font>
    + visit(<font color="6060BB">n:ConstructorDeclaration, arg:Void</font>): <font color="BB6060">void</font>
    + visit(<font color="6060BB">n:ContinueStmt, arg:Void</font>): <font color="BB6060">void</font>
    + visit(<font color="6060BB">n:DoStmt, arg:Void</font>): <font color="BB6060">void</font>
    + visit(<font color="6060BB">n:DoubleLiteralExpr, arg:Void</font>): <font color="BB6060">void</font>
    + visit(<font color="6060BB">n:EmptyStmt, arg:Void</font>): <font color="BB6060">void</font>
    + visit(<font color="6060BB">n:EnclosedExpr, arg:Void</font>): <font color="BB6060">void</font>
    + visit(<font color="6060BB">n:EnumConstantDeclaration, arg:Void</font>): <font color="BB6060">void</font>
    + visit(<font color="6060BB">n:EnumDeclaration, arg:Void</font>): <font color="BB6060">void</font>
    + visit(<font color="6060BB">n:ExplicitConstructorInvocationStmt, arg:Void</font>): <font color="BB6060">void</font>
    + visit(<font color="6060BB">n:ExpressionStmt, arg:Void</font>): <font color="BB6060">void</font>
    + visit(<font color="6060BB">n:FieldAccessExpr, arg:Void</font>): <font color="BB6060">void</font>
    + visit(<font color="6060BB">n:FieldDeclaration, arg:Void</font>): <font color="BB6060">void</font>
    + visit(<font color="6060BB">n:ForEachStmt, arg:Void</font>): <font color="BB6060">void</font>
    + visit(<font color="6060BB">n:ForStmt, arg:Void</font>): <font color="BB6060">void</font>
    + visit(<font color="6060BB">n:IfStmt, arg:Void</font>): <font color="BB6060">void</font>
    + visit(<font color="6060BB">n:ImportDeclaration, arg:Void</font>): <font color="BB6060">void</font>
    + visit(<font color="6060BB">n:InitializerDeclaration, arg:Void</font>): <font color="BB6060">void</font>
    + visit(<font color="6060BB">n:InstanceOfExpr, arg:Void</font>): <font color="BB6060">void</font>
    + visit(<font color="6060BB">n:IntegerLiteralExpr, arg:Void</font>): <font color="BB6060">void</font>
    + visit(<font color="6060BB">n:IntersectionType, arg:Void</font>): <font color="BB6060">void</font>
    + visit(<font color="6060BB">n:JavadocComment, arg:Void</font>): <font color="BB6060">void</font>
    + visit(<font color="6060BB">n:LabeledStmt, arg:Void</font>): <font color="BB6060">void</font>
    + visit(<font color="6060BB">n:LambdaExpr, arg:Void</font>): <font color="BB6060">void</font>
    + visit(<font color="6060BB">n:LineComment, arg:Void</font>): <font color="BB6060">void</font>
    + visit(<font color="6060BB">n:LocalClassDeclarationStmt, arg:Void</font>): <font color="BB6060">void</font>
    + visit(<font color="6060BB">n:LongLiteralExpr, arg:Void</font>): <font color="BB6060">void</font>
    + visit(<font color="6060BB">n:MarkerAnnotationExpr, arg:Void</font>): <font color="BB6060">void</font>
    + visit(<font color="6060BB">n:MemberValuetuple, arg:Void</font>): <font color="BB6060">void</font>
    + visit(<font color="6060BB">n:MethodCallExpr, arg:Void</font>): <font color="BB6060">void</font>
    + visit(<font color="6060BB">n:MethodDeclaration, arg:Void</font>): <font color="BB6060">void</font>
    + visit(<font color="6060BB">n:MethodReferenceExpr, arg:Void</font>): <font color="BB6060">void</font>
    + visit(<font color="6060BB">n:ModuleDeclaration, arg:Void</font>): <font color="BB6060">void</font>
    + visit(<font color="6060BB">n:ModuleExportsDirective, arg:Void</font>): <font color="BB6060">void</font>
    + visit(<font color="6060BB">n:ModuleOpensDirective, arg:Void</font>): <font color="BB6060">void</font>
    + visit(<font color="6060BB">n:ModuleProvidesDirective, arg:Void</font>): <font color="BB6060">void</font>
    + visit(<font color="6060BB">n:ModuleRequiresDirective, arg:Void</font>): <font color="BB6060">void</font>
    + visit(<font color="6060BB">n:ModuleUsesDirective, arg:Void</font>): <font color="BB6060">void</font>
    + visit(<font color="6060BB">n:Name, arg:Void</font>): <font color="BB6060">void</font>
    + visit(<font color="6060BB">n:NameExpr, arg:Void</font>): <font color="BB6060">void</font>
    + visit(<font color="6060BB">n:Nodelist, arg:Void</font>): <font color="BB6060">void</font>
    + visit(<font color="6060BB">n:NormalAnnotationExpr, arg:Void</font>): <font color="BB6060">void</font>
    + visit(<font color="6060BB">n:NullLiteralExpr, arg:Void</font>): <font color="BB6060">void</font>
    + visit(<font color="6060BB">n:ObjectCreationExpr, arg:Void</font>): <font color="BB6060">void</font>
    + visit(<font color="6060BB">n:PackageDeclaration, arg:Void</font>): <font color="BB6060">void</font>
    + visit(<font color="6060BB">n:Parameter, arg:Void</font>): <font color="BB6060">void</font>
    + visit(<font color="6060BB">n:PrimitiveType, arg:Void</font>): <font color="BB6060">void</font>
    + visit(<font color="6060BB">n:ReturnStmt, arg:Void</font>): <font color="BB6060">void</font>
    + visit(<font color="6060BB">n:SimpleName, arg:Void</font>): <font color="BB6060">void</font>
    + visit(<font color="6060BB">n:SingleMemberAnnotationExpr, arg:Void</font>): <font color="BB6060">void</font>
    + visit(<font color="6060BB">n:StringLiteralExpr, arg:Void</font>): <font color="BB6060">void</font>
    + visit(<font color="6060BB">n:SuperExpr, arg:Void</font>): <font color="BB6060">void</font>
    + visit(<font color="6060BB">n:SwitchEntry, arg:Void</font>): <font color="BB6060">void</font>
    + visit(<font color="6060BB">n:SwitchStmt, arg:Void</font>): <font color="BB6060">void</font>
    + visit(<font color="6060BB">n:SynchronizedStmt, arg:Void</font>): <font color="BB6060">void</font>
    + visit(<font color="6060BB">n:ThisExpr, arg:Void</font>): <font color="BB6060">void</font>
    + visit(<font color="6060BB">n:ThrowStmt, arg:Void</font>): <font color="BB6060">void</font>
    + visit(<font color="6060BB">n:TryStmt, arg:Void</font>): <font color="BB6060">void</font>
    + visit(<font color="6060BB">n:TypeExpr, arg:Void</font>): <font color="BB6060">void</font>
    + visit(<font color="6060BB">n:TypeParameter, arg:Void</font>): <font color="BB6060">void</font>
    + visit(<font color="6060BB">n:UnaryExpr, arg:Void</font>): <font color="BB6060">void</font>
    + visit(<font color="6060BB">n:UnionType, arg:Void</font>): <font color="BB6060">void</font>
    + visit(<font color="6060BB">n:UnknownType, arg:Void</font>): <font color="BB6060">void</font>
    + visit(<font color="6060BB">n:UnparsableStmt, arg:Void</font>): <font color="BB6060">void</font>
    + visit(<font color="6060BB">n:VariableDeclarationExpr, arg:Void</font>): <font color="BB6060">void</font>
    + visit(<font color="6060BB">n:VariableDeclarator, arg:Void</font>): <font color="BB6060">void</font>
    + visit(<font color="6060BB">n:VoidType, arg:Void</font>): <font color="BB6060">void</font>
    + visit(<font color="6060BB">n:WhileStmt, arg:Void</font>): <font color="BB6060">void</font>
    + visit(<font color="6060BB">n:WildcardType, arg:Void</font>): <font color="BB6060">void</font>
--
    + main(<font color="6060BB">args:String</font>): <font color="BB6060">void</font>
    - <font color="909090">main.cu: CompilationUnit</font>
    - <font color="909090">main.file: String</font>
--
  }
  class preadapter.domain.Datastructure_DOT_Method_DOT_ParameterType [[preadapter.domain.Datastructure_DOT_Method_DOT_ParameterType-diagram-detailed-grouped-per-namespace.svg]] #yellow {
  }
  class preadapter.domain.ASTVisitor_DOT_HandleDeepness [[preadapter.domain.ASTVisitor_DOT_HandleDeepness-diagram-detailed-grouped-per-namespace.svg]] #yellow {
  }
  class preadapter.domain.ASTVisitor [[preadapter.domain.ASTVisitor-diagram-detailed-grouped-per-namespace.svg]] #yellow {
    + logger: preadapter.Logger
    + datastructure: preadapter.domain.Datastructure
    + activeMethodList: list[String]
    + activeClassnameList: list[String]
    + namespaceList: list[String]
    + allUsing: list[String]
    + usingDict: dict[String,String]
    + deepness: HandleDeepness
    + ignoreType: list[String]
==
    + SimplifyType(<font color="6060BB">type:String</font>): <font color="BB6060">String</font>
--
    + cleanClassName(<font color="6060BB">className:String</font>): <font color="BB6060">String</font>
    - <font color="909090">cleanClassName.namespace: String</font>
    - <font color="909090">cleanClassName.namespaceLength: int</font>
--
    + CreateClassInterface(<font color="6060BB">node:ClassOrInterfaceDeclaration</font>): <font color="BB6060">String</font>
    - <font color="909090">CreateClassInterface.fqdnCurrentClassName: String</font>
    - <font color="909090">CreateClassInterface.fqdnParentClassName: String</font>
    - <font color="909090">CreateClassInterface.parentSubDataStructure: preadapter.domain.Datastructure_DOT_SubDataStructure</font>
    - <font color="909090">CreateClassInterface.subDataStructure: preadapter.domain.Datastructure_DOT_SubDataStructure</font>
    - <font color="909090">CreateClassInterface.fqdnCurrentClassNameFinal: String</font>
    - <font color="909090">CreateClassInterface.extendedTypeStr: String</font>
--
    - addArgumentType(<font color="6060BB">methodName:String, fqdnParentClassName:String, parameterType:Type, parameterName:String, argumentsTuple:list[tuple[String,String,String]]</font>): <font color="BB6060">void</font>
    - <font color="909090">addArgumentType.argumentTypeString: String</font>
    - <font color="909090">addArgumentType.mostProbableNS: String</font>
--
    + visit(<font color="6060BB">n:MethodDeclaration, arg:Void</font>): <font color="BB6060">void</font>
    - <font color="909090">visit.methodName: String</font>
    - <font color="909090">visit.fqdnParentClassName: String</font>
    - <font color="909090">visit.subDataStructure: preadapter.domain.Datastructure_DOT_SubDataStructure</font>
    - <font color="909090">visit.argument: Optional_DOT_empty</font>
    - <font color="909090">visit.className: String</font>
    - <font color="909090">visit.fqdnParentClassName: String</font>
    - <font color="909090">visit.subDataStructure: preadapter.domain.Datastructure_DOT_SubDataStructure</font>
    - <font color="909090">visit.argumentTypeString: String</font>
    - <font color="909090">visit.mostProbableNS: String</font>
    - <font color="909090">visit.variableDeclarator: VariableDeclarator</font>
    - <font color="909090">visit.importName: String</font>
    - <font color="909090">visit.enumValueName: String</font>
    - <font color="909090">visit.fqdnParentClassName: String</font>
    - <font color="909090">visit.subDataStructure: preadapter.domain.Datastructure_DOT_SubDataStructure</font>
    - <font color="909090">visit.fqdnCurrentClassName: String</font>
    - <font color="909090">visit.fqdnParentClassName: String</font>
    - <font color="909090">visit.subDataStructureParent: preadapter.domain.Datastructure_DOT_SubDataStructure</font>
    - <font color="909090">visit.subDataStructureChild: preadapter.domain.Datastructure_DOT_SubDataStructure</font>
    - <font color="909090">visit.fqdnParentClassName: String</font>
    - <font color="909090">visit.subDataStructureParent: preadapter.domain.Datastructure_DOT_SubDataStructure</font>
    - <font color="909090">visit.methodName: String</font>
    - <font color="909090">visit.method: preadapter.domain.Datastructure_DOT_Method</font>
--
    + visit(<font color="6060BB">n:ClassOrInterfaceDeclaration, arg:Void</font>): <font color="BB6060">void</font>
    + visit(<font color="6060BB">n:FieldDeclaration, arg:Void</font>): <font color="BB6060">void</font>
    + visit(<font color="6060BB">n:PackageDeclaration, arg:Void</font>): <font color="BB6060">void</font>
    + visit(<font color="6060BB">n:ImportDeclaration, arg:Void</font>): <font color="BB6060">void</font>
    + visit(<font color="6060BB">n:EnumConstantDeclaration, arg:Void</font>): <font color="BB6060">void</font>
    + visit(<font color="6060BB">n:EnumDeclaration, arg:Void</font>): <font color="BB6060">void</font>
    + visit(<font color="6060BB">n:VariableDeclarator, arg:Void</font>): <font color="BB6060">void</font>
--
    + main(<font color="6060BB">args:String</font>): <font color="BB6060">void</font>
    - <font color="909090">main.cu: CompilationUnit</font>
    - <font color="909090">main.file: String</font>
--
  }
  class preadapter.domain.ASTVisitor_DOT_ObjectType [[preadapter.domain.ASTVisitor_DOT_ObjectType-diagram-detailed-grouped-per-namespace.svg]] #yellow {
  }
  class preadapter.domain.Datastructure_DOT_Method_DOT_Variable [[preadapter.domain.Datastructure_DOT_Method_DOT_Variable-diagram-detailed-grouped-per-namespace.svg]] #yellow {
  }
'Compared namespace preadapter.domain [[preadapter.domain-diagram-detailed-grouped-per-namespace.svg]] { with last element of   }
' Closing all previous_sub_namespace_list namespace None because file analysis is finished.
' Closing namespace domain
}
' Closing namespace preadapter
}
namespace preadapter [[preadapter-diagram-detailed-grouped-per-namespace.svg]] {
namespace preadapter.infrastructure [[preadapter.infrastructure-diagram-detailed-grouped-per-namespace.svg]] {
  class preadapter.infrastructure.CreateYML [[preadapter.infrastructure.CreateYML-diagram-detailed-grouped-per-namespace.svg]] #yellow {
    + dummperOptions: DumperOptions.FlowStyle
    + startMark: Mark
    + endMark: Mark
==
    - appendTupleNodeValueSequenceNode(<font color="6060BB">mappingNode:dictpingNode, key:String, value:SequenceNode</font>): <font color="BB6060">boolean</font>
    - appendTupleNodeValueString(<font color="6060BB">mappingNode:dictpingNode, key:String, value:String</font>): <font color="BB6060">boolean</font>
    - appendTupleNodeValueStringToSequenceNode(<font color="6060BB">sequenceNode:SequenceNode, key:String, value:String</font>): <font color="BB6060">boolean</font>
--
    - appendSequence(<font color="6060BB">mappingNode:dictpingNode, list:list[String], nodeName:String</font>): <font color="BB6060">void</font>
    - <font color="909090">appendSequence.subSequenceNode: SequenceNode</font>
--
    + Create(<font color="6060BB">datastructure:preadapter.domain.Datastructure, toFile:String, logger:preadapter.Logger</font>): <font color="BB6060">void</font>
    - <font color="909090">Create.subDataStructure: preadapter.domain.Datastructure_DOT_SubDataStructure</font>
    - <font color="909090">Create.yaml: Yaml</font>
    - <font color="909090">Create.writer: PrintWriter</font>
--
  }
'Compared namespace preadapter.infrastructure [[preadapter.infrastructure-diagram-detailed-grouped-per-namespace.svg]] { with last element of   }
' Closing all previous_sub_namespace_list namespace None because file analysis is finished.
' Closing namespace infrastructure
}
' Closing namespace preadapter
}
namespace preadapter [[preadapter-diagram-detailed-grouped-per-namespace.svg]] {
namespace preadapter.service [[preadapter.service-diagram-detailed-grouped-per-namespace.svg]] {
  class preadapter.service.AnalyzeAST [[preadapter.service.AnalyzeAST-diagram-detailed-grouped-per-namespace.svg]] #yellow {
    + SearchRecurseCSharpToYAML(<font color="6060BB">fromDir:String, toDir:String, logger:preadapter.Logger</font>): <font color="BB6060">void</font>
    - <font color="909090">SearchRecurseCSharpToYAML.datastructure: preadapter.domain.Datastructure</font>
    - <font color="909090">SearchRecurseCSharpToYAML.listFilePaths: list[String]</font>
    - <font color="909090">SearchRecurseCSharpToYAML.cu: CompilationUnit</font>
    - <font color="909090">SearchRecurseCSharpToYAML.filePath: String</font>
    - <font color="909090">SearchRecurseCSharpToYAML.toFile: String</font>
--
  }
  class preadapter.service.RecursiveFileProcessor [[preadapter.service.RecursiveFileProcessor-diagram-detailed-grouped-per-namespace.svg]] #yellow {
    + SearchPath(<font color="6060BB">path:String</font>): <font color="BB6060">list[String]</font>
    - <font color="909090">SearchPath.fileList: list[String]</font>
--
    - ProcessDirectory(<font color="6060BB">sourceDirectory:String, fileList:list[String]</font>): <font color="BB6060">void</font>
    - <font color="909090">ProcessDirectory.stream: DirectoryStream[Path]</font>
    - <font color="909090">ProcessDirectory.isDirectory: boolean</font>
    - <font color="909090">ProcessDirectory.path: Path</font>
--
  }
'Compared namespace preadapter.service [[preadapter.service-diagram-detailed-grouped-per-namespace.svg]] { with last element of   }
' Closing all previous_sub_namespace_list namespace None because file analysis is finished.
' Closing namespace service
}
' Closing namespace preadapter
}
 ' *************************************** 
 ' *************************************** 
 ' *************************************** 
' Class relations extracted from namespace:
' 
' Class relations extracted from namespace:
' Examples.BadDesign
Examples.BadDesign.DB .[#6060BB].> Examples.BadDesign.FakeEntitities.User  : uses 
Examples.BadDesign.DB .[#6060BB].> Examples.BadDesign.FakeEntitities.Customer  : uses 
Examples.BadDesign.DB .[#6060BB].> Examples.BadDesign.FakeEntitities.Item  : uses 
Examples.BadDesign.DB .[#6060BB].> Examples.BadDesign.FakeEntitities.Invoice  : uses 
Examples.BadDesign.DB .[#6060BB].> Examples.BadDesign.FakeEntitities.Complaints  : uses 
Examples.BadDesign.DB .[#6060BB].> Examples.BadDesign.CarExample.Car  : uses 
Examples.BadDesign.DB .[#6060BB].> Examples.BadDesign.CarExample.CarParts.Driver  : uses 
Examples.BadDesign.DB .[#6060BB].> Examples.BadDesign.CarExample.CarParts.Wheels  : uses 
Examples.BadDesign.DB .[#6060BB].> Examples.BadDesign.CarExample.CarParts.Doors  : uses 
Examples.BadDesign.DB .[#6060BB].> Examples.BadDesign.CarExample.CarParts.Seats  : uses 
' Class relations extracted from namespace:
' Examples.BadDesign.BasicExample
Examples.BadDesign.BasicExample.IExample .[#6060BB].> Examples.BadDesign.BasicExample.Useless  : uses 
Examples.BadDesign.BasicExample.Useless *-[#10BB10]- Examples.BadDesign.DB 
Examples.BadDesign.BasicExample.Useless -[#909090]-> Examples.BadDesign.BasicExample.SideExample.SideTestEnum  : uses 
Examples.BadDesign.BasicExample.ClassExample_DOT_InnerClassExample +-[#10BBBB]- Examples.BadDesign.BasicExample.ClassExample_DOT_InnerClassExample_DOT_classInMethodExample 
Examples.BadDesign.BasicExample.BaseExample <|-[#red]- Examples.BadDesign.BasicExample.ClassExample
Examples.BadDesign.BasicExample.ClassExample +-[#10BBBB]- Examples.BadDesign.BasicExample.ClassExample_DOT_InnerClassExample 
Examples.BadDesign.BasicExample.ClassExample *-[#10BB10]- Examples.BadDesign.BasicExample.Useless 
Examples.BadDesign.BasicExample.ClassExample *-[#10BB10]- EnumTest 
Examples.BadDesign.BasicExample.ClassExample .[#6060BB].> Examples.BadDesign.BasicExample.Useless  : uses 
Examples.BadDesign.BasicExample.ClassExample -[#909090]-> Examples.BadDesign.BasicExample.BaseExample  : uses 
Examples.BadDesign.BasicExample.ClassExample .[#6060BB].> Examples.BadDesign.BasicExample.IExample  : uses 
Examples.BadDesign.BasicExample.AbstractBaseExample <|-[#red]- Examples.BadDesign.BasicExample.BaseExample
Examples.BadDesign.BasicExample.BaseExample +-[#10BBBB]- Examples.BadDesign.BasicExample.BaseExample_DOT_EnumTest 
Examples.BadDesign.BasicExample.BaseExample .[#6060BB].> Examples.BadDesign.BasicExample.Useless  : uses 
Examples.BadDesign.BasicExample.AbstractBaseExample .[#6060BB].> Examples.BadDesign.BasicExample.Useless  : uses 
' Class relations extracted from namespace:
' Examples.BadDesign.BasicExample.SideExample
Examples.BadDesign.BasicExample.SideExample.SideExample *-[#10BB10]- Examples.BadDesign.DB 
Examples.BadDesign.BasicExample.SideExample.SideExample .[#6060BB].> Examples.BadDesign.BasicExample.SideExample.SideTestEnum  : uses 
' Class relations extracted from namespace:
' Examples.BadDesign.CarExample
Examples.BadDesign.CarExample.Vehicle *-[#10BB10]- Examples.BadDesign.DB 
Examples.BadDesign.CarExample.CarParts.Driver <|-[#red]- Examples.BadDesign.CarExample.Car
Examples.BadDesign.CarExample.Car *-[#10BB10]- Examples.BadDesign.CarExample.CarParts.Wheels 
Examples.BadDesign.CarExample.Car *-[#10BB10]- Examples.BadDesign.CarExample.Vehicle 
Examples.BadDesign.CarExample.Car *-[#10BB10]- Examples.BadDesign.DB 
Examples.BadDesign.CarExample.Car .[#6060BB].> Examples.BadDesign.CarExample.CarParts.Doors  : uses 
Examples.BadDesign.CarExample.Car -[#909090]-> Examples.BadDesign.CarExample.CarParts.Seats  : uses 
' Class relations extracted from namespace:
' Examples.BadDesign.CarExample.CarParts
Examples.BadDesign.CarExample.CarParts.Driver *-[#10BB10]- Examples.BadDesign.DB 
Examples.BadDesign.CarExample.CarParts.Seats *-[#10BB10]- Examples.BadDesign.DB 
Examples.BadDesign.CarExample.CarParts.Wheels *-[#10BB10]- Examples.BadDesign.DB 
Examples.BadDesign.CarExample.CarParts.Doors *-[#10BB10]- Examples.BadDesign.DB 
' Class relations extracted from namespace:
' Examples.BadDesign.FakeEntitities
' Class relations extracted from namespace:
' Examples.BetterDesign
Examples.BetterDesign.DBCustomers .[#6060BB].> Examples.BetterDesign.FakeEntitities.Customer  : uses 
Examples.BetterDesign.DBCustomers .[#6060BB].> Examples.BetterDesign.FakeEntitities.Invoice  : uses 
Examples.BetterDesign.DBCustomers .[#6060BB].> Examples.BetterDesign.FakeEntitities.Item  : uses 
Examples.BetterDesign.DBCustomers .[#6060BB].> Examples.BetterDesign.FakeEntitities.Complaints  : uses 
Examples.BetterDesign.DBCustomers .[#6060BB].> Examples.BetterDesign.FakeEntitities.User  : uses 
Examples.BetterDesign.DBCar .[#6060BB].> Examples.BetterDesign.CarExample.CarParts.Driver  : uses 
Examples.BetterDesign.DBCar .[#6060BB].> Examples.BetterDesign.CarExample.Car  : uses 
Examples.BetterDesign.DBCar .[#6060BB].> Examples.BetterDesign.CarExample.CarParts.Seats  : uses 
Examples.BetterDesign.DBCar .[#6060BB].> Examples.BetterDesign.CarExample.CarParts.Doors  : uses 
Examples.BetterDesign.DBCar .[#6060BB].> Examples.BetterDesign.CarExample.CarParts.Wheels  : uses 
' Class relations extracted from namespace:
' Examples.BetterDesign.CarExample
Examples.BetterDesign.CarExample.Vehicle *-[#10BB10]- Examples.BetterDesign.DBCar 
.Vehicle <|-[#red]- Examples.BetterDesign.CarExample.Car
Examples.BetterDesign.CarExample.Car *-[#10BB10]- Examples.BetterDesign.CarExample.CarParts.Wheels 
Examples.BetterDesign.CarExample.Car *-[#10BB10]- Examples.BetterDesign.CarExample.CarParts.Seats 
Examples.BetterDesign.CarExample.Car *-[#10BB10]- Examples.BetterDesign.CarExample.CarParts.Driver 
Examples.BetterDesign.CarExample.Car *-[#10BB10]- Examples.BetterDesign.CarExample.CarParts.Doors 
Examples.BetterDesign.CarExample.Car .[#6060BB].> Examples.BetterDesign.CarExample.CarParts.Doors  : uses 
' Class relations extracted from namespace:
' Examples.BetterDesign.CarExample.CarParts
Examples.BetterDesign.CarExample.CarParts.Wheels *-[#10BB10]- Examples.BetterDesign.DBCar 
Examples.BetterDesign.CarExample.CarParts.Seats *-[#10BB10]- Examples.BetterDesign.DBCar 
Examples.BetterDesign.CarExample.CarParts.Driver *-[#10BB10]- Examples.BetterDesign.DBCar 
Examples.BetterDesign.CarExample.CarParts.Doors *-[#10BB10]- Examples.BetterDesign.DBCar 
' Class relations extracted from namespace:
' Examples.BetterDesign.FakeEntitities
' Class relations extracted from namespace:
' preadapter
preadapter.Logger *-[#10BB10]- preadapter.LoggingType 
preadapter.Revenger -[#909090]-> preadapter.Logger  : uses 
' Class relations extracted from namespace:
' preadapter.domain
preadapter.domain.Datastructure +-[#10BBBB]- preadapter.domain.Datastructure_DOT_Method 
preadapter.domain.Datastructure +-[#10BBBB]- preadapter.domain.Datastructure_DOT_Static 
preadapter.domain.Datastructure +-[#10BBBB]- preadapter.domain.Datastructure_DOT_Variable 
preadapter.domain.Datastructure +-[#10BBBB]- preadapter.domain.Datastructure_DOT_SubDataStructure 
preadapter.domain.Datastructure *-[#10BB10]- preadapter.Logger 
preadapter.domain.Datastructure -[#909090]-> Variable  : uses 
preadapter.domain.Datastructure -[#909090]-> Method  : uses 
preadapter.domain.Datastructure -[#909090]-> SubDataStructure  : uses 
preadapter.domain.Datastructure .[#6060BB].> SubDataStructure  : uses 
preadapter.domain.Datastructure_DOT_Method +-[#10BBBB]- preadapter.domain.Datastructure_DOT_Method_DOT_ParameterType 
preadapter.domain.Datastructure_DOT_Method +-[#10BBBB]- preadapter.domain.Datastructure_DOT_Method_DOT_Variable 
VoidVisitorAdapter_BRQTO_Void_BRQTC <|-[#red]- preadapter.domain.ASTVisitorDebug
preadapter.domain.ASTVisitorDebug +-[#10BBBB]- preadapter.domain.ASTVisitorDebug_DOT_HandleDeepness 
preadapter.domain.ASTVisitorDebug *-[#10BB10]- PrintStream 
preadapter.domain.ASTVisitorDebug *-[#10BB10]- HandleDeepness 
preadapter.domain.ASTVisitorDebug .[#6060BB].> AnnotationDeclaration  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> Void  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> AnnotationMemberDeclaration  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> ArrayAccessExpr  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> ArrayCreationExpr  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> ArrayCreationLevel  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> ArrayInitializerExpr  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> ArrayType  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> AssertStmt  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> AssignExpr  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> BinaryExpr  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> BlockComment  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> BlockStmt  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> BooleanLiteralExpr  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> BreakStmt  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> CastExpr  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> CatchClause  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> CharLiteralExpr  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> ClassExpr  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> ClassOrInterfaceDeclaration  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> ClassOrInterfaceType  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> CompilationUnit  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> ConditionalExpr  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> ConstructorDeclaration  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> ContinueStmt  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> DoStmt  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> DoubleLiteralExpr  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> EmptyStmt  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> EnclosedExpr  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> EnumConstantDeclaration  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> EnumDeclaration  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> ExplicitConstructorInvocationStmt  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> ExpressionStmt  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> FieldAccessExpr  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> FieldDeclaration  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> ForEachStmt  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> ForStmt  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> IfStmt  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> ImportDeclaration  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> InitializerDeclaration  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> InstanceOfExpr  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> IntegerLiteralExpr  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> IntersectionType  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> JavadocComment  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> LabeledStmt  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> LambdaExpr  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> LineComment  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> LocalClassDeclarationStmt  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> LongLiteralExpr  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> MarkerAnnotationExpr  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> MemberValuetuple  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> MethodCallExpr  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> MethodDeclaration  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> MethodReferenceExpr  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> ModuleDeclaration  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> ModuleExportsDirective  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> ModuleOpensDirective  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> ModuleProvidesDirective  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> ModuleRequiresDirective  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> ModuleUsesDirective  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> Name  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> NameExpr  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> Nodelist  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> NormalAnnotationExpr  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> NullLiteralExpr  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> ObjectCreationExpr  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> PackageDeclaration  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> Parameter  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> PrimitiveType  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> ReturnStmt  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> SimpleName  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> SingleMemberAnnotationExpr  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> StringLiteralExpr  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> SuperExpr  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> SwitchEntry  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> SwitchStmt  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> SynchronizedStmt  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> ThisExpr  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> ThrowStmt  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> TryStmt  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> TypeExpr  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> TypeParameter  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> UnaryExpr  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> UnionType  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> UnknownType  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> UnparsableStmt  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> VariableDeclarationExpr  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> VariableDeclarator  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> VoidType  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> WhileStmt  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> WildcardType  : uses 
preadapter.domain.ASTVisitorDebug -[#909090]-> CompilationUnit  : uses 
VoidVisitorAdapter_BRQTO_Void_BRQTC <|-[#red]- preadapter.domain.ASTVisitor
preadapter.domain.ASTVisitor +-[#10BBBB]- preadapter.domain.ASTVisitor_DOT_ObjectType 
preadapter.domain.ASTVisitor +-[#10BBBB]- preadapter.domain.ASTVisitor_DOT_HandleDeepness 
preadapter.domain.ASTVisitor *-[#10BB10]- preadapter.Logger 
preadapter.domain.ASTVisitor *-[#10BB10]- preadapter.domain.Datastructure 
preadapter.domain.ASTVisitor *-[#10BB10]- HandleDeepness 
preadapter.domain.ASTVisitor .[#6060BB].> ClassOrInterfaceDeclaration  : uses 
preadapter.domain.ASTVisitor -[#909090]-> preadapter.domain.Datastructure_DOT_SubDataStructure  : uses 
preadapter.domain.ASTVisitor .[#6060BB].> Type  : uses 
preadapter.domain.ASTVisitor .[#6060BB].> MethodDeclaration  : uses 
preadapter.domain.ASTVisitor .[#6060BB].> Void  : uses 
preadapter.domain.ASTVisitor -[#909090]-> Optional_DOT_empty  : uses 
preadapter.domain.ASTVisitor -[#909090]-> VariableDeclarator  : uses 
preadapter.domain.ASTVisitor -[#909090]-> preadapter.domain.Datastructure_DOT_Method  : uses 
preadapter.domain.ASTVisitor .[#6060BB].> FieldDeclaration  : uses 
preadapter.domain.ASTVisitor .[#6060BB].> PackageDeclaration  : uses 
preadapter.domain.ASTVisitor .[#6060BB].> ImportDeclaration  : uses 
preadapter.domain.ASTVisitor .[#6060BB].> EnumConstantDeclaration  : uses 
preadapter.domain.ASTVisitor .[#6060BB].> EnumDeclaration  : uses 
preadapter.domain.ASTVisitor .[#6060BB].> VariableDeclarator  : uses 
preadapter.domain.ASTVisitor -[#909090]-> CompilationUnit  : uses 
' Class relations extracted from namespace:
' preadapter.infrastructure
preadapter.infrastructure.CreateYML *-[#10BB10]- DumperOptions.FlowStyle 
preadapter.infrastructure.CreateYML *-[#10BB10]- Mark 
preadapter.infrastructure.CreateYML .[#6060BB].> dictpingNode  : uses 
preadapter.infrastructure.CreateYML .[#6060BB].> SequenceNode  : uses 
preadapter.infrastructure.CreateYML -[#909090]-> SequenceNode  : uses 
preadapter.infrastructure.CreateYML .[#6060BB].> preadapter.domain.Datastructure  : uses 
preadapter.infrastructure.CreateYML .[#6060BB].> preadapter.Logger  : uses 
preadapter.infrastructure.CreateYML -[#909090]-> preadapter.domain.Datastructure_DOT_SubDataStructure  : uses 
preadapter.infrastructure.CreateYML -[#909090]-> Yaml  : uses 
preadapter.infrastructure.CreateYML -[#909090]-> PrintWriter  : uses 
' Class relations extracted from namespace:
' preadapter.service
preadapter.service.AnalyzeAST .[#6060BB].> preadapter.Logger  : uses 
preadapter.service.AnalyzeAST -[#909090]-> preadapter.domain.Datastructure  : uses 
preadapter.service.AnalyzeAST -[#909090]-> CompilationUnit  : uses 
preadapter.service.RecursiveFileProcessor -[#909090]-> Path  : uses 
@enduml