@startuml
title <size:20>AnalyzeAST_BRQTO__BRQTC **detailed** </size>
note "Your are analyzing:\nAnalyzeAST_BRQTO__BRQTC **detailed** \n\n==Filter==\nYou can click either the namespaces \nor class names for filtering them and their\ndirect dependencies.\n\n==Select other==\n* AnalyzeAST_BRQTO__BRQTC **simplified** :\n   [[AnalyzeAST_BRQTO__BRQTC-diagram-simplified.svg]]\n* Full diagram **detailed** and **grouped per namespace**:\n   [[full-diagram-detailed-grouped-per-namespace.svg]]\n* Home:\n   [[index.html]]" as FloatingNote
class AnalyzeAST_BRQTO__BRQTC [[AnalyzeAST_BRQTO__BRQTC-diagram-detailed.svg]] #yellow {
}
class preadapter.Revenger [[preadapter.Revenger-diagram-detailed.svg]]  {
  + main(<font color="6060BB">main:String_BRQTO__BRQTC</font>)
  - <font color="909090">main.logger: preadapter.Logger</font>
  - <font color="909090">main.ast: AnalyzeAST_BRQTO__BRQTC</font>
--
}
 ' *************************************** 
 ' *************************************** 
 ' *************************************** 
' Class relations extracted from namespace:
' 
' Class relations extracted from namespace:
' preadapter
preadapter.Revenger -[#909090]-> AnalyzeAST_BRQTO__BRQTC  : uses 
@enduml