@startuml
skinparam linetype ortho
title <size:20>DumperOptions.FlowStyle **simplified** </size>
note "Your are analyzing:\nDumperOptions.FlowStyle **simplified** \n\n==Filter==\nYou can click either the namespaces \nor class names for filtering them and their\ndirect dependencies.\n\n==Select other==\n* DumperOptions.FlowStyle **detailed** :\n   [[DumperOptions.FlowStyle-diagram-detailed.svg]]\n* Full diagram **simplified** and **grouped per namespace**:\n   [[full-diagram-simplified-grouped-per-namespace.svg]]\n* Home:\n   [[index.html]]" as FloatingNote
class DumperOptions.FlowStyle [[DumperOptions.FlowStyle-diagram-simplified.svg]] #yellow {
}
  class preadapter.infrastructure.CreateYML [[preadapter.infrastructure.CreateYML-diagram-simplified.svg]]  {
  }
 ' *************************************** 
 ' *************************************** 
 ' *************************************** 
' Class relations extracted from namespace:
' 
' Class relations extracted from namespace:
' preadapter.infrastructure
preadapter.infrastructure.CreateYML *-[#10BB10]- DumperOptions.FlowStyle 
@enduml