@startuml
title <size:20>EnumTypePlaceHolder **detailed** </size>
note "Your are analyzing:\nEnumTypePlaceHolder **detailed** \n\n==Filter==\nYou can click either the namespaces \nor class names for filtering them and their\ndirect dependencies.\n\n==Select other==\n* EnumTypePlaceHolder **simplified** :\n   [[EnumTypePlaceHolder-diagram-simplified.svg]]\n* Full diagram **detailed** and **grouped per namespace**:\n   [[full-diagram-detailed-grouped-per-namespace.svg]]\n* Home:\n   [[index.html]]" as FloatingNote
class EnumTypePlaceHolder [[EnumTypePlaceHolder-diagram-detailed.svg]] #yellow {
}
  class Example.SideExample.SideTestEnum [[Example.SideExample.SideTestEnum-diagram-detailed.svg]]  {
    + TestEnumValue1: EnumTypePlaceHolder
    + TestEnumValue2: EnumTypePlaceHolder
==
  }
class preadapter.LoggingType [[preadapter.LoggingType-diagram-detailed.svg]]  {
  + TRACE: EnumTypePlaceHolder
  + DEBUG: EnumTypePlaceHolder
  + INFO: EnumTypePlaceHolder
  + WARNING: EnumTypePlaceHolder
  + ERROR: EnumTypePlaceHolder
==
  + getValue(<font color="6060BB"></font>)
}
 ' *************************************** 
 ' *************************************** 
 ' *************************************** 
' Class relations extracted from namespace:
' 
' Class relations extracted from namespace:
' Example.SideExample
Example.SideExample.SideTestEnum .[#6060BB].> EnumTypePlaceHolder  : uses 
' Class relations extracted from namespace:
' preadapter
preadapter.LoggingType .[#6060BB].> EnumTypePlaceHolder  : uses 
@enduml