@startuml
title <size:20>Example.IExample **detailed** </size>
note "Your are analyzing:\nExample.IExample **detailed** \n\n==Filter==\nYou can click either the namespaces \nor class names for filtering them and their\ndirect dependencies.\n\n==Select other==\n* Example.IExample **simplified** :\n   [[Example.IExample-diagram-simplified.svg]]\n* Full diagram **detailed** and **grouped per namespace**:\n   [[full-diagram-detailed-grouped-per-namespace.svg]]\n* Home:\n   [[index.html]]" as FloatingNote
interface Example.IExample [[Example.IExample-diagram-detailed.svg]] #yellow {
  + example(<font color="6060BB">example:Example.Useless, example:Example.Useless</font>)
}
class Example.Useless [[Example.Useless-diagram-detailed.svg]]  {
  + useless(<font color="6060BB"></font>)
  - <font color="909090">useless.testEnum: Example.SideExample.SideTestEnum</font>
--
}
 ' *************************************** 
 ' *************************************** 
 ' *************************************** 
' Class relations extracted from namespace:
' Example
Example.IExample .[#6060BB].> Example.Useless  : uses 
@enduml