@startuml
title <size:20>Example.ClassExample **simplified** and **grouped per namespace**</size>
note "Your are analyzing:\nExample.ClassExample **simplified** and **grouped per namespace**\n\n==Filter==\nYou can click either the namespaces \nor class names for filtering them and their\ndirect dependencies.\n\n==Select other==\n* Example.ClassExample **detailed** and **grouped per namespace**:\n   [[Example.ClassExample-diagram-detailed-grouped-per-namespace.svg]]\n* Full diagram **simplified** and **grouped per namespace**:\n   [[full-diagram-simplified-grouped-per-namespace.svg]]\n* Home:\n   [[index.html]]" as FloatingNote
class EnumTest [[EnumTest-diagram-simplified-grouped-per-namespace.svg]] #MintCream {
}
' Closing all previous_sub_namespace_list namespace None because file analysis is finished.
namespace Example [[Example-diagram-simplified-grouped-per-namespace.svg]] {
class Example.ClassExample [[Example.ClassExample-diagram-simplified-grouped-per-namespace.svg]] #yellow {
}
class Example.BaseExample [[Example.BaseExample-diagram-simplified-grouped-per-namespace.svg]]  {
}
class Example.Useless [[Example.Useless-diagram-simplified-grouped-per-namespace.svg]]  {
}
class Example.ClassExample_DOT_InnerClassExample [[Example.ClassExample_DOT_InnerClassExample-diagram-simplified-grouped-per-namespace.svg]]  {
}
'Compared namespace Example [[Example-diagram-simplified-grouped-per-namespace.svg]] { with last element of }
' Closing all previous_sub_namespace_list namespace None because file analysis is finished.
' Closing namespace Example
}
 ' *************************************** 
 ' *************************************** 
 ' *************************************** 
' Class relations extracted from namespace:
' 
' Class relations extracted from namespace:
' Example
Example.BaseExample <|-[#red]- Example.ClassExample
Example.ClassExample +-[#10BBBB]- Example.ClassExample_DOT_InnerClassExample 
Example.ClassExample .[#6060BB].> Example.Useless  : uses 
Example.ClassExample .[#6060BB].> EnumTest  : uses 
Example.ClassExample -[#909090]-> Example.BaseExample  : uses 
Example.BaseExample .[#6060BB].> Example.Useless  : uses 
@enduml