@startuml
title <size:20>Example.ClassExample_DOT_InnerClassExample_DOT_classInMethodExample **simplified** </size>
note "Your are analyzing:\nExample.ClassExample_DOT_InnerClassExample_DOT_classInMethodExample **simplified** \n\n==Filter==\nYou can click either the namespaces \nor class names for filtering them and their\ndirect dependencies.\n\n==Select other==\n* Example.ClassExample_DOT_InnerClassExample_DOT_classInMethodExample **detailed** :\n   [[Example.ClassExample_DOT_InnerClassExample_DOT_classInMethodExample-diagram-detailed.svg]]\n* Full diagram **simplified** and **grouped per namespace**:\n   [[full-diagram-simplified-grouped-per-namespace.svg]]\n* Home:\n   [[index.html]]" as FloatingNote
class Example.ClassExample_DOT_InnerClassExample_DOT_classInMethodExample [[Example.ClassExample_DOT_InnerClassExample_DOT_classInMethodExample-diagram-simplified.svg]] #yellow {
}
class Example.ClassExample_DOT_InnerClassExample [[Example.ClassExample_DOT_InnerClassExample-diagram-simplified.svg]]  {
}
 ' *************************************** 
 ' *************************************** 
 ' *************************************** 
' Class relations extracted from namespace:
' Example
Example.ClassExample_DOT_InnerClassExample +-[#10BBBB]- Example.ClassExample_DOT_InnerClassExample_DOT_classInMethodExample 
@enduml