@startuml
skinparam linetype ortho
title <size:20>Examples.BetterDesign.Repository.CarExample.CarParts.Driver **detailed** and **grouped per namespace**</size>
note "Your are analyzing:\nExamples.BetterDesign.Repository.CarExample.CarParts.Driver **detailed** and **grouped per namespace**\n\n==Filter==\nYou can click either the namespaces \nor class names for filtering them and their\ndirect dependencies.\n\n==Select other==\n* Examples.BetterDesign.Repository.CarExample.CarParts.Driver **simplified** and **grouped per namespace**:\n   [[Examples.BetterDesign.Repository.CarExample.CarParts.Driver-diagram-simplified-grouped-per-namespace.svg]]\n* Full diagram **detailed** and **grouped per namespace**:\n   [[full-diagram-detailed-grouped-per-namespace.svg]]\n* Home:\n   [[index.html]]" as FloatingNote
namespace Examples [[Examples-diagram-detailed-grouped-per-namespace.svg]] {
namespace Examples.BetterDesign [[Examples.BetterDesign-diagram-detailed-grouped-per-namespace.svg]] {
namespace Examples.BetterDesign.Repository [[Examples.BetterDesign.Repository-diagram-detailed-grouped-per-namespace.svg]] {
    class Examples.BetterDesign.Repository.DBCar [[Examples.BetterDesign.Repository.DBCar-diagram-detailed-grouped-per-namespace.svg]]  {
      + getCarsForDriver(<font color="6060BB">driver:Examples.BetterDesign.Repository.CarExample.CarParts.Driver</font>): <font color="BB6060">String</font>
      + updateCar(<font color="6060BB">car:Examples.BetterDesign.Repository.CarExample.Car, seats:Examples.BetterDesign.Repository.CarExample.CarParts.Seats</font>): <font color="BB6060">void</font>
      + updateCar(<font color="6060BB">car:Examples.BetterDesign.Repository.CarExample.Car, doors:Examples.BetterDesign.Repository.CarExample.CarParts.Doors</font>): <font color="BB6060">void</font>
      + sellCarTo(<font color="6060BB">car:Examples.BetterDesign.Repository.CarExample.Car, driver:Examples.BetterDesign.Repository.CarExample.CarParts.Driver</font>): <font color="BB6060">void</font>
      + getCar(<font color="6060BB">d:Examples.BetterDesign.Repository.CarExample.CarParts.Driver</font>): <font color="BB6060">Examples.BetterDesign.Repository.CarExample.Car</font>
      + getDriver(<font color="6060BB">c:Examples.BetterDesign.Repository.CarExample.Car</font>): <font color="BB6060">Examples.BetterDesign.Repository.CarExample.CarParts.Driver</font>
      + getWheels(<font color="6060BB">c:Examples.BetterDesign.Repository.CarExample.Car</font>): <font color="BB6060">Examples.BetterDesign.Repository.CarExample.CarParts.Wheels</font>
      + getDoors(<font color="6060BB">c:Examples.BetterDesign.Repository.CarExample.Car</font>): <font color="BB6060">Examples.BetterDesign.Repository.CarExample.CarParts.Doors</font>
      + getSeats(<font color="6060BB">c:Examples.BetterDesign.Repository.CarExample.Car</font>): <font color="BB6060">Examples.BetterDesign.Repository.CarExample.CarParts.Seats</font>
    }
'Compared namespace Examples.BetterDesign.Repository [[Examples.BetterDesign.Repository-diagram-detailed-grouped-per-namespace.svg]] { with last element of     }
' Closing all previous_sub_namespace_list namespace None because file analysis is finished.
' Closing namespace Repository
}
' Closing namespace BetterDesign
}
' Closing namespace Examples
}
namespace Examples [[Examples-diagram-detailed-grouped-per-namespace.svg]] {
namespace Examples.BetterDesign [[Examples.BetterDesign-diagram-detailed-grouped-per-namespace.svg]] {
namespace Examples.BetterDesign.Repository [[Examples.BetterDesign.Repository-diagram-detailed-grouped-per-namespace.svg]] {
namespace Examples.BetterDesign.Repository.CarExample [[Examples.BetterDesign.Repository.CarExample-diagram-detailed-grouped-per-namespace.svg]] {
      class Examples.BetterDesign.Repository.CarExample.Car [[Examples.BetterDesign.Repository.CarExample.Car-diagram-detailed-grouped-per-namespace.svg]]  {
        + wheels: Examples.BetterDesign.Repository.CarExample.CarParts.Wheels
        + seats: Examples.BetterDesign.Repository.CarExample.CarParts.Seats
        + driver: Examples.BetterDesign.Repository.CarExample.CarParts.Driver
        + doors: Examples.BetterDesign.Repository.CarExample.CarParts.Doors
==
        + createCar(<font color="6060BB">doors:Examples.BetterDesign.Repository.CarExample.CarParts.Doors</font>): <font color="BB6060">void</font>
      }
'Compared namespace Examples.BetterDesign.Repository.CarExample [[Examples.BetterDesign.Repository.CarExample-diagram-detailed-grouped-per-namespace.svg]] { with last element of       }
' Closing all previous_sub_namespace_list namespace None because file analysis is finished.
' Closing namespace CarExample
}
' Closing namespace Repository
}
' Closing namespace BetterDesign
}
' Closing namespace Examples
}
namespace Examples [[Examples-diagram-detailed-grouped-per-namespace.svg]] {
namespace Examples.BetterDesign [[Examples.BetterDesign-diagram-detailed-grouped-per-namespace.svg]] {
namespace Examples.BetterDesign.Repository [[Examples.BetterDesign.Repository-diagram-detailed-grouped-per-namespace.svg]] {
namespace Examples.BetterDesign.Repository.CarExample [[Examples.BetterDesign.Repository.CarExample-diagram-detailed-grouped-per-namespace.svg]] {
namespace Examples.BetterDesign.Repository.CarExample.CarParts [[Examples.BetterDesign.Repository.CarExample.CarParts-diagram-detailed-grouped-per-namespace.svg]] {
        class Examples.BetterDesign.Repository.CarExample.CarParts.Driver [[Examples.BetterDesign.Repository.CarExample.CarParts.Driver-diagram-detailed-grouped-per-namespace.svg]] #yellow {
          + db: Examples.BetterDesign.Repository.DBCar
==
          + getWeight(<font color="6060BB"></font>): <font color="BB6060">int</font>
        }
'Compared namespace Examples.BetterDesign.Repository.CarExample.CarParts [[Examples.BetterDesign.Repository.CarExample.CarParts-diagram-detailed-grouped-per-namespace.svg]] { with last element of         }
' Closing all previous_sub_namespace_list namespace None because file analysis is finished.
' Closing namespace CarParts
}
' Closing namespace CarExample
}
' Closing namespace Repository
}
' Closing namespace BetterDesign
}
' Closing namespace Examples
}
 ' *************************************** 
 ' *************************************** 
 ' *************************************** 
' Class relations extracted from namespace:
' Examples.BetterDesign.Repository
Examples.BetterDesign.Repository.DBCar .[#6060BB].> Examples.BetterDesign.Repository.CarExample.CarParts.Driver  : uses 
Examples.BetterDesign.Repository.DBCar .[#6060BB].> Examples.BetterDesign.Repository.CarExample.Car  : uses 
' Class relations extracted from namespace:
' Examples.BetterDesign.Repository.CarExample
Examples.BetterDesign.Repository.CarExample.Car *-[#10BB10]- Examples.BetterDesign.Repository.CarExample.CarParts.Driver 
' Class relations extracted from namespace:
' Examples.BetterDesign.Repository.CarExample.CarParts
Examples.BetterDesign.Repository.CarExample.CarParts.Driver *-[#10BB10]- Examples.BetterDesign.Repository.DBCar 
@enduml