@startuml
skinparam linetype ortho
title <size:20>Examples.BadDesign.CarExample.CarParts_DOT_Driver **detailed** </size>
note "Your are analyzing:\nExamples.BadDesign.CarExample.CarParts_DOT_Driver **detailed** \n\n==Filter==\nYou can click either the namespaces \nor class names for filtering them and their\ndirect dependencies.\n\n==Select other==\n* Examples.BadDesign.CarExample.CarParts_DOT_Driver **simplified** :\n   [[Examples.BadDesign.CarExample.CarParts_DOT_Driver-diagram-simplified.svg]]\n* Full diagram **detailed** and **grouped per namespace**:\n   [[full-diagram-detailed-grouped-per-namespace.svg]]\n* Home:\n   [[index.html]]" as FloatingNote
class Examples.BadDesign.CarExample.CarParts_DOT_Driver [[Examples.BadDesign.CarExample.CarParts_DOT_Driver-diagram-detailed.svg]] #yellow {
}
    class Examples.BadDesign.CarExample.Car [[Examples.BadDesign.CarExample.Car-diagram-detailed.svg]]  {
      + wheels: Examples.BadDesign.CarExample.CarParts.Wheels
      + vehicle: Examples.BadDesign.CarExample.Vehicle
      + db: Examples.BadDesign.DB
==
      + createCar(<font color="6060BB">doors:Examples.BadDesign.CarExample.CarParts.Doors</font>): <font color="BB6060">void</font>
      - <font color="909090">createCar.seats: Examples.BadDesign.CarExample.CarParts.Seats</font>
--
    }
 ' *************************************** 
 ' *************************************** 
 ' *************************************** 
' Class relations extracted from namespace:
' 
' Class relations extracted from namespace:
' Examples.BadDesign.CarExample
Examples.BadDesign.CarExample.CarParts_DOT_Driver <|-[#red]- Examples.BadDesign.CarExample.Car
@enduml