@startuml
skinparam linetype ortho
title <size:20>Examples.BadDesign.BasicExample.IExample **simplified** </size>
note "Your are analyzing:\nExamples.BadDesign.BasicExample.IExample **simplified** \n\n==Filter==\nYou can click either the namespaces \nor class names for filtering them and their\ndirect dependencies.\n\n==Select other==\n* Examples.BadDesign.BasicExample.IExample **detailed** :\n   [[Examples.BadDesign.BasicExample.IExample-diagram-detailed.svg]]\n* Full diagram **simplified** and **grouped per namespace**:\n   [[full-diagram-simplified-grouped-per-namespace.svg]]\n* Home:\n   [[index.html]]" as FloatingNote
    interface Examples.BadDesign.BasicExample.IExample [[Examples.BadDesign.BasicExample.IExample-diagram-simplified.svg]] #yellow {
    }
    class Examples.BadDesign.BasicExample.Useless [[Examples.BadDesign.BasicExample.Useless-diagram-simplified.svg]]  {
    }
    class Examples.BadDesign.BasicExample.ClassExample [[Examples.BadDesign.BasicExample.ClassExample-diagram-simplified.svg]]  {
    }
 ' *************************************** 
 ' *************************************** 
 ' *************************************** 
' Class relations extracted from namespace:
' Examples.BadDesign.BasicExample
Examples.BadDesign.BasicExample.IExample .[#6060BB].> Examples.BadDesign.BasicExample.Useless  : uses 
Examples.BadDesign.BasicExample.ClassExample *-[#10BB10]- Examples.BadDesign.BasicExample.Useless 
Examples.BadDesign.BasicExample.ClassExample .[#6060BB].> Examples.BadDesign.BasicExample.Useless  : uses 
Examples.BadDesign.BasicExample.ClassExample .[#6060BB].> Examples.BadDesign.BasicExample.IExample  : uses 
@enduml