@startuml
title <size:20>Example.SideExample.SideExample **simplified** </size>
note "Your are analyzing:\nExample.SideExample.SideExample **simplified** \n\n==Filter==\nYou can click either the namespaces \nor class names for filtering them and their\ndirect dependencies.\n\n==Select other==\n* Example.SideExample.SideExample **detailed** :\n   [[Example.SideExample.SideExample-diagram-detailed.svg]]\n* Full diagram **simplified** and **grouped per namespace**:\n   [[full-diagram-simplified-grouped-per-namespace.svg]]\n* Home:\n   [[index.html]]" as FloatingNote
  class Example.SideExample.SideExample [[Example.SideExample.SideExample-diagram-simplified.svg]] #yellow {
  }
  class Example.SideExample.SideTestEnum [[Example.SideExample.SideTestEnum-diagram-simplified.svg]]  {
  }
 ' *************************************** 
 ' *************************************** 
 ' *************************************** 
' Class relations extracted from namespace:
' Example.SideExample
Example.SideExample.SideExample .[#6060BB].> Example.SideExample.SideTestEnum  : uses 
@enduml