@startuml
skinparam linetype ortho
title <size:20>Examples.BetterDesign.CarExample.Car **detailed** </size>
note "Your are analyzing:\nExamples.BetterDesign.CarExample.Car **detailed** \n\n==Filter==\nYou can click either the namespaces \nor class names for filtering them and their\ndirect dependencies.\n\n==Select other==\n* Examples.BetterDesign.CarExample.Car **simplified** :\n   [[Examples.BetterDesign.CarExample.Car-diagram-simplified.svg]]\n* Full diagram **detailed** and **grouped per namespace**:\n   [[full-diagram-detailed-grouped-per-namespace.svg]]\n* Home:\n   [[index.html]]" as FloatingNote
  class Examples.BetterDesign.DBCar [[Examples.BetterDesign.DBCar-diagram-detailed.svg]]  {
    + getCarsForDriver(<font color="6060BB">driver:Examples.BetterDesign.CarExample.CarParts.Driver</font>): <font color="BB6060">String</font>
    + updateCar(<font color="6060BB">car:Examples.BetterDesign.CarExample.Car, seats:Examples.BetterDesign.CarExample.CarParts.Seats</font>): <font color="BB6060">void</font>
    + updateCar(<font color="6060BB">car:Examples.BetterDesign.CarExample.Car, doors:Examples.BetterDesign.CarExample.CarParts.Doors</font>): <font color="BB6060">void</font>
    + sellCarTo(<font color="6060BB">car:Examples.BetterDesign.CarExample.Car, driver:Examples.BetterDesign.CarExample.CarParts.Driver</font>): <font color="BB6060">void</font>
    + getCarFromDriver(<font color="6060BB">d:Examples.BetterDesign.CarExample.CarParts.Driver</font>): <font color="BB6060">Examples.BetterDesign.CarExample.Car</font>
    + getDriverFromCar(<font color="6060BB">c:Examples.BetterDesign.CarExample.Car</font>): <font color="BB6060">Examples.BetterDesign.CarExample.CarParts.Driver</font>
    + getWheelsFromCar(<font color="6060BB">c:Examples.BetterDesign.CarExample.Car</font>): <font color="BB6060">Examples.BetterDesign.CarExample.CarParts.Wheels</font>
    + getDoorsFromCar(<font color="6060BB">c:Examples.BetterDesign.CarExample.Car</font>): <font color="BB6060">Examples.BetterDesign.CarExample.CarParts.Doors</font>
    + getSeatsFromCar(<font color="6060BB">c:Examples.BetterDesign.CarExample.Car</font>): <font color="BB6060">Examples.BetterDesign.CarExample.CarParts.Seats</font>
  }
    class Examples.BetterDesign.CarExample.Car [[Examples.BetterDesign.CarExample.Car-diagram-detailed.svg]] #yellow {
      + wheels: Examples.BetterDesign.CarExample.CarParts.Wheels
      + seats: Examples.BetterDesign.CarExample.CarParts.Seats
      + driver: Examples.BetterDesign.CarExample.CarParts.Driver
      + doors: Examples.BetterDesign.CarExample.CarParts.Doors
==
      + createCar(<font color="6060BB">doors:Examples.BetterDesign.CarExample.CarParts.Doors</font>): <font color="BB6060">void</font>
    }
    class Examples.BetterDesign.CarExample.Vehicle [[Examples.BetterDesign.CarExample.Vehicle-diagram-detailed.svg]]  {
      + db: Examples.BetterDesign.DBCar
==
      + setSpeed(<font color="6060BB">speed:int</font>): <font color="BB6060">void</font>
      + getSpeed(<font color="6060BB"></font>): <font color="BB6060">int</font>
    }
      class Examples.BetterDesign.CarExample.CarParts.Wheels [[Examples.BetterDesign.CarExample.CarParts.Wheels-diagram-detailed.svg]]  {
        + db: Examples.BetterDesign.DBCar
==
        + getWeight(<font color="6060BB"></font>): <font color="BB6060">int</font>
      }
      class Examples.BetterDesign.CarExample.CarParts.Seats [[Examples.BetterDesign.CarExample.CarParts.Seats-diagram-detailed.svg]]  {
        + db: Examples.BetterDesign.DBCar
==
        + getWeight(<font color="6060BB"></font>): <font color="BB6060">int</font>
      }
      class Examples.BetterDesign.CarExample.CarParts.Driver [[Examples.BetterDesign.CarExample.CarParts.Driver-diagram-detailed.svg]]  {
        + db: Examples.BetterDesign.DBCar
==
        + getWeight(<font color="6060BB"></font>): <font color="BB6060">int</font>
      }
      class Examples.BetterDesign.CarExample.CarParts.Doors [[Examples.BetterDesign.CarExample.CarParts.Doors-diagram-detailed.svg]]  {
        + db: Examples.BetterDesign.DBCar
==
        + getWeight(<font color="6060BB"></font>): <font color="BB6060">int</font>
      }
 ' *************************************** 
 ' *************************************** 
 ' *************************************** 
' Class relations extracted from namespace:
' Examples.BetterDesign
Examples.BetterDesign.DBCar .[#6060BB].> Examples.BetterDesign.CarExample.CarParts.Driver  : uses 
Examples.BetterDesign.DBCar .[#6060BB].> Examples.BetterDesign.CarExample.Car  : uses 
Examples.BetterDesign.DBCar .[#6060BB].> Examples.BetterDesign.CarExample.CarParts.Seats  : uses 
Examples.BetterDesign.DBCar .[#6060BB].> Examples.BetterDesign.CarExample.CarParts.Doors  : uses 
Examples.BetterDesign.DBCar .[#6060BB].> Examples.BetterDesign.CarExample.CarParts.Wheels  : uses 
' Class relations extracted from namespace:
' Examples.BetterDesign.CarExample
Examples.BetterDesign.CarExample.Vehicle <|-[#red]- Examples.BetterDesign.CarExample.Car
Examples.BetterDesign.CarExample.Car *-[#10BB10]- Examples.BetterDesign.CarExample.CarParts.Wheels 
Examples.BetterDesign.CarExample.Car *-[#10BB10]- Examples.BetterDesign.CarExample.CarParts.Seats 
Examples.BetterDesign.CarExample.Car *-[#10BB10]- Examples.BetterDesign.CarExample.CarParts.Driver 
Examples.BetterDesign.CarExample.Car *-[#10BB10]- Examples.BetterDesign.CarExample.CarParts.Doors 
Examples.BetterDesign.CarExample.Car .[#6060BB].> Examples.BetterDesign.CarExample.CarParts.Doors  : uses 
Examples.BetterDesign.CarExample.Vehicle *-[#10BB10]- Examples.BetterDesign.DBCar 
' Class relations extracted from namespace:
' Examples.BetterDesign.CarExample.CarParts
Examples.BetterDesign.CarExample.CarParts.Wheels *-[#10BB10]- Examples.BetterDesign.DBCar 
Examples.BetterDesign.CarExample.CarParts.Seats *-[#10BB10]- Examples.BetterDesign.DBCar 
Examples.BetterDesign.CarExample.CarParts.Driver *-[#10BB10]- Examples.BetterDesign.DBCar 
Examples.BetterDesign.CarExample.CarParts.Doors *-[#10BB10]- Examples.BetterDesign.DBCar 
@enduml