@startuml
skinparam linetype ortho
title <size:20>Examples.BasicExample **detailed** </size>
note "Your are analyzing:\nExamples.BasicExample **detailed** \n\n==Filter==\nYou can click either the namespaces \nor class names for filtering them and their\ndirect dependencies.\n\n==Select other==\n* Examples.BasicExample **simplified** :\n   [[Examples.BasicExample-diagram-simplified.svg]]\n* Full diagram **detailed** and **grouped per namespace**:\n   [[full-diagram-detailed-grouped-per-namespace.svg]]\n* Home:\n   [[index.html]]" as FloatingNote
  class Examples.BasicExample.ClassExample_DOT_InnerClassExample [[Examples.BasicExample.ClassExample.InnerClassExample-diagram-detailed.svg]] #yellow {
    + methodClassInnerClassExample(<font color="6060BB">useless1:Examples.BasicExample.Useless</font>): <font color="BB6060">void</font>
  }
  class Examples.BasicExample.Useless [[Examples.BasicExample.Useless-diagram-detailed.svg]] #yellow {
    + useless(<font color="6060BB"></font>): <font color="BB6060">void</font>
    - <font color="909090">useless.testEnum: Examples.BasicExample.SideExample.SideTestEnum</font>
--
  }
  class Examples.BasicExample.ClassExample_DOT_InnerClassExample_DOT_classInMethodExample [[Examples.BasicExample.ClassExample.InnerClassExample.classInMethodExample-diagram-detailed.svg]] #yellow {
  }
  class Examples.BasicExample.BaseExample [[Examples.BasicExample.BaseExample-diagram-detailed.svg]] #yellow {
    + exampleAbstract(<font color="6060BB">useless1:Examples.BasicExample.Useless, useless2:Examples.BasicExample.Useless</font>): <font color="BB6060">Examples.BasicExample.Useless</font>
    + otherExample(<font color="6060BB"></font>): <font color="BB6060">void</font>
  }
  abstract class Examples.BasicExample.AbstractBaseExample [[Examples.BasicExample.AbstractBaseExample-diagram-detailed.svg]] #yellow {
    + exampleAbstract(<font color="6060BB">useless1:Examples.BasicExample.Useless, useless2:Examples.BasicExample.Useless</font>): <font color="BB6060">Examples.BasicExample.Useless</font>
  }
  class Examples.BasicExample.BaseExample_DOT_EnumTest [[Examples.BasicExample.BaseExample.EnumTest-diagram-detailed.svg]] #yellow {
    + EnumValue1: EnumTypePlaceHolder
    + EnumValue2: EnumTypePlaceHolder
==
  }
  interface Examples.BasicExample.IExample [[Examples.BasicExample.IExample-diagram-detailed.svg]] #yellow {
    + example(<font color="6060BB">useless1:Examples.BasicExample.Useless, useless2:Examples.BasicExample.Useless</font>): <font color="BB6060">void</font>
  }
  class Examples.BasicExample.ClassExample [[Examples.BasicExample.ClassExample-diagram-detailed.svg]] #yellow {
    + memberVarUseless: Examples.BasicExample.Useless
    + memberVarEnumTest: Examples.BasicExample.BaseExample.EnumTest
==
    + example(<font color="6060BB">useless1:Examples.BasicExample.Useless, useless2:Examples.BasicExample.Useless</font>): <font color="BB6060">void</font>
    - <font color="909090">example.localVarBaseExample: Examples.BasicExample.BaseExample</font>
--
    + getExample(<font color="6060BB"></font>): <font color="BB6060">Examples.BasicExample.IExample</font>
    + exampleAbstract(<font color="6060BB">useless1:Examples.BasicExample.Useless, useless2:Examples.BasicExample.Useless</font>): <font color="BB6060">Examples.BasicExample.Useless</font>
  }
    class Examples.BasicExample.SideExample.SideTestEnum [[Examples.BasicExample.SideExample.SideTestEnum-diagram-detailed.svg]] #yellow {
      + TestEnumValue1: EnumTypePlaceHolder
      + TestEnumValue2: EnumTypePlaceHolder
==
    }
    class Examples.BasicExample.SideExample.SideExample [[Examples.BasicExample.SideExample.SideExample-diagram-detailed.svg]] #yellow {
      + test(<font color="6060BB">testEnum:Examples.BasicExample.SideExample.SideTestEnum</font>): <font color="BB6060">void</font>
      + testNoParameter(<font color="6060BB"></font>): <font color="BB6060">void</font>
    }
 ' *************************************** 
 ' *************************************** 
 ' *************************************** 
' Class relations extracted from namespace:
' Examples.BasicExample
Examples.BasicExample.ClassExample_DOT_InnerClassExample +-[#10BBBB]- Examples.BasicExample.ClassExample_DOT_InnerClassExample_DOT_classInMethodExample 
Examples.BasicExample.ClassExample.InnerClassExample .[#6060BB].> Examples.BasicExample.Useless  : uses 
Examples.BasicExample.Useless -[#909090]-> Examples.BasicExample.SideExample.SideTestEnum  : uses 
Examples.BasicExample.AbstractBaseExample <|-[#red]- Examples.BasicExample.BaseExample
Examples.BasicExample.BaseExample +-[#10BBBB]- Examples.BasicExample.BaseExample_DOT_EnumTest 
Examples.BasicExample.BaseExample .[#6060BB].> Examples.BasicExample.Useless  : uses 
Examples.BasicExample.AbstractBaseExample .[#6060BB].> Examples.BasicExample.Useless  : uses 
Examples.BasicExample.IExample .[#6060BB].> Examples.BasicExample.Useless  : uses 
Examples.BasicExample.BaseExample <|-[#red]- Examples.BasicExample.ClassExample
Examples.BasicExample.ClassExample +-[#10BBBB]- Examples.BasicExample.ClassExample_DOT_InnerClassExample 
Examples.BasicExample.ClassExample *-[#10BB10]- Examples.BasicExample.Useless 
Examples.BasicExample.ClassExample *-[#10BB10]- Examples.BasicExample.BaseExample.EnumTest 
Examples.BasicExample.ClassExample .[#6060BB].> Examples.BasicExample.Useless  : uses 
Examples.BasicExample.ClassExample -[#909090]-> Examples.BasicExample.BaseExample  : uses 
Examples.BasicExample.ClassExample .[#6060BB].> Examples.BasicExample.IExample  : uses 
' Class relations extracted from namespace:
' Examples.BasicExample.SideExample
Examples.BasicExample.SideExample.SideExample .[#6060BB].> Examples.BasicExample.SideExample.SideTestEnum  : uses 
@enduml