@startuml
title <size:20>Example.SideExample **simplified** </size>
note "Your are analyzing:\nExample.SideExample **simplified** \n\n==Filter==\nYou can click either the namespaces \nor class names for filtering them and their\ndirect dependencies.\n\n==Select other==\n* Example.SideExample **detailed** :\n   [[Example.SideExample-diagram-detailed.svg]]\n* Full diagram **simplified** and **grouped per namespace**:\n   [[full-diagram-simplified-grouped-per-namespace.svg]]\n* Home:\n   [[index.html]]" as FloatingNote
class EnumTypePlaceHolder [[EnumTypePlaceHolder-diagram-simplified.svg]] #MintCream {
}
class Example.Useless [[Example.Useless-diagram-simplified.svg]]  {
}
  class Example.SideExample.SideTestEnum [[Example.SideExample.SideTestEnum-diagram-simplified.svg]] #yellow {
  }
  class Example.SideExample.SideExample [[Example.SideExample.SideExample-diagram-simplified.svg]] #yellow {
  }
 ' *************************************** 
 ' *************************************** 
 ' *************************************** 
' Class relations extracted from namespace:
' 
' Class relations extracted from namespace:
' Example
Example.Useless -[#909090]-> Example.SideExample.SideTestEnum  : uses 
' Class relations extracted from namespace:
' Example.SideExample
Example.SideExample.SideTestEnum .[#6060BB].> EnumTypePlaceHolder  : uses 
Example.SideExample.SideExample .[#6060BB].> Example.SideExample.SideTestEnum  : uses 
@enduml