@startuml
skinparam linetype ortho
title <size:20>Examples.BetterDesign.FakeEntitities **detailed** </size>
note "Your are analyzing:\nExamples.BetterDesign.FakeEntitities **detailed** \n\n==Filter==\nYou can click either the namespaces \nor class names for filtering them and their\ndirect dependencies.\n\n==Select other==\n* Examples.BetterDesign.FakeEntitities **simplified** :\n   [[Examples.BetterDesign.FakeEntitities-diagram-simplified.svg]]\n* Full diagram **detailed** and **grouped per namespace**:\n   [[full-diagram-detailed-grouped-per-namespace.svg]]\n* Home:\n   [[index.html]]" as FloatingNote
  class Examples.BetterDesign.DBCustomers [[Examples.BetterDesign.DBCustomers-diagram-detailed.svg]]  {
    + getCustomer(<font color="6060BB">i:Examples.BetterDesign.FakeEntitities.Invoice</font>): <font color="BB6060">Examples.BetterDesign.FakeEntitities.Customer</font>
    + getItem(<font color="6060BB">c:Examples.BetterDesign.FakeEntitities.Complaints</font>): <font color="BB6060">Examples.BetterDesign.FakeEntitities.Item</font>
    + getInvoice(<font color="6060BB">c:Examples.BetterDesign.FakeEntitities.Customer</font>): <font color="BB6060">Examples.BetterDesign.FakeEntitities.Invoice</font>
    + getComplaints(<font color="6060BB">c:Examples.BetterDesign.FakeEntitities.Customer</font>): <font color="BB6060">Examples.BetterDesign.FakeEntitities.Complaints</font>
    + getUser(<font color="6060BB">item:Examples.BetterDesign.FakeEntitities.Item</font>): <font color="BB6060">Examples.BetterDesign.FakeEntitities.User</font>
    + getCustomer(<font color="6060BB">complaint:Examples.BetterDesign.FakeEntitities.Complaints</font>): <font color="BB6060">Examples.BetterDesign.FakeEntitities.Customer</font>
    + getItem(<font color="6060BB">user:Examples.BetterDesign.FakeEntitities.User</font>): <font color="BB6060">Examples.BetterDesign.FakeEntitities.Item</font>
    + getComplaints(<font color="6060BB">item:Examples.BetterDesign.FakeEntitities.Item</font>): <font color="BB6060">Examples.BetterDesign.FakeEntitities.Complaints</font>
    + getFirstUser(<font color="6060BB"></font>): <font color="BB6060">Examples.BetterDesign.FakeEntitities.User</font>
    + getFirstItem(<font color="6060BB"></font>): <font color="BB6060">Examples.BetterDesign.FakeEntitities.Item</font>
    + getFirstInvoice(<font color="6060BB"></font>): <font color="BB6060">Examples.BetterDesign.FakeEntitities.Invoice</font>
    + getFirstComplaints(<font color="6060BB"></font>): <font color="BB6060">Examples.BetterDesign.FakeEntitities.Complaints</font>
  }
    class Examples.BetterDesign.FakeEntitities.Item [[Examples.BetterDesign.FakeEntitities.Item-diagram-detailed.svg]] #yellow {
    }
    class Examples.BetterDesign.FakeEntitities.User [[Examples.BetterDesign.FakeEntitities.User-diagram-detailed.svg]] #yellow {
    }
    class Examples.BetterDesign.FakeEntitities.Complaints [[Examples.BetterDesign.FakeEntitities.Complaints-diagram-detailed.svg]] #yellow {
    }
    class Examples.BetterDesign.FakeEntitities.Invoice [[Examples.BetterDesign.FakeEntitities.Invoice-diagram-detailed.svg]] #yellow {
    }
    class Examples.BetterDesign.FakeEntitities.Customer [[Examples.BetterDesign.FakeEntitities.Customer-diagram-detailed.svg]] #yellow {
    }
 ' *************************************** 
 ' *************************************** 
 ' *************************************** 
' Class relations extracted from namespace:
' Examples.BetterDesign
Examples.BetterDesign.DBCustomers .[#6060BB].> Examples.BetterDesign.FakeEntitities.Customer  : uses 
Examples.BetterDesign.DBCustomers .[#6060BB].> Examples.BetterDesign.FakeEntitities.Invoice  : uses 
Examples.BetterDesign.DBCustomers .[#6060BB].> Examples.BetterDesign.FakeEntitities.Item  : uses 
Examples.BetterDesign.DBCustomers .[#6060BB].> Examples.BetterDesign.FakeEntitities.Complaints  : uses 
Examples.BetterDesign.DBCustomers .[#6060BB].> Examples.BetterDesign.FakeEntitities.User  : uses 
' Class relations extracted from namespace:
' Examples.BetterDesign.FakeEntitities
@enduml