@startuml
skinparam linetype ortho
title <size:20>Examples.BetterDesign.DB **simplified** and **grouped per namespace**</size>
note "Your are analyzing:\nExamples.BetterDesign.DB **simplified** and **grouped per namespace**\n\n==Filter==\nYou can click either the namespaces \nor class names for filtering them and their\ndirect dependencies.\n\n==Select other==\n* Examples.BetterDesign.DB **detailed** and **grouped per namespace**:\n   [[Examples.BetterDesign.DB-diagram-detailed-grouped-per-namespace.svg]]\n* Full diagram **simplified** and **grouped per namespace**:\n   [[full-diagram-simplified-grouped-per-namespace.svg]]\n* Home:\n   [[index.html]]" as FloatingNote
class String [[String-diagram-simplified-grouped-per-namespace.svg]] #MintCream {
}
' Closing all previous_sub_namespace_list namespace None because file analysis is finished.
namespace Examples [[Examples-diagram-simplified-grouped-per-namespace.svg]] {
namespace Examples.BadDesign [[Examples.BadDesign-diagram-simplified-grouped-per-namespace.svg]] {
namespace Examples.BadDesign.CarExample [[Examples.BadDesign.CarExample-diagram-simplified-grouped-per-namespace.svg]] {
namespace Examples.BadDesign.CarExample.CarParts [[Examples.BadDesign.CarExample.CarParts-diagram-simplified-grouped-per-namespace.svg]] {
      class Examples.BadDesign.CarExample.CarParts.Driver [[Examples.BadDesign.CarExample.CarParts.Driver-diagram-simplified-grouped-per-namespace.svg]]  {
      }
      class Examples.BadDesign.CarExample.CarParts.Wheels [[Examples.BadDesign.CarExample.CarParts.Wheels-diagram-simplified-grouped-per-namespace.svg]]  {
      }
      class Examples.BadDesign.CarExample.CarParts.Doors [[Examples.BadDesign.CarExample.CarParts.Doors-diagram-simplified-grouped-per-namespace.svg]]  {
      }
      class Examples.BadDesign.CarExample.CarParts.Seats [[Examples.BadDesign.CarExample.CarParts.Seats-diagram-simplified-grouped-per-namespace.svg]]  {
      }
'Compared namespace Examples.BadDesign.CarExample.CarParts [[Examples.BadDesign.CarExample.CarParts-diagram-simplified-grouped-per-namespace.svg]] { with last element of       }
' Closing all previous_sub_namespace_list namespace None because file analysis is finished.
' Closing namespace CarParts
}
' Closing namespace CarExample
}
' Closing namespace BadDesign
}
' Closing namespace Examples
}
namespace Examples [[Examples-diagram-simplified-grouped-per-namespace.svg]] {
namespace Examples.BadDesign [[Examples.BadDesign-diagram-simplified-grouped-per-namespace.svg]] {
namespace Examples.BadDesign.FakeEntitities [[Examples.BadDesign.FakeEntitities-diagram-simplified-grouped-per-namespace.svg]] {
    class Examples.BadDesign.FakeEntitities.User [[Examples.BadDesign.FakeEntitities.User-diagram-simplified-grouped-per-namespace.svg]]  {
    }
    class Examples.BadDesign.FakeEntitities.Customer [[Examples.BadDesign.FakeEntitities.Customer-diagram-simplified-grouped-per-namespace.svg]]  {
    }
    class Examples.BadDesign.FakeEntitities.Invoice [[Examples.BadDesign.FakeEntitities.Invoice-diagram-simplified-grouped-per-namespace.svg]]  {
    }
'Compared namespace Examples.BadDesign.FakeEntitities [[Examples.BadDesign.FakeEntitities-diagram-simplified-grouped-per-namespace.svg]] { with last element of     }
' Closing all previous_sub_namespace_list namespace None because file analysis is finished.
' Closing namespace FakeEntitities
}
' Closing namespace BadDesign
}
' Closing namespace Examples
}
namespace Examples [[Examples-diagram-simplified-grouped-per-namespace.svg]] {
namespace Examples.BetterDesign [[Examples.BetterDesign-diagram-simplified-grouped-per-namespace.svg]] {
  class Examples.BetterDesign.DB [[Examples.BetterDesign.DB-diagram-simplified-grouped-per-namespace.svg]] #yellow {
  }
'Compared namespace Examples.BetterDesign [[Examples.BetterDesign-diagram-simplified-grouped-per-namespace.svg]] { with last element of   }
' Closing all previous_sub_namespace_list namespace None because file analysis is finished.
' Closing namespace BetterDesign
}
' Closing namespace Examples
}
namespace Examples [[Examples-diagram-simplified-grouped-per-namespace.svg]] {
namespace Examples.BetterDesign [[Examples.BetterDesign-diagram-simplified-grouped-per-namespace.svg]] {
namespace Examples.BetterDesign.CarExample [[Examples.BetterDesign.CarExample-diagram-simplified-grouped-per-namespace.svg]] {
    class Examples.BetterDesign.CarExample.Car [[Examples.BetterDesign.CarExample.Car-diagram-simplified-grouped-per-namespace.svg]]  {
    }
'Compared namespace Examples.BetterDesign.CarExample [[Examples.BetterDesign.CarExample-diagram-simplified-grouped-per-namespace.svg]] { with last element of     }
' Closing all previous_sub_namespace_list namespace None because file analysis is finished.
' Closing namespace CarExample
}
' Closing namespace BetterDesign
}
' Closing namespace Examples
}
namespace Examples [[Examples-diagram-simplified-grouped-per-namespace.svg]] {
namespace Examples.BetterDesign [[Examples.BetterDesign-diagram-simplified-grouped-per-namespace.svg]] {
namespace Examples.BetterDesign.FakeEntitities [[Examples.BetterDesign.FakeEntitities-diagram-simplified-grouped-per-namespace.svg]] {
    class Examples.BetterDesign.FakeEntitities.Item [[Examples.BetterDesign.FakeEntitities.Item-diagram-simplified-grouped-per-namespace.svg]]  {
    }
    class Examples.BetterDesign.FakeEntitities.Complaints [[Examples.BetterDesign.FakeEntitities.Complaints-diagram-simplified-grouped-per-namespace.svg]]  {
    }
'Compared namespace Examples.BetterDesign.FakeEntitities [[Examples.BetterDesign.FakeEntitities-diagram-simplified-grouped-per-namespace.svg]] { with last element of     }
' Closing all previous_sub_namespace_list namespace None because file analysis is finished.
' Closing namespace FakeEntitities
}
' Closing namespace BetterDesign
}
' Closing namespace Examples
}
 ' *************************************** 
 ' *************************************** 
 ' *************************************** 
' Class relations extracted from namespace:
' 
' Class relations extracted from namespace:
' Examples.BadDesign.CarExample.CarParts
' Class relations extracted from namespace:
' Examples.BadDesign.FakeEntitities
' Class relations extracted from namespace:
' Examples.BetterDesign
Examples.BetterDesign.DB .[#6060BB].> String  : uses 
Examples.BetterDesign.DB .[#6060BB].> Examples.BadDesign.FakeEntitities.User  : uses 
Examples.BetterDesign.DB .[#6060BB].> Examples.BadDesign.FakeEntitities.Customer  : uses 
Examples.BetterDesign.DB .[#6060BB].> Examples.BetterDesign.FakeEntitities.Item  : uses 
Examples.BetterDesign.DB .[#6060BB].> Examples.BadDesign.FakeEntitities.Invoice  : uses 
Examples.BetterDesign.DB .[#6060BB].> Examples.BetterDesign.FakeEntitities.Complaints  : uses 
Examples.BetterDesign.DB .[#6060BB].> Examples.BetterDesign.CarExample.Car  : uses 
Examples.BetterDesign.DB .[#6060BB].> Examples.BadDesign.CarExample.CarParts.Driver  : uses 
Examples.BetterDesign.DB .[#6060BB].> Examples.BadDesign.CarExample.CarParts.Wheels  : uses 
Examples.BetterDesign.DB .[#6060BB].> Examples.BadDesign.CarExample.CarParts.Doors  : uses 
Examples.BetterDesign.DB .[#6060BB].> Examples.BadDesign.CarExample.CarParts.Seats  : uses 
' Class relations extracted from namespace:
' Examples.BetterDesign.CarExample
Examples.BadDesign.CarExample.CarParts.Driver <|-[#red]- Examples.BetterDesign.CarExample.Car
Examples.BetterDesign.CarExample.Car *-[#10BB10]- Examples.BadDesign.CarExample.CarParts.Wheels 
Examples.BetterDesign.CarExample.Car .[#6060BB].> Examples.BadDesign.CarExample.CarParts.Doors  : uses 
Examples.BetterDesign.CarExample.Car -[#909090]-> Examples.BadDesign.CarExample.CarParts.Seats  : uses 
' Class relations extracted from namespace:
' Examples.BetterDesign.FakeEntitities
@enduml