@startuml
skinparam linetype ortho
title <size:20>Examples.BadDesign.CarExample.CarParts_DOT_Driver **simplified** </size>
note "Your are analyzing:\nExamples.BadDesign.CarExample.CarParts_DOT_Driver **simplified** \n\n==Filter==\nYou can click either the namespaces \nor class names for filtering them and their\ndirect dependencies.\n\n==Select other==\n* Examples.BadDesign.CarExample.CarParts_DOT_Driver **detailed** :\n   [[Examples.BadDesign.CarExample.CarParts_DOT_Driver-diagram-detailed.svg]]\n* Full diagram **simplified** and **grouped per namespace**:\n   [[full-diagram-simplified-grouped-per-namespace.svg]]\n* Home:\n   [[index.html]]" as FloatingNote
class Examples.BadDesign.CarExample.CarParts_DOT_Driver [[Examples.BadDesign.CarExample.CarParts_DOT_Driver-diagram-simplified.svg]] #yellow {
}
    class Examples.BadDesign.CarExample.Car [[Examples.BadDesign.CarExample.Car-diagram-simplified.svg]]  {
    }
 ' *************************************** 
 ' *************************************** 
 ' *************************************** 
' Class relations extracted from namespace:
' 
' Class relations extracted from namespace:
' Examples.BadDesign.CarExample
Examples.BadDesign.CarExample.CarParts_DOT_Driver <|-[#red]- Examples.BadDesign.CarExample.Car
@enduml