@startuml
skinparam linetype ortho
title <size:20>Examples.BadDesign.FakeEntitities.User **detailed** </size>
note "Your are analyzing:\nExamples.BadDesign.FakeEntitities.User **detailed** \n\n==Filter==\nYou can click either the namespaces \nor class names for filtering them and their\ndirect dependencies.\n\n==Select other==\n* Examples.BadDesign.FakeEntitities.User **simplified** :\n   [[Examples.BadDesign.FakeEntitities.User-diagram-simplified.svg]]\n* Full diagram **detailed** and **grouped per namespace**:\n   [[full-diagram-detailed-grouped-per-namespace.svg]]\n* Home:\n   [[index.html]]" as FloatingNote
  class Examples.BadDesign.DB [[Examples.BadDesign.DB-diagram-detailed.svg]]  {
    + get(<font color="6060BB">queryString:String</font>): <font color="BB6060">String</font>
    + getCarsWhere(<font color="6060BB">whereQueryString:String</font>): <font color="BB6060">String</font>
    + set(<font color="6060BB">queryString:String</font>): <font color="BB6060">void</font>
    + update(<font color="6060BB">queryString:String</font>): <font color="BB6060">void</font>
    + getUserWhere(<font color="6060BB">query:String</font>): <font color="BB6060">Examples.BadDesign.FakeEntitities.User</font>
    + getCustomerWhere(<font color="6060BB">query:String</font>): <font color="BB6060">Examples.BadDesign.FakeEntitities.Customer</font>
    + getItemWhere(<font color="6060BB">query:String</font>): <font color="BB6060">Examples.BadDesign.FakeEntitities.Item</font>
    + getInvoiceWhere(<font color="6060BB">query:String</font>): <font color="BB6060">Examples.BadDesign.FakeEntitities.Invoice</font>
    + getComplaintsWhere(<font color="6060BB">query:String</font>): <font color="BB6060">Examples.BadDesign.FakeEntitities.Complaints</font>
    + getUserHavingItem(<font color="6060BB">item:Examples.BadDesign.FakeEntitities.Item</font>): <font color="BB6060">Examples.BadDesign.FakeEntitities.User</font>
    + getCustomerFromComplaint(<font color="6060BB">complaint:Examples.BadDesign.FakeEntitities.Complaints</font>): <font color="BB6060">Examples.BadDesign.FakeEntitities.Customer</font>
    + getItemFromUser(<font color="6060BB">user:Examples.BadDesign.FakeEntitities.User</font>): <font color="BB6060">Examples.BadDesign.FakeEntitities.Item</font>
    + getInvoiceFromCustomer(<font color="6060BB">c:Examples.BadDesign.FakeEntitities.Customer</font>): <font color="BB6060">Examples.BadDesign.FakeEntitities.Invoice</font>
    + getComplaintsFromItem(<font color="6060BB">item:Examples.BadDesign.FakeEntitities.Item</font>): <font color="BB6060">Examples.BadDesign.FakeEntitities.Complaints</font>
    + getFirstUser(<font color="6060BB"></font>): <font color="BB6060">Examples.BadDesign.FakeEntitities.User</font>
    + getFirstCustomerWhere(<font color="6060BB"></font>): <font color="BB6060">Examples.BadDesign.FakeEntitities.Customer</font>
    + getFirstItem(<font color="6060BB"></font>): <font color="BB6060">Examples.BadDesign.FakeEntitities.Item</font>
    + getFirstInvoice(<font color="6060BB"></font>): <font color="BB6060">Examples.BadDesign.FakeEntitities.Invoice</font>
    + getFirstComplaints(<font color="6060BB"></font>): <font color="BB6060">Examples.BadDesign.FakeEntitities.Complaints</font>
    + getCarFromDriver(<font color="6060BB">d:Examples.BadDesign.CarExample.CarParts.Driver</font>): <font color="BB6060">Examples.BadDesign.CarExample.Car</font>
    + getDriverFromCar(<font color="6060BB">c:Examples.BadDesign.CarExample.Car</font>): <font color="BB6060">Examples.BadDesign.CarExample.CarParts.Driver</font>
    + getWheelsFromCar(<font color="6060BB">c:Examples.BadDesign.CarExample.Car</font>): <font color="BB6060">Examples.BadDesign.CarExample.CarParts.Wheels</font>
    + getDoorsFromCar(<font color="6060BB">c:Examples.BadDesign.CarExample.Car</font>): <font color="BB6060">Examples.BadDesign.CarExample.CarParts.Doors</font>
    + getSeatsFromCar(<font color="6060BB">c:Examples.BadDesign.CarExample.Car</font>): <font color="BB6060">Examples.BadDesign.CarExample.CarParts.Seats</font>
  }
    class Examples.BadDesign.FakeEntitities.User [[Examples.BadDesign.FakeEntitities.User-diagram-detailed.svg]] #yellow {
    }
 ' *************************************** 
 ' *************************************** 
 ' *************************************** 
' Class relations extracted from namespace:
' Examples.BadDesign
Examples.BadDesign.DB .[#6060BB].> Examples.BadDesign.FakeEntitities.User  : uses 
' Class relations extracted from namespace:
' Examples.BadDesign.FakeEntitities
@enduml