@startuml
skinparam linetype ortho
title <size:20>Examples.BadDesign.BasicExample.AbstractBaseExample **simplified** and **grouped per namespace**</size>
note "Your are analyzing:\nExamples.BadDesign.BasicExample.AbstractBaseExample **simplified** and **grouped per namespace**\n\n==Filter==\nYou can click either the namespaces \nor class names for filtering them and their\ndirect dependencies.\n\n==Select other==\n* Examples.BadDesign.BasicExample.AbstractBaseExample **detailed** and **grouped per namespace**:\n   [[Examples.BadDesign.BasicExample.AbstractBaseExample-diagram-detailed-grouped-per-namespace.svg]]\n* Full diagram **simplified** and **grouped per namespace**:\n   [[full-diagram-simplified-grouped-per-namespace.svg]]\n* Home:\n   [[index.html]]" as FloatingNote
namespace Examples [[Examples-diagram-simplified-grouped-per-namespace.svg]] {
namespace Examples.BadDesign [[Examples.BadDesign-diagram-simplified-grouped-per-namespace.svg]] {
namespace Examples.BadDesign.BasicExample [[Examples.BadDesign.BasicExample-diagram-simplified-grouped-per-namespace.svg]] {
    abstract class Examples.BadDesign.BasicExample.AbstractBaseExample [[Examples.BadDesign.BasicExample.AbstractBaseExample-diagram-simplified-grouped-per-namespace.svg]] #yellow {
    }
    class Examples.BadDesign.BasicExample.Useless [[Examples.BadDesign.BasicExample.Useless-diagram-simplified-grouped-per-namespace.svg]]  {
    }
    class Examples.BadDesign.BasicExample.BaseExample [[Examples.BadDesign.BasicExample.BaseExample-diagram-simplified-grouped-per-namespace.svg]]  {
    }
'Compared namespace Examples.BadDesign.BasicExample [[Examples.BadDesign.BasicExample-diagram-simplified-grouped-per-namespace.svg]] { with last element of     }
' Closing all previous_sub_namespace_list namespace None because file analysis is finished.
' Closing namespace BasicExample
}
' Closing namespace BadDesign
}
' Closing namespace Examples
}
 ' *************************************** 
 ' *************************************** 
 ' *************************************** 
' Class relations extracted from namespace:
' Examples.BadDesign.BasicExample
Examples.BadDesign.BasicExample.AbstractBaseExample .[#6060BB].> Examples.BadDesign.BasicExample.Useless  : uses 
Examples.BadDesign.BasicExample.AbstractBaseExample <|-[#red]- Examples.BadDesign.BasicExample.BaseExample
Examples.BadDesign.BasicExample.BaseExample .[#6060BB].> Examples.BadDesign.BasicExample.Useless  : uses 
@enduml