@startuml
skinparam linetype ortho
title <size:20>Examples.BetterDesign.CarExample.CarParts.Seats **simplified** and **grouped per namespace**</size>
note "Your are analyzing:\nExamples.BetterDesign.CarExample.CarParts.Seats **simplified** and **grouped per namespace**\n\n==Filter==\nYou can click either the namespaces \nor class names for filtering them and their\ndirect dependencies.\n\n==Select other==\n* Examples.BetterDesign.CarExample.CarParts.Seats **detailed** and **grouped per namespace**:\n   [[Examples.BetterDesign.CarExample.CarParts.Seats-diagram-detailed-grouped-per-namespace.svg]]\n* Full diagram **simplified** and **grouped per namespace**:\n   [[full-diagram-simplified-grouped-per-namespace.svg]]\n* Home:\n   [[index.html]]" as FloatingNote
namespace Examples [[Examples-diagram-simplified-grouped-per-namespace.svg]] {
namespace Examples.BetterDesign [[Examples.BetterDesign-diagram-simplified-grouped-per-namespace.svg]] {
  class Examples.BetterDesign.DBCar [[Examples.BetterDesign.DBCar-diagram-simplified-grouped-per-namespace.svg]]  {
  }
'Compared namespace Examples.BetterDesign [[Examples.BetterDesign-diagram-simplified-grouped-per-namespace.svg]] { with last element of   }
' Closing all previous_sub_namespace_list namespace None because file analysis is finished.
' Closing namespace BetterDesign
}
' Closing namespace Examples
}
namespace Examples [[Examples-diagram-simplified-grouped-per-namespace.svg]] {
namespace Examples.BetterDesign [[Examples.BetterDesign-diagram-simplified-grouped-per-namespace.svg]] {
namespace Examples.BetterDesign.CarExample [[Examples.BetterDesign.CarExample-diagram-simplified-grouped-per-namespace.svg]] {
    class Examples.BetterDesign.CarExample.Car [[Examples.BetterDesign.CarExample.Car-diagram-simplified-grouped-per-namespace.svg]]  {
    }
'Compared namespace Examples.BetterDesign.CarExample [[Examples.BetterDesign.CarExample-diagram-simplified-grouped-per-namespace.svg]] { with last element of     }
' Closing all previous_sub_namespace_list namespace None because file analysis is finished.
' Closing namespace CarExample
}
' Closing namespace BetterDesign
}
' Closing namespace Examples
}
namespace Examples [[Examples-diagram-simplified-grouped-per-namespace.svg]] {
namespace Examples.BetterDesign [[Examples.BetterDesign-diagram-simplified-grouped-per-namespace.svg]] {
namespace Examples.BetterDesign.CarExample [[Examples.BetterDesign.CarExample-diagram-simplified-grouped-per-namespace.svg]] {
namespace Examples.BetterDesign.CarExample.CarParts [[Examples.BetterDesign.CarExample.CarParts-diagram-simplified-grouped-per-namespace.svg]] {
      class Examples.BetterDesign.CarExample.CarParts.Seats [[Examples.BetterDesign.CarExample.CarParts.Seats-diagram-simplified-grouped-per-namespace.svg]] #yellow {
      }
'Compared namespace Examples.BetterDesign.CarExample.CarParts [[Examples.BetterDesign.CarExample.CarParts-diagram-simplified-grouped-per-namespace.svg]] { with last element of       }
' Closing all previous_sub_namespace_list namespace None because file analysis is finished.
' Closing namespace CarParts
}
' Closing namespace CarExample
}
' Closing namespace BetterDesign
}
' Closing namespace Examples
}
 ' *************************************** 
 ' *************************************** 
 ' *************************************** 
' Class relations extracted from namespace:
' Examples.BetterDesign
Examples.BetterDesign.DBCar .[#6060BB].> Examples.BetterDesign.CarExample.Car  : uses 
Examples.BetterDesign.DBCar .[#6060BB].> Examples.BetterDesign.CarExample.CarParts.Seats  : uses 
' Class relations extracted from namespace:
' Examples.BetterDesign.CarExample
Examples.BetterDesign.CarExample.Car *-[#10BB10]- Examples.BetterDesign.CarExample.CarParts.Seats 
' Class relations extracted from namespace:
' Examples.BetterDesign.CarExample.CarParts
Examples.BetterDesign.CarExample.CarParts.Seats *-[#10BB10]- Examples.BetterDesign.DBCar 
@enduml