@startuml
skinparam linetype ortho
title <size:20>Examples.BadDesign.BasicExample.SideExample.SideTestEnum **detailed** </size>
note "Your are analyzing:\nExamples.BadDesign.BasicExample.SideExample.SideTestEnum **detailed** \n\n==Filter==\nYou can click either the namespaces \nor class names for filtering them and their\ndirect dependencies.\n\n==Select other==\n* Examples.BadDesign.BasicExample.SideExample.SideTestEnum **simplified** :\n   [[Examples.BadDesign.BasicExample.SideExample.SideTestEnum-diagram-simplified.svg]]\n* Full diagram **detailed** and **grouped per namespace**:\n   [[full-diagram-detailed-grouped-per-namespace.svg]]\n* Home:\n   [[index.html]]" as FloatingNote
    class Examples.BadDesign.BasicExample.Useless [[Examples.BadDesign.BasicExample.Useless-diagram-detailed.svg]]  {
      + useless(<font color="6060BB"></font>): <font color="BB6060">void</font>
      - <font color="909090">useless.testEnum: Examples.BadDesign.BasicExample.SideExample.SideTestEnum</font>
--
    }
      class Examples.BadDesign.BasicExample.SideExample.SideTestEnum [[Examples.BadDesign.BasicExample.SideExample.SideTestEnum-diagram-detailed.svg]] #yellow {
        + TestEnumValue1: EnumTypePlaceHolder
        + TestEnumValue2: EnumTypePlaceHolder
==
      }
      class Examples.BadDesign.BasicExample.SideExample.SideExample [[Examples.BadDesign.BasicExample.SideExample.SideExample-diagram-detailed.svg]]  {
        + test(<font color="6060BB">testEnum:Examples.BadDesign.BasicExample.SideExample.SideTestEnum</font>): <font color="BB6060">void</font>
        + testNoParameter(<font color="6060BB"></font>): <font color="BB6060">void</font>
      }
 ' *************************************** 
 ' *************************************** 
 ' *************************************** 
' Class relations extracted from namespace:
' Examples.BadDesign.BasicExample
Examples.BadDesign.BasicExample.Useless -[#909090]-> Examples.BadDesign.BasicExample.SideExample.SideTestEnum  : uses 
' Class relations extracted from namespace:
' Examples.BadDesign.BasicExample.SideExample
Examples.BadDesign.BasicExample.SideExample.SideExample .[#6060BB].> Examples.BadDesign.BasicExample.SideExample.SideTestEnum  : uses 
@enduml