@startuml
title <size:20>Example.ClassExample **detailed** </size>
note "Your are analyzing:\nExample.ClassExample **detailed** \n\n==Filter==\nYou can click either the namespaces \nor class names for filtering them and their\ndirect dependencies.\n\n==Select other==\n* Example.ClassExample **simplified** :\n   [[Example.ClassExample-diagram-simplified.svg]]\n* Full diagram **detailed** and **grouped per namespace**:\n   [[full-diagram-detailed-grouped-per-namespace.svg]]\n* Home:\n   [[index.html]]" as FloatingNote
class EnumTest [[EnumTest-diagram-detailed.svg]] #MintCream {
}
class Example.ClassExample [[Example.ClassExample-diagram-detailed.svg]] #yellow {
  + memberVarUseless: Example.Useless
  + memberVarEnumTest: EnumTest
==
  + example(<font color="6060BB">example:Example.Useless, example:Example.Useless</font>)
  - <font color="909090">example.localVarBaseExample: Example.BaseExample</font>
--
  + getExample(<font color="6060BB"></font>)
  + exampleAbstract(<font color="6060BB">exampleAbstract:Example.Useless, exampleAbstract:Example.Useless</font>)
}
class Example.BaseExample [[Example.BaseExample-diagram-detailed.svg]]  {
  + exampleAbstract(<font color="6060BB">exampleAbstract:Example.Useless, exampleAbstract:Example.Useless</font>)
  + otherExample(<font color="6060BB"></font>)
}
class Example.Useless [[Example.Useless-diagram-detailed.svg]]  {
  + useless(<font color="6060BB"></font>)
  - <font color="909090">useless.testEnum: Example.SideExample.SideTestEnum</font>
--
}
class Example.ClassExample_DOT_InnerClassExample [[Example.ClassExample_DOT_InnerClassExample-diagram-detailed.svg]]  {
}
 ' *************************************** 
 ' *************************************** 
 ' *************************************** 
' Class relations extracted from namespace:
' 
' Class relations extracted from namespace:
' Example
Example.BaseExample <|-[#red]- Example.ClassExample
Example.ClassExample +-[#10BBBB]- Example.ClassExample_DOT_InnerClassExample 
Example.ClassExample .[#6060BB].> Example.Useless  : uses 
Example.ClassExample .[#6060BB].> EnumTest  : uses 
Example.ClassExample -[#909090]-> Example.BaseExample  : uses 
Example.BaseExample .[#6060BB].> Example.Useless  : uses 
@enduml