@startuml
skinparam linetype ortho
title <size:20>Examples.BadDesign.BasicExample.SideExample.SideTestEnum **simplified** and **grouped per namespace**</size>
note "Your are analyzing:\nExamples.BadDesign.BasicExample.SideExample.SideTestEnum **simplified** and **grouped per namespace**\n\n==Filter==\nYou can click either the namespaces \nor class names for filtering them and their\ndirect dependencies.\n\n==Select other==\n* Examples.BadDesign.BasicExample.SideExample.SideTestEnum **detailed** and **grouped per namespace**:\n   [[Examples.BadDesign.BasicExample.SideExample.SideTestEnum-diagram-detailed-grouped-per-namespace.svg]]\n* Full diagram **simplified** and **grouped per namespace**:\n   [[full-diagram-simplified-grouped-per-namespace.svg]]\n* Home:\n   [[index.html]]" as FloatingNote
namespace Examples [[Examples-diagram-simplified-grouped-per-namespace.svg]] {
namespace Examples.BadDesign [[Examples.BadDesign-diagram-simplified-grouped-per-namespace.svg]] {
namespace Examples.BadDesign.BasicExample [[Examples.BadDesign.BasicExample-diagram-simplified-grouped-per-namespace.svg]] {
    class Examples.BadDesign.BasicExample.Useless [[Examples.BadDesign.BasicExample.Useless-diagram-simplified-grouped-per-namespace.svg]]  {
    }
'Compared namespace Examples.BadDesign.BasicExample [[Examples.BadDesign.BasicExample-diagram-simplified-grouped-per-namespace.svg]] { with last element of     }
' Closing all previous_sub_namespace_list namespace None because file analysis is finished.
' Closing namespace BasicExample
}
' Closing namespace BadDesign
}
' Closing namespace Examples
}
namespace Examples [[Examples-diagram-simplified-grouped-per-namespace.svg]] {
namespace Examples.BadDesign [[Examples.BadDesign-diagram-simplified-grouped-per-namespace.svg]] {
namespace Examples.BadDesign.BasicExample [[Examples.BadDesign.BasicExample-diagram-simplified-grouped-per-namespace.svg]] {
namespace Examples.BadDesign.BasicExample.SideExample [[Examples.BadDesign.BasicExample.SideExample-diagram-simplified-grouped-per-namespace.svg]] {
      class Examples.BadDesign.BasicExample.SideExample.SideTestEnum [[Examples.BadDesign.BasicExample.SideExample.SideTestEnum-diagram-simplified-grouped-per-namespace.svg]] #yellow {
      }
      class Examples.BadDesign.BasicExample.SideExample.SideExample [[Examples.BadDesign.BasicExample.SideExample.SideExample-diagram-simplified-grouped-per-namespace.svg]]  {
      }
'Compared namespace Examples.BadDesign.BasicExample.SideExample [[Examples.BadDesign.BasicExample.SideExample-diagram-simplified-grouped-per-namespace.svg]] { with last element of       }
' Closing all previous_sub_namespace_list namespace None because file analysis is finished.
' Closing namespace SideExample
}
' Closing namespace BasicExample
}
' Closing namespace BadDesign
}
' Closing namespace Examples
}
 ' *************************************** 
 ' *************************************** 
 ' *************************************** 
' Class relations extracted from namespace:
' Examples.BadDesign.BasicExample
Examples.BadDesign.BasicExample.Useless -[#909090]-> Examples.BadDesign.BasicExample.SideExample.SideTestEnum  : uses 
' Class relations extracted from namespace:
' Examples.BadDesign.BasicExample.SideExample
Examples.BadDesign.BasicExample.SideExample.SideExample .[#6060BB].> Examples.BadDesign.BasicExample.SideExample.SideTestEnum  : uses 
@enduml