@startuml
skinparam linetype ortho
title <size:20>Examples.BasicExample.SideExample.SideExample **detailed** </size>
note "Your are analyzing:\nExamples.BasicExample.SideExample.SideExample **detailed** \n\n==Filter==\nYou can click either the namespaces \nor class names for filtering them and their\ndirect dependencies.\n\n==Select other==\n* Examples.BasicExample.SideExample.SideExample **simplified** :\n   [[Examples.BasicExample.SideExample.SideExample-diagram-simplified.svg]]\n* Full diagram **detailed** and **grouped per namespace**:\n   [[full-diagram-detailed-grouped-per-namespace.svg]]\n* Home:\n   [[index.html]]" as FloatingNote
    class Examples.BasicExample.SideExample.SideExample [[Examples.BasicExample.SideExample.SideExample-diagram-detailed.svg]] #yellow {
      + test(<font color="6060BB">testEnum:Examples.BasicExample.SideExample.SideTestEnum</font>): <font color="BB6060">void</font>
      + testNoParameter(<font color="6060BB"></font>): <font color="BB6060">void</font>
    }
    class Examples.BasicExample.SideExample.SideTestEnum [[Examples.BasicExample.SideExample.SideTestEnum-diagram-detailed.svg]]  {
      + TestEnumValue1: EnumTypePlaceHolder
      + TestEnumValue2: EnumTypePlaceHolder
==
    }
 ' *************************************** 
 ' *************************************** 
 ' *************************************** 
' Class relations extracted from namespace:
' Examples.BasicExample.SideExample
Examples.BasicExample.SideExample.SideExample .[#6060BB].> Examples.BasicExample.SideExample.SideTestEnum  : uses 
@enduml