@startuml
skinparam linetype ortho
title <size:20>Examples.BadDesign.CarExample.Vehicle **detailed** and **grouped per namespace**</size>
note "Your are analyzing:\nExamples.BadDesign.CarExample.Vehicle **detailed** and **grouped per namespace**\n\n==Filter==\nYou can click either the namespaces \nor class names for filtering them and their\ndirect dependencies.\n\n==Select other==\n* Examples.BadDesign.CarExample.Vehicle **simplified** and **grouped per namespace**:\n   [[Examples.BadDesign.CarExample.Vehicle-diagram-simplified-grouped-per-namespace.svg]]\n* Full diagram **detailed** and **grouped per namespace**:\n   [[full-diagram-detailed-grouped-per-namespace.svg]]\n* Home:\n   [[index.html]]" as FloatingNote
namespace Examples [[Examples-diagram-detailed-grouped-per-namespace.svg]] {
namespace Examples.BadDesign [[Examples.BadDesign-diagram-detailed-grouped-per-namespace.svg]] {
  class Examples.BadDesign.DB [[Examples.BadDesign.DB-diagram-detailed-grouped-per-namespace.svg]]  {
    + get(<font color="6060BB">queryString:String</font>): <font color="BB6060">String</font>
    + getCarsWhere(<font color="6060BB">whereQueryString:String</font>): <font color="BB6060">String</font>
    + set(<font color="6060BB">queryString:String</font>): <font color="BB6060">void</font>
    + update(<font color="6060BB">queryString:String</font>): <font color="BB6060">void</font>
    + getUserWhere(<font color="6060BB">query:String</font>): <font color="BB6060">Examples.BadDesign.WarehouseEntitities.User</font>
    + getCustomerWhere(<font color="6060BB">query:String</font>): <font color="BB6060">Examples.BadDesign.WarehouseEntitities.Customer</font>
    + getWarehouseCarWhere(<font color="6060BB">query:String</font>): <font color="BB6060">Examples.BadDesign.WarehouseEntitities.Car</font>
    + getInvoiceWhere(<font color="6060BB">query:String</font>): <font color="BB6060">Examples.BadDesign.WarehouseEntitities.Invoice</font>
    + getComplaintsWhere(<font color="6060BB">query:String</font>): <font color="BB6060">Examples.BadDesign.WarehouseEntitities.Complaints</font>
    + getFirstCustomerWhere(<font color="6060BB">query:String</font>): <font color="BB6060">Examples.BadDesign.WarehouseEntitities.Customer</font>
    + getUserFromWarehouseCar(<font color="6060BB">item:Examples.BadDesign.WarehouseEntitities.Car</font>): <font color="BB6060">Examples.BadDesign.WarehouseEntitities.User</font>
    + getCustomerFromComplaint(<font color="6060BB">complaint:Examples.BadDesign.WarehouseEntitities.Complaints</font>): <font color="BB6060">Examples.BadDesign.WarehouseEntitities.Customer</font>
    + getWarehouseCarFromUser(<font color="6060BB">user:Examples.BadDesign.WarehouseEntitities.Car</font>): <font color="BB6060">Examples.BadDesign.CarExample.Car</font>
    + getInvoiceFromCustomer(<font color="6060BB">c:Examples.BadDesign.WarehouseEntitities.Customer</font>): <font color="BB6060">Examples.BadDesign.WarehouseEntitities.Invoice</font>
    + getComplaintsFromWarehouseCar(<font color="6060BB">item:Examples.BadDesign.WarehouseEntitities.Car</font>): <font color="BB6060">Examples.BadDesign.WarehouseEntitities.Complaints</font>
    + getCarFromDriver(<font color="6060BB">d:Examples.BadDesign.CarExample.CarParts.Driver</font>): <font color="BB6060">Examples.BadDesign.CarExample.Car</font>
    + getDriverFromCar(<font color="6060BB">c:Examples.BadDesign.CarExample.Car</font>): <font color="BB6060">Examples.BadDesign.CarExample.CarParts.Driver</font>
    + getWheelsFromCar(<font color="6060BB">c:Examples.BadDesign.CarExample.Car</font>): <font color="BB6060">Examples.BadDesign.CarExample.CarParts.Wheels</font>
    + getDoorsFromCar(<font color="6060BB">c:Examples.BadDesign.CarExample.Car</font>): <font color="BB6060">Examples.BadDesign.CarExample.CarParts.Doors</font>
    + getSeatsFromCar(<font color="6060BB">c:Examples.BadDesign.CarExample.Car</font>): <font color="BB6060">Examples.BadDesign.CarExample.CarParts.Seats</font>
  }
'Compared namespace Examples.BadDesign [[Examples.BadDesign-diagram-detailed-grouped-per-namespace.svg]] { with last element of   }
' Closing all previous_sub_namespace_list namespace None because file analysis is finished.
' Closing namespace BadDesign
}
' Closing namespace Examples
}
namespace Examples [[Examples-diagram-detailed-grouped-per-namespace.svg]] {
namespace Examples.BadDesign [[Examples.BadDesign-diagram-detailed-grouped-per-namespace.svg]] {
namespace Examples.BadDesign.CarExample [[Examples.BadDesign.CarExample-diagram-detailed-grouped-per-namespace.svg]] {
    class Examples.BadDesign.CarExample.Vehicle [[Examples.BadDesign.CarExample.Vehicle-diagram-detailed-grouped-per-namespace.svg]] #yellow {
      + db: Examples.BadDesign.DB
==
      + setSpeed(<font color="6060BB">speed:int</font>): <font color="BB6060">void</font>
      + getSpeed(<font color="6060BB"></font>): <font color="BB6060">int</font>
    }
'Compared namespace Examples.BadDesign.CarExample [[Examples.BadDesign.CarExample-diagram-detailed-grouped-per-namespace.svg]] { with last element of     }
' Closing all previous_sub_namespace_list namespace None because file analysis is finished.
' Closing namespace CarExample
}
' Closing namespace BadDesign
}
' Closing namespace Examples
}
 ' *************************************** 
 ' *************************************** 
 ' *************************************** 
' Class relations extracted from namespace:
' Examples.BadDesign
' Class relations extracted from namespace:
' Examples.BadDesign.CarExample
Examples.BadDesign.CarExample.Vehicle *-[#10BB10]- Examples.BadDesign.DB 
@enduml