@startuml
skinparam linetype ortho
title <size:20>Examples.BasicExample.SideExample **simplified** and **grouped per namespace**</size>
note "Your are analyzing:\nExamples.BasicExample.SideExample **simplified** and **grouped per namespace**\n\n==Filter==\nYou can click either the namespaces \nor class names for filtering them and their\ndirect dependencies.\n\n==Select other==\n* Examples.BasicExample.SideExample **detailed** and **grouped per namespace**:\n   [[Examples.BasicExample.SideExample-diagram-detailed-grouped-per-namespace.svg]]\n* Full diagram **simplified** and **grouped per namespace**:\n   [[full-diagram-simplified-grouped-per-namespace.svg]]\n* Home:\n   [[index.html]]" as FloatingNote
namespace Examples [[Examples-diagram-simplified-grouped-per-namespace.svg]] {
namespace Examples.BasicExample [[Examples.BasicExample-diagram-simplified-grouped-per-namespace.svg]] {
  class Examples.BasicExample.Useless [[Examples.BasicExample.Useless-diagram-simplified-grouped-per-namespace.svg]]  {
  }
'Compared namespace Examples.BasicExample [[Examples.BasicExample-diagram-simplified-grouped-per-namespace.svg]] { with last element of   }
' Closing all previous_sub_namespace_list namespace None because file analysis is finished.
' Closing namespace BasicExample
}
' Closing namespace Examples
}
namespace Examples [[Examples-diagram-simplified-grouped-per-namespace.svg]] {
namespace Examples.BasicExample [[Examples.BasicExample-diagram-simplified-grouped-per-namespace.svg]] {
namespace Examples.BasicExample.SideExample [[Examples.BasicExample.SideExample-diagram-simplified-grouped-per-namespace.svg]] {
    class Examples.BasicExample.SideExample.SideExample [[Examples.BasicExample.SideExample.SideExample-diagram-simplified-grouped-per-namespace.svg]] #yellow {
    }
    class Examples.BasicExample.SideExample.SideTestEnum [[Examples.BasicExample.SideExample.SideTestEnum-diagram-simplified-grouped-per-namespace.svg]] #yellow {
    }
'Compared namespace Examples.BasicExample.SideExample [[Examples.BasicExample.SideExample-diagram-simplified-grouped-per-namespace.svg]] { with last element of     }
' Closing all previous_sub_namespace_list namespace None because file analysis is finished.
' Closing namespace SideExample
}
' Closing namespace BasicExample
}
' Closing namespace Examples
}
 ' *************************************** 
 ' *************************************** 
 ' *************************************** 
' Class relations extracted from namespace:
' Examples.BasicExample
Examples.BasicExample.Useless -[#909090]-> Examples.BasicExample.SideExample.SideTestEnum  : uses 
' Class relations extracted from namespace:
' Examples.BasicExample.SideExample
Examples.BasicExample.SideExample.SideExample .[#6060BB].> Examples.BasicExample.SideExample.SideTestEnum  : uses 
@enduml