@startuml
title <size:20>Example.ClassExample_DOT_InnerClassExample **detailed** and **grouped per namespace**</size>
note "Your are analyzing:\nExample.ClassExample_DOT_InnerClassExample **detailed** and **grouped per namespace**\n\n==Filter==\nYou can click either the namespaces \nor class names for filtering them and their\ndirect dependencies.\n\n==Select other==\n* Example.ClassExample_DOT_InnerClassExample **simplified** and **grouped per namespace**:\n   [[Example.ClassExample_DOT_InnerClassExample-diagram-simplified-grouped-per-namespace.svg]]\n* Full diagram **detailed** and **grouped per namespace**:\n   [[full-diagram-detailed-grouped-per-namespace.svg]]\n* Home:\n   [[index.html]]" as FloatingNote
namespace Example [[Example-diagram-detailed-grouped-per-namespace.svg]] {
class Example.ClassExample_DOT_InnerClassExample [[Example.ClassExample_DOT_InnerClassExample-diagram-detailed-grouped-per-namespace.svg]] #yellow {
}
class Example.ClassExample_DOT_InnerClassExample_DOT_classInMethodExample [[Example.ClassExample_DOT_InnerClassExample_DOT_classInMethodExample-diagram-detailed-grouped-per-namespace.svg]]  {
}
class Example.ClassExample [[Example.ClassExample-diagram-detailed-grouped-per-namespace.svg]]  {
  + memberVarUseless: Example.Useless
  + memberVarEnumTest: EnumTest
==
  + example(<font color="6060BB">example:Example.Useless, example:Example.Useless</font>)
  - <font color="909090">example.localVarBaseExample: Example.BaseExample</font>
--
  + getExample(<font color="6060BB"></font>)
  + exampleAbstract(<font color="6060BB">exampleAbstract:Example.Useless, exampleAbstract:Example.Useless</font>)
}
'Compared namespace Example [[Example-diagram-detailed-grouped-per-namespace.svg]] { with last element of }
' Closing all previous_sub_namespace_list namespace None because file analysis is finished.
' Closing namespace Example
}
 ' *************************************** 
 ' *************************************** 
 ' *************************************** 
' Class relations extracted from namespace:
' Example
Example.ClassExample_DOT_InnerClassExample +-[#10BBBB]- Example.ClassExample_DOT_InnerClassExample_DOT_classInMethodExample 
Example.ClassExample +-[#10BBBB]- Example.ClassExample_DOT_InnerClassExample 
@enduml