@startuml
skinparam linetype ortho
title <size:20>Examples.BetterDesign.FakeEntitities.Invoice **detailed** and **grouped per namespace**</size>
note "Your are analyzing:\nExamples.BetterDesign.FakeEntitities.Invoice **detailed** and **grouped per namespace**\n\n==Filter==\nYou can click either the namespaces \nor class names for filtering them and their\ndirect dependencies.\n\n==Select other==\n* Examples.BetterDesign.FakeEntitities.Invoice **simplified** and **grouped per namespace**:\n   [[Examples.BetterDesign.FakeEntitities.Invoice-diagram-simplified-grouped-per-namespace.svg]]\n* Full diagram **detailed** and **grouped per namespace**:\n   [[full-diagram-detailed-grouped-per-namespace.svg]]\n* Home:\n   [[index.html]]" as FloatingNote
namespace Examples [[Examples-diagram-detailed-grouped-per-namespace.svg]] {
namespace Examples.BetterDesign [[Examples.BetterDesign-diagram-detailed-grouped-per-namespace.svg]] {
  class Examples.BetterDesign.DBCustomers [[Examples.BetterDesign.DBCustomers-diagram-detailed-grouped-per-namespace.svg]]  {
    + getCustomer(<font color="6060BB">i:Examples.BetterDesign.FakeEntitities.Invoice</font>): <font color="BB6060">Examples.BetterDesign.FakeEntitities.Customer</font>
    + getItem(<font color="6060BB">c:Examples.BetterDesign.FakeEntitities.Complaints</font>): <font color="BB6060">Examples.BetterDesign.FakeEntitities.Item</font>
    + getInvoice(<font color="6060BB">c:Examples.BetterDesign.FakeEntitities.Customer</font>): <font color="BB6060">Examples.BetterDesign.FakeEntitities.Invoice</font>
    + getComplaints(<font color="6060BB">c:Examples.BetterDesign.FakeEntitities.Customer</font>): <font color="BB6060">Examples.BetterDesign.FakeEntitities.Complaints</font>
    + getUser(<font color="6060BB">item:Examples.BetterDesign.FakeEntitities.Item</font>): <font color="BB6060">Examples.BetterDesign.FakeEntitities.User</font>
    + getCustomer(<font color="6060BB">complaint:Examples.BetterDesign.FakeEntitities.Complaints</font>): <font color="BB6060">Examples.BetterDesign.FakeEntitities.Customer</font>
    + getItem(<font color="6060BB">user:Examples.BetterDesign.FakeEntitities.User</font>): <font color="BB6060">Examples.BetterDesign.FakeEntitities.Item</font>
    + getComplaints(<font color="6060BB">item:Examples.BetterDesign.FakeEntitities.Item</font>): <font color="BB6060">Examples.BetterDesign.FakeEntitities.Complaints</font>
    + getFirstUser(<font color="6060BB"></font>): <font color="BB6060">Examples.BetterDesign.FakeEntitities.User</font>
    + getFirstItem(<font color="6060BB"></font>): <font color="BB6060">Examples.BetterDesign.FakeEntitities.Item</font>
    + getFirstInvoice(<font color="6060BB"></font>): <font color="BB6060">Examples.BetterDesign.FakeEntitities.Invoice</font>
    + getFirstComplaints(<font color="6060BB"></font>): <font color="BB6060">Examples.BetterDesign.FakeEntitities.Complaints</font>
  }
'Compared namespace Examples.BetterDesign [[Examples.BetterDesign-diagram-detailed-grouped-per-namespace.svg]] { with last element of   }
' Closing all previous_sub_namespace_list namespace None because file analysis is finished.
' Closing namespace BetterDesign
}
' Closing namespace Examples
}
namespace Examples [[Examples-diagram-detailed-grouped-per-namespace.svg]] {
namespace Examples.BetterDesign [[Examples.BetterDesign-diagram-detailed-grouped-per-namespace.svg]] {
namespace Examples.BetterDesign.FakeEntitities [[Examples.BetterDesign.FakeEntitities-diagram-detailed-grouped-per-namespace.svg]] {
    class Examples.BetterDesign.FakeEntitities.Invoice [[Examples.BetterDesign.FakeEntitities.Invoice-diagram-detailed-grouped-per-namespace.svg]] #yellow {
    }
'Compared namespace Examples.BetterDesign.FakeEntitities [[Examples.BetterDesign.FakeEntitities-diagram-detailed-grouped-per-namespace.svg]] { with last element of     }
' Closing all previous_sub_namespace_list namespace None because file analysis is finished.
' Closing namespace FakeEntitities
}
' Closing namespace BetterDesign
}
' Closing namespace Examples
}
 ' *************************************** 
 ' *************************************** 
 ' *************************************** 
' Class relations extracted from namespace:
' Examples.BetterDesign
Examples.BetterDesign.DBCustomers .[#6060BB].> Examples.BetterDesign.FakeEntitities.Invoice  : uses 
' Class relations extracted from namespace:
' Examples.BetterDesign.FakeEntitities
@enduml