@startuml
skinparam linetype ortho
title <size:20>Examples.BadDesign.FakeEntitities.Item **simplified** </size>
note "Your are analyzing:\nExamples.BadDesign.FakeEntitities.Item **simplified** \n\n==Filter==\nYou can click either the namespaces \nor class names for filtering them and their\ndirect dependencies.\n\n==Select other==\n* Examples.BadDesign.FakeEntitities.Item **detailed** :\n   [[Examples.BadDesign.FakeEntitities.Item-diagram-detailed.svg]]\n* Full diagram **simplified** and **grouped per namespace**:\n   [[full-diagram-simplified-grouped-per-namespace.svg]]\n* Home:\n   [[index.html]]" as FloatingNote
  class Examples.BadDesign.DB [[Examples.BadDesign.DB-diagram-simplified.svg]]  {
  }
    class Examples.BadDesign.FakeEntitities.Item [[Examples.BadDesign.FakeEntitities.Item-diagram-simplified.svg]] #yellow {
    }
 ' *************************************** 
 ' *************************************** 
 ' *************************************** 
' Class relations extracted from namespace:
' Examples.BadDesign
Examples.BadDesign.DB .[#6060BB].> Examples.BadDesign.FakeEntitities.Item  : uses 
' Class relations extracted from namespace:
' Examples.BadDesign.FakeEntitities
@enduml