@startuml
title <size:20>Example.BaseExample **simplified** and **grouped per namespace**</size>
note "Your are analyzing:\nExample.BaseExample **simplified** and **grouped per namespace**\n\n==Filter==\nYou can click either the namespaces \nor class names for filtering them and their\ndirect dependencies.\n\n==Select other==\n* Example.BaseExample **detailed** and **grouped per namespace**:\n   [[Example.BaseExample-diagram-detailed-grouped-per-namespace.svg]]\n* Full diagram **simplified** and **grouped per namespace**:\n   [[full-diagram-simplified-grouped-per-namespace.svg]]\n* Home:\n   [[index.html]]" as FloatingNote
namespace Example [[Example-diagram-simplified-grouped-per-namespace.svg]] {
class Example.BaseExample [[Example.BaseExample-diagram-simplified-grouped-per-namespace.svg]] #yellow {
}
abstract class Example.AbstractBaseExample [[Example.AbstractBaseExample-diagram-simplified-grouped-per-namespace.svg]]  {
}
class Example.Useless [[Example.Useless-diagram-simplified-grouped-per-namespace.svg]]  {
}
class Example.BaseExample_DOT_EnumTest [[Example.BaseExample_DOT_EnumTest-diagram-simplified-grouped-per-namespace.svg]]  {
}
class Example.ClassExample [[Example.ClassExample-diagram-simplified-grouped-per-namespace.svg]]  {
}
'Compared namespace Example [[Example-diagram-simplified-grouped-per-namespace.svg]] { with last element of }
' Closing all previous_sub_namespace_list namespace None because file analysis is finished.
' Closing namespace Example
}
 ' *************************************** 
 ' *************************************** 
 ' *************************************** 
' Class relations extracted from namespace:
' Example
Example.AbstractBaseExample <|-[#red]- Example.BaseExample
Example.BaseExample +-[#10BBBB]- Example.BaseExample_DOT_EnumTest 
Example.BaseExample .[#6060BB].> Example.Useless  : uses 
Example.AbstractBaseExample .[#6060BB].> Example.Useless  : uses 
Example.BaseExample <|-[#red]- Example.ClassExample
Example.ClassExample .[#6060BB].> Example.Useless  : uses 
Example.ClassExample -[#909090]-> Example.BaseExample  : uses 
@enduml