@startuml
skinparam linetype ortho
title <size:20>Examples.BasicExample.BaseExample.EnumTest **simplified** </size>
note "Your are analyzing:\nExamples.BasicExample.BaseExample.EnumTest **simplified** \n\n==Filter==\nYou can click either the namespaces \nor class names for filtering them and their\ndirect dependencies.\n\n==Select other==\n* Examples.BasicExample.BaseExample.EnumTest **detailed** :\n   [[Examples.BasicExample.BaseExample.EnumTest-diagram-detailed.svg]]\n* Full diagram **simplified** and **grouped per namespace**:\n   [[full-diagram-simplified-grouped-per-namespace.svg]]\n* Home:\n   [[index.html]]" as FloatingNote
  class Examples.BasicExample.BaseExample_DOT_EnumTest [[Examples.BasicExample.BaseExample.EnumTest-diagram-simplified.svg]] #yellow {
  }
  class Examples.BasicExample.BaseExample [[Examples.BasicExample.BaseExample-diagram-simplified.svg]]  {
  }
  class Examples.BasicExample.ClassExample [[Examples.BasicExample.ClassExample-diagram-simplified.svg]]  {
  }
 ' *************************************** 
 ' *************************************** 
 ' *************************************** 
' Class relations extracted from namespace:
' Examples.BasicExample
Examples.BasicExample.BaseExample +-[#10BBBB]- Examples.BasicExample.BaseExample_DOT_EnumTest 
Examples.BasicExample.BaseExample <|-[#red]- Examples.BasicExample.ClassExample
Examples.BasicExample.ClassExample *-[#10BB10]- Examples.BasicExample.BaseExample.EnumTest 
Examples.BasicExample.ClassExample -[#909090]-> Examples.BasicExample.BaseExample  : uses 
@enduml