@startuml
title <size:20>Example.AbstractBaseExample **simplified** </size>
note "Your are analyzing:\nExample.AbstractBaseExample **simplified** \n\n==Filter==\nYou can click either the namespaces \nor class names for filtering them and their\ndirect dependencies.\n\n==Select other==\n* Example.AbstractBaseExample **detailed** :\n   [[Example.AbstractBaseExample-diagram-detailed.svg]]\n* Full diagram **simplified** and **grouped per namespace**:\n   [[full-diagram-simplified-grouped-per-namespace.svg]]\n* Home:\n   [[index.html]]" as FloatingNote
abstract class Example.AbstractBaseExample [[Example.AbstractBaseExample-diagram-simplified.svg]] #yellow {
}
class Example.Useless [[Example.Useless-diagram-simplified.svg]]  {
}
class Example.BaseExample [[Example.BaseExample-diagram-simplified.svg]]  {
}
 ' *************************************** 
 ' *************************************** 
 ' *************************************** 
' Class relations extracted from namespace:
' Example
Example.AbstractBaseExample .[#6060BB].> Example.Useless  : uses 
Example.AbstractBaseExample <|-[#red]- Example.BaseExample
Example.BaseExample .[#6060BB].> Example.Useless  : uses 
@enduml