@startuml
skinparam linetype ortho
title <size:20>ForStmt **simplified** and **grouped per namespace**</size>
note "Your are analyzing:\nForStmt **simplified** and **grouped per namespace**\n\n==Filter==\nYou can click either the namespaces \nor class names for filtering them and their\ndirect dependencies.\n\n==Select other==\n* ForStmt **detailed** and **grouped per namespace**:\n   [[ForStmt-diagram-detailed-grouped-per-namespace.svg]]\n* Full diagram **simplified** and **grouped per namespace**:\n   [[full-diagram-simplified-grouped-per-namespace.svg]]\n* Home:\n   [[index.html]]" as FloatingNote
class ForStmt [[ForStmt-diagram-simplified-grouped-per-namespace.svg]] #yellow {
}
' Closing all previous_sub_namespace_list namespace None because file analysis is finished.
namespace preadapter [[preadapter-diagram-simplified-grouped-per-namespace.svg]] {
namespace preadapter.domain [[preadapter.domain-diagram-simplified-grouped-per-namespace.svg]] {
  class preadapter.domain.ASTVisitorDebug [[preadapter.domain.ASTVisitorDebug-diagram-simplified-grouped-per-namespace.svg]]  {
  }
'Compared namespace preadapter.domain [[preadapter.domain-diagram-simplified-grouped-per-namespace.svg]] { with last element of   }
' Closing all previous_sub_namespace_list namespace None because file analysis is finished.
' Closing namespace domain
}
' Closing namespace preadapter
}
 ' *************************************** 
 ' *************************************** 
 ' *************************************** 
' Class relations extracted from namespace:
' 
' Class relations extracted from namespace:
' preadapter.domain
preadapter.domain.ASTVisitorDebug .[#6060BB].> ForStmt  : uses 
@enduml