@startuml
title <size:20>n_DOT_getTypeAsString_BRQTO__BRQTC **simplified** </size>
note "Your are analyzing:\nn_DOT_getTypeAsString_BRQTO__BRQTC **simplified** \n\n==Filter==\nYou can click either the namespaces \nor class names for filtering them and their\ndirect dependencies.\n\n==Select other==\n* n_DOT_getTypeAsString_BRQTO__BRQTC **detailed** :\n   [[n_DOT_getTypeAsString_BRQTO__BRQTC-diagram-detailed.svg]]\n* Full diagram **simplified** and **grouped per namespace**:\n   [[full-diagram-simplified-grouped-per-namespace.svg]]\n* Home:\n   [[index.html]]" as FloatingNote
class n_DOT_getTypeAsString_BRQTO__BRQTC [[n_DOT_getTypeAsString_BRQTO__BRQTC-diagram-simplified.svg]] #yellow {
}
  class preadapter.domain.ASTVisitor [[preadapter.domain.ASTVisitor-diagram-simplified.svg]]  {
  }
 ' *************************************** 
 ' *************************************** 
 ' *************************************** 
' Class relations extracted from namespace:
' 
' Class relations extracted from namespace:
' preadapter.domain
preadapter.domain.ASTVisitor -[#909090]-> n_DOT_getTypeAsString_BRQTO__BRQTC  : uses 
@enduml