@startuml
title <size:20>preadapter.domain.Datastructure **simplified** </size>
note "Your are analyzing:\npreadapter.domain.Datastructure **simplified** \n\n==Filter==\nYou can click either the namespaces \nor class names for filtering them and their\ndirect dependencies.\n\n==Select other==\n* preadapter.domain.Datastructure **detailed** :\n   [[preadapter.domain.Datastructure-diagram-detailed.svg]]\n* Full diagram **simplified** and **grouped per namespace**:\n   [[full-diagram-simplified-grouped-per-namespace.svg]]\n* Home:\n   [[index.html]]" as FloatingNote
class list_BRQTO_Variable_BRQTC [[list_BRQTO_Variable_BRQTC-diagram-simplified.svg]] #MintCream {
}
class Variable [[Variable-diagram-simplified.svg]] #MintCream {
}
class Method [[Method-diagram-simplified.svg]] #MintCream {
}
class SubDataStructure [[SubDataStructure-diagram-simplified.svg]] #MintCream {
}
class list_BRQTO_String_BRQTC [[list_BRQTO_String_BRQTC-diagram-simplified.svg]] #MintCream {
}
class String_BRQTO__BRQTC [[String_BRQTO__BRQTC-diagram-simplified.svg]] #MintCream {
}
class preadapter.Logger [[preadapter.Logger-diagram-simplified.svg]]  {
}
  class preadapter.domain.Datastructure [[preadapter.domain.Datastructure-diagram-simplified.svg]] #yellow {
  }
  class preadapter.domain.Datastructure_DOT_Method [[preadapter.domain.Datastructure_DOT_Method-diagram-simplified.svg]]  {
  }
  class preadapter.domain.Datastructure_DOT_Static [[preadapter.domain.Datastructure_DOT_Static-diagram-simplified.svg]]  {
  }
  class preadapter.domain.Datastructure_DOT_Variable [[preadapter.domain.Datastructure_DOT_Variable-diagram-simplified.svg]]  {
  }
  class preadapter.domain.Datastructure_DOT_SubDataStructure [[preadapter.domain.Datastructure_DOT_SubDataStructure-diagram-simplified.svg]]  {
  }
  class preadapter.domain.ASTVisitor [[preadapter.domain.ASTVisitor-diagram-simplified.svg]]  {
  }
  class preadapter.infrastructure.CreateYML [[preadapter.infrastructure.CreateYML-diagram-simplified.svg]]  {
  }
  class preadapter.service.AnalyzeAST [[preadapter.service.AnalyzeAST-diagram-simplified.svg]]  {
  }
 ' *************************************** 
 ' *************************************** 
 ' *************************************** 
' Class relations extracted from namespace:
' 
' Class relations extracted from namespace:
' preadapter
preadapter.Logger -[#909090]-> String_BRQTO__BRQTC  : uses 
' Class relations extracted from namespace:
' preadapter.domain
preadapter.domain.Datastructure +-[#10BBBB]- preadapter.domain.Datastructure_DOT_Method 
preadapter.domain.Datastructure +-[#10BBBB]- preadapter.domain.Datastructure_DOT_Static 
preadapter.domain.Datastructure +-[#10BBBB]- preadapter.domain.Datastructure_DOT_Variable 
preadapter.domain.Datastructure +-[#10BBBB]- preadapter.domain.Datastructure_DOT_SubDataStructure 
preadapter.domain.Datastructure .[#6060BB].> preadapter.Logger  : uses 
preadapter.domain.Datastructure -[#909090]-> list_BRQTO_Variable_BRQTC  : uses 
preadapter.domain.Datastructure -[#909090]-> Variable  : uses 
preadapter.domain.Datastructure -[#909090]-> Method  : uses 
preadapter.domain.Datastructure -[#909090]-> SubDataStructure  : uses 
preadapter.domain.Datastructure .[#6060BB].> SubDataStructure  : uses 
preadapter.domain.Datastructure .[#6060BB].> list_BRQTO_String_BRQTC  : uses 
preadapter.domain.Datastructure -[#909090]-> list_BRQTO_String_BRQTC  : uses 
preadapter.domain.Datastructure -[#909090]-> String_BRQTO__BRQTC  : uses 
preadapter.domain.ASTVisitor .[#6060BB].> preadapter.Logger  : uses 
preadapter.domain.ASTVisitor .[#6060BB].> preadapter.domain.Datastructure  : uses 
preadapter.domain.ASTVisitor -[#909090]-> preadapter.domain.Datastructure_DOT_SubDataStructure  : uses 
preadapter.domain.ASTVisitor -[#909090]-> preadapter.domain.Datastructure_DOT_Method  : uses 
preadapter.domain.ASTVisitor .[#6060BB].> String_BRQTO__BRQTC  : uses 
' Class relations extracted from namespace:
' preadapter.infrastructure
preadapter.infrastructure.CreateYML .[#6060BB].> list_BRQTO_String_BRQTC  : uses 
preadapter.infrastructure.CreateYML .[#6060BB].> preadapter.domain.Datastructure  : uses 
preadapter.infrastructure.CreateYML .[#6060BB].> preadapter.Logger  : uses 
preadapter.infrastructure.CreateYML -[#909090]-> preadapter.domain.Datastructure_DOT_SubDataStructure  : uses 
' Class relations extracted from namespace:
' preadapter.service
preadapter.service.AnalyzeAST .[#6060BB].> preadapter.Logger  : uses 
preadapter.service.AnalyzeAST -[#909090]-> preadapter.domain.Datastructure  : uses 
preadapter.service.AnalyzeAST -[#909090]-> list_BRQTO_String_BRQTC  : uses 
@enduml