@startuml
skinparam linetype ortho
title <size:20>preadapter.service.RecursiveFileProcessor **detailed** </size>
note "Your are analyzing:\npreadapter.service.RecursiveFileProcessor **detailed** \n\n==Filter==\nYou can click either the namespaces \nor class names for filtering them and their\ndirect dependencies.\n\n==Select other==\n* preadapter.service.RecursiveFileProcessor **simplified** :\n   [[preadapter.service.RecursiveFileProcessor-diagram-simplified.svg]]\n* Full diagram **detailed** and **grouped per namespace**:\n   [[full-diagram-detailed-grouped-per-namespace.svg]]\n* Home:\n   [[index.html]]" as FloatingNote
class Path [[Path-diagram-detailed.svg]] #MintCream {
}
  class preadapter.service.RecursiveFileProcessor [[preadapter.service.RecursiveFileProcessor-diagram-detailed.svg]] #yellow {
    + SearchPath(<font color="6060BB">path:String</font>): <font color="BB6060">list[String]</font>
    - <font color="909090">SearchPath.fileList: list[String]</font>
--
    - ProcessDirectory(<font color="6060BB">sourceDirectory:String, fileList:list[String]</font>): <font color="BB6060">void</font>
    - <font color="909090">ProcessDirectory.stream: DirectoryStream[Path]</font>
    - <font color="909090">ProcessDirectory.isDirectory: boolean</font>
    - <font color="909090">ProcessDirectory.path: Path</font>
--
  }
 ' *************************************** 
 ' *************************************** 
 ' *************************************** 
' Class relations extracted from namespace:
' 
' Class relations extracted from namespace:
' preadapter.service
preadapter.service.RecursiveFileProcessor -[#909090]-> Path  : uses 
@enduml