@startuml
skinparam linetype ortho
title <size:20>preadapter.infrastructure **simplified** and **grouped per namespace**</size>
note "Your are analyzing:\npreadapter.infrastructure **simplified** and **grouped per namespace**\n\n==Filter==\nYou can click either the namespaces \nor class names for filtering them and their\ndirect dependencies.\n\n==Select other==\n* preadapter.infrastructure **detailed** and **grouped per namespace**:\n   [[preadapter.infrastructure-diagram-detailed-grouped-per-namespace.svg]]\n* Full diagram **simplified** and **grouped per namespace**:\n   [[full-diagram-simplified-grouped-per-namespace.svg]]\n* Home:\n   [[index.html]]" as FloatingNote
class DumperOptions.FlowStyle [[DumperOptions.FlowStyle-diagram-simplified-grouped-per-namespace.svg]] #MintCream {
}
class Mark [[Mark-diagram-simplified-grouped-per-namespace.svg]] #MintCream {
}
class dictpingNode [[dictpingNode-diagram-simplified-grouped-per-namespace.svg]] #MintCream {
}
class SequenceNode [[SequenceNode-diagram-simplified-grouped-per-namespace.svg]] #MintCream {
}
class Yaml [[Yaml-diagram-simplified-grouped-per-namespace.svg]] #MintCream {
}
class PrintWriter [[PrintWriter-diagram-simplified-grouped-per-namespace.svg]] #MintCream {
}
' Closing all previous_sub_namespace_list namespace None because file analysis is finished.
namespace preadapter [[preadapter-diagram-simplified-grouped-per-namespace.svg]] {
class preadapter.Logger [[preadapter.Logger-diagram-simplified-grouped-per-namespace.svg]]  {
}
'Compared namespace preadapter [[preadapter-diagram-simplified-grouped-per-namespace.svg]] { with last element of }
' Closing all previous_sub_namespace_list namespace None because file analysis is finished.
' Closing namespace preadapter
}
namespace preadapter [[preadapter-diagram-simplified-grouped-per-namespace.svg]] {
namespace preadapter.domain [[preadapter.domain-diagram-simplified-grouped-per-namespace.svg]] {
  class preadapter.domain.Datastructure [[preadapter.domain.Datastructure-diagram-simplified-grouped-per-namespace.svg]]  {
  }
'Compared namespace preadapter.domain [[preadapter.domain-diagram-simplified-grouped-per-namespace.svg]] { with last element of   }
' Closing all previous_sub_namespace_list namespace None because file analysis is finished.
' Closing namespace domain
}
' Closing namespace preadapter
}
namespace preadapter [[preadapter-diagram-simplified-grouped-per-namespace.svg]] {
namespace preadapter.infrastructure [[preadapter.infrastructure-diagram-simplified-grouped-per-namespace.svg]] {
  class preadapter.infrastructure.CreateYML [[preadapter.infrastructure.CreateYML-diagram-simplified-grouped-per-namespace.svg]] #yellow {
  }
'Compared namespace preadapter.infrastructure [[preadapter.infrastructure-diagram-simplified-grouped-per-namespace.svg]] { with last element of   }
' Closing all previous_sub_namespace_list namespace None because file analysis is finished.
' Closing namespace infrastructure
}
' Closing namespace preadapter
}
 ' *************************************** 
 ' *************************************** 
 ' *************************************** 
' Class relations extracted from namespace:
' 
' Class relations extracted from namespace:
' preadapter
' Class relations extracted from namespace:
' preadapter.domain
preadapter.domain.Datastructure *-[#10BB10]- preadapter.Logger 
' Class relations extracted from namespace:
' preadapter.infrastructure
preadapter.infrastructure.CreateYML *-[#10BB10]- DumperOptions.FlowStyle 
preadapter.infrastructure.CreateYML *-[#10BB10]- Mark 
preadapter.infrastructure.CreateYML .[#6060BB].> dictpingNode  : uses 
preadapter.infrastructure.CreateYML .[#6060BB].> SequenceNode  : uses 
preadapter.infrastructure.CreateYML -[#909090]-> SequenceNode  : uses 
preadapter.infrastructure.CreateYML .[#6060BB].> preadapter.domain.Datastructure  : uses 
preadapter.infrastructure.CreateYML .[#6060BB].> preadapter.Logger  : uses 
preadapter.infrastructure.CreateYML -[#909090]-> Yaml  : uses 
preadapter.infrastructure.CreateYML -[#909090]-> PrintWriter  : uses 
@enduml