@startuml
skinparam linetype ortho
title <size:20>preadapter.service.RecursiveFileProcessor **simplified** </size>
note "Your are analyzing:\npreadapter.service.RecursiveFileProcessor **simplified** \n\n==Filter==\nYou can click either the namespaces \nor class names for filtering them and their\ndirect dependencies.\n\n==Select other==\n* preadapter.service.RecursiveFileProcessor **detailed** :\n   [[preadapter.service.RecursiveFileProcessor-diagram-detailed.svg]]\n* Full diagram **simplified** and **grouped per namespace**:\n   [[full-diagram-simplified-grouped-per-namespace.svg]]\n* Home:\n   [[index.html]]" as FloatingNote
class Path [[Path-diagram-simplified.svg]] #MintCream {
}
  class preadapter.service.RecursiveFileProcessor [[preadapter.service.RecursiveFileProcessor-diagram-simplified.svg]] #yellow {
  }
 ' *************************************** 
 ' *************************************** 
 ' *************************************** 
' Class relations extracted from namespace:
' 
' Class relations extracted from namespace:
' preadapter.service
preadapter.service.RecursiveFileProcessor -[#909090]-> Path  : uses 
@enduml