@startuml
skinparam linetype ortho
title <size:20>preadapter.service.AnalyzeAST **simplified** and **grouped per namespace**</size>
note "Your are analyzing:\npreadapter.service.AnalyzeAST **simplified** and **grouped per namespace**\n\n==Filter==\nYou can click either the namespaces \nor class names for filtering them and their\ndirect dependencies.\n\n==Select other==\n* preadapter.service.AnalyzeAST **detailed** and **grouped per namespace**:\n   [[preadapter.service.AnalyzeAST-diagram-detailed-grouped-per-namespace.svg]]\n* Full diagram **simplified** and **grouped per namespace**:\n   [[full-diagram-simplified-grouped-per-namespace.svg]]\n* Home:\n   [[index.html]]" as FloatingNote
class CompilationUnit [[CompilationUnit-diagram-simplified-grouped-per-namespace.svg]] #MintCream {
}
' Closing all previous_sub_namespace_list namespace None because file analysis is finished.
namespace preadapter [[preadapter-diagram-simplified-grouped-per-namespace.svg]] {
class preadapter.Logger [[preadapter.Logger-diagram-simplified-grouped-per-namespace.svg]]  {
}
'Compared namespace preadapter [[preadapter-diagram-simplified-grouped-per-namespace.svg]] { with last element of }
' Closing all previous_sub_namespace_list namespace None because file analysis is finished.
' Closing namespace preadapter
}
namespace preadapter [[preadapter-diagram-simplified-grouped-per-namespace.svg]] {
namespace preadapter.domain [[preadapter.domain-diagram-simplified-grouped-per-namespace.svg]] {
  class preadapter.domain.Datastructure [[preadapter.domain.Datastructure-diagram-simplified-grouped-per-namespace.svg]]  {
  }
'Compared namespace preadapter.domain [[preadapter.domain-diagram-simplified-grouped-per-namespace.svg]] { with last element of   }
' Closing all previous_sub_namespace_list namespace None because file analysis is finished.
' Closing namespace domain
}
' Closing namespace preadapter
}
namespace preadapter [[preadapter-diagram-simplified-grouped-per-namespace.svg]] {
namespace preadapter.service [[preadapter.service-diagram-simplified-grouped-per-namespace.svg]] {
  class preadapter.service.AnalyzeAST [[preadapter.service.AnalyzeAST-diagram-simplified-grouped-per-namespace.svg]] #yellow {
  }
'Compared namespace preadapter.service [[preadapter.service-diagram-simplified-grouped-per-namespace.svg]] { with last element of   }
' Closing all previous_sub_namespace_list namespace None because file analysis is finished.
' Closing namespace service
}
' Closing namespace preadapter
}
 ' *************************************** 
 ' *************************************** 
 ' *************************************** 
' Class relations extracted from namespace:
' 
' Class relations extracted from namespace:
' preadapter
' Class relations extracted from namespace:
' preadapter.domain
preadapter.domain.Datastructure *-[#10BB10]- preadapter.Logger 
' Class relations extracted from namespace:
' preadapter.service
preadapter.service.AnalyzeAST .[#6060BB].> preadapter.Logger  : uses 
preadapter.service.AnalyzeAST -[#909090]-> preadapter.domain.Datastructure  : uses 
preadapter.service.AnalyzeAST -[#909090]-> CompilationUnit  : uses 
@enduml