@startuml
title <size:20>preadapter.domain.ASTVisitor **simplified** and **grouped per namespace**</size>
note "Your are analyzing:\npreadapter.domain.ASTVisitor **simplified** and **grouped per namespace**\n\n==Filter==\nYou can click either the namespaces \nor class names for filtering them and their\ndirect dependencies.\n\n==Select other==\n* preadapter.domain.ASTVisitor **detailed** and **grouped per namespace**:\n   [[preadapter.domain.ASTVisitor-diagram-detailed-grouped-per-namespace.svg]]\n* Full diagram **simplified** and **grouped per namespace**:\n   [[full-diagram-simplified-grouped-per-namespace.svg]]\n* Home:\n   [[index.html]]" as FloatingNote
class VoidVisitorAdapter_BRQTO_Void_BRQTC [[VoidVisitorAdapter_BRQTO_Void_BRQTC-diagram-simplified-grouped-per-namespace.svg]] #MintCream {
}
class HandleDeepness [[HandleDeepness-diagram-simplified-grouped-per-namespace.svg]] #MintCream {
}
class ClassOrInterfaceDeclaration [[ClassOrInterfaceDeclaration-diagram-simplified-grouped-per-namespace.svg]] #MintCream {
}
class MethodDeclaration [[MethodDeclaration-diagram-simplified-grouped-per-namespace.svg]] #MintCream {
}
class Void [[Void-diagram-simplified-grouped-per-namespace.svg]] #MintCream {
}
class list_BRQTO_tuple_BRQTO_String_COMMA_String_COMMA_String_BRQTC_BRQTC [[list_BRQTO_tuple_BRQTO_String_COMMA_String_COMMA_String_BRQTC_BRQTC-diagram-simplified-grouped-per-namespace.svg]] #MintCream {
}
class Optional_DOT_empty [[Optional_DOT_empty-diagram-simplified-grouped-per-namespace.svg]] #MintCream {
}
class VariableDeclarator [[VariableDeclarator-diagram-simplified-grouped-per-namespace.svg]] #MintCream {
}
class n_DOT_getNameAsString_BRQTO__BRQTC [[n_DOT_getNameAsString_BRQTO__BRQTC-diagram-simplified-grouped-per-namespace.svg]] #MintCream {
}
class n_DOT_getTypeAsString_BRQTO__BRQTC [[n_DOT_getTypeAsString_BRQTO__BRQTC-diagram-simplified-grouped-per-namespace.svg]] #MintCream {
}
class n_DOT_getInitializer_BRQTO__BRQTC_DOT_toString_BRQTO__BRQTC [[n_DOT_getInitializer_BRQTO__BRQTC_DOT_toString_BRQTO__BRQTC-diagram-simplified-grouped-per-namespace.svg]] #MintCream {
}
class FieldDeclaration [[FieldDeclaration-diagram-simplified-grouped-per-namespace.svg]] #MintCream {
}
class PackageDeclaration [[PackageDeclaration-diagram-simplified-grouped-per-namespace.svg]] #MintCream {
}
class ImportDeclaration [[ImportDeclaration-diagram-simplified-grouped-per-namespace.svg]] #MintCream {
}
class EnumConstantDeclaration [[EnumConstantDeclaration-diagram-simplified-grouped-per-namespace.svg]] #MintCream {
}
class EnumDeclaration [[EnumDeclaration-diagram-simplified-grouped-per-namespace.svg]] #MintCream {
}
class String_BRQTO__BRQTC [[String_BRQTO__BRQTC-diagram-simplified-grouped-per-namespace.svg]] #MintCream {
}
class CompilationUnit [[CompilationUnit-diagram-simplified-grouped-per-namespace.svg]] #MintCream {
}
' Closing all previous_sub_namespace_list namespace None because file analysis is finished.
namespace preadapter [[preadapter-diagram-simplified-grouped-per-namespace.svg]] {
class preadapter.Logger [[preadapter.Logger-diagram-simplified-grouped-per-namespace.svg]]  {
}
'Compared namespace preadapter [[preadapter-diagram-simplified-grouped-per-namespace.svg]] { with last element of }
' Closing all previous_sub_namespace_list namespace None because file analysis is finished.
' Closing namespace preadapter
}
namespace preadapter [[preadapter-diagram-simplified-grouped-per-namespace.svg]] {
namespace preadapter.domain [[preadapter.domain-diagram-simplified-grouped-per-namespace.svg]] {
  class preadapter.domain.ASTVisitor [[preadapter.domain.ASTVisitor-diagram-simplified-grouped-per-namespace.svg]] #yellow {
  }
  class preadapter.domain.Datastructure [[preadapter.domain.Datastructure-diagram-simplified-grouped-per-namespace.svg]]  {
  }
  class preadapter.domain.Datastructure_DOT_SubDataStructure [[preadapter.domain.Datastructure_DOT_SubDataStructure-diagram-simplified-grouped-per-namespace.svg]]  {
  }
  class preadapter.domain.Datastructure_DOT_Method [[preadapter.domain.Datastructure_DOT_Method-diagram-simplified-grouped-per-namespace.svg]]  {
  }
  class preadapter.domain.ASTVisitor_DOT_ObjectType [[preadapter.domain.ASTVisitor_DOT_ObjectType-diagram-simplified-grouped-per-namespace.svg]]  {
  }
  class preadapter.domain.ASTVisitor_DOT_HandleDeepness [[preadapter.domain.ASTVisitor_DOT_HandleDeepness-diagram-simplified-grouped-per-namespace.svg]]  {
  }
'Compared namespace preadapter.domain [[preadapter.domain-diagram-simplified-grouped-per-namespace.svg]] { with last element of   }
' Closing all previous_sub_namespace_list namespace None because file analysis is finished.
' Closing namespace domain
}
' Closing namespace preadapter
}
 ' *************************************** 
 ' *************************************** 
 ' *************************************** 
' Class relations extracted from namespace:
' 
' Class relations extracted from namespace:
' preadapter
preadapter.Logger -[#909090]-> String_BRQTO__BRQTC  : uses 
' Class relations extracted from namespace:
' preadapter.domain
VoidVisitorAdapter_BRQTO_Void_BRQTC <|-[#red]- preadapter.domain.ASTVisitor
preadapter.domain.ASTVisitor +-[#10BBBB]- preadapter.domain.ASTVisitor_DOT_ObjectType 
preadapter.domain.ASTVisitor +-[#10BBBB]- preadapter.domain.ASTVisitor_DOT_HandleDeepness 
preadapter.domain.ASTVisitor .[#6060BB].> preadapter.Logger  : uses 
preadapter.domain.ASTVisitor .[#6060BB].> preadapter.domain.Datastructure  : uses 
preadapter.domain.ASTVisitor .[#6060BB].> HandleDeepness  : uses 
preadapter.domain.ASTVisitor .[#6060BB].> ClassOrInterfaceDeclaration  : uses 
preadapter.domain.ASTVisitor -[#909090]-> preadapter.domain.Datastructure_DOT_SubDataStructure  : uses 
preadapter.domain.ASTVisitor .[#6060BB].> MethodDeclaration  : uses 
preadapter.domain.ASTVisitor .[#6060BB].> Void  : uses 
preadapter.domain.ASTVisitor -[#909090]-> list_BRQTO_tuple_BRQTO_String_COMMA_String_COMMA_String_BRQTC_BRQTC  : uses 
preadapter.domain.ASTVisitor -[#909090]-> Optional_DOT_empty  : uses 
preadapter.domain.ASTVisitor -[#909090]-> VariableDeclarator  : uses 
preadapter.domain.ASTVisitor -[#909090]-> n_DOT_getNameAsString_BRQTO__BRQTC  : uses 
preadapter.domain.ASTVisitor -[#909090]-> n_DOT_getTypeAsString_BRQTO__BRQTC  : uses 
preadapter.domain.ASTVisitor -[#909090]-> n_DOT_getInitializer_BRQTO__BRQTC_DOT_toString_BRQTO__BRQTC  : uses 
preadapter.domain.ASTVisitor -[#909090]-> preadapter.domain.Datastructure_DOT_Method  : uses 
preadapter.domain.ASTVisitor .[#6060BB].> FieldDeclaration  : uses 
preadapter.domain.ASTVisitor .[#6060BB].> PackageDeclaration  : uses 
preadapter.domain.ASTVisitor .[#6060BB].> ImportDeclaration  : uses 
preadapter.domain.ASTVisitor .[#6060BB].> EnumConstantDeclaration  : uses 
preadapter.domain.ASTVisitor .[#6060BB].> EnumDeclaration  : uses 
preadapter.domain.ASTVisitor .[#6060BB].> VariableDeclarator  : uses 
preadapter.domain.ASTVisitor .[#6060BB].> String_BRQTO__BRQTC  : uses 
preadapter.domain.ASTVisitor -[#909090]-> CompilationUnit  : uses 
preadapter.domain.Datastructure +-[#10BBBB]- preadapter.domain.Datastructure_DOT_Method 
preadapter.domain.Datastructure +-[#10BBBB]- preadapter.domain.Datastructure_DOT_SubDataStructure 
preadapter.domain.Datastructure .[#6060BB].> preadapter.Logger  : uses 
preadapter.domain.Datastructure -[#909090]-> String_BRQTO__BRQTC  : uses 
@enduml