@startuml
skinparam linetype ortho
title <size:20>preadapter.domain.ASTVisitor_DOT_ObjectType **detailed** </size>
note "Your are analyzing:\npreadapter.domain.ASTVisitor_DOT_ObjectType **detailed** \n\n==Filter==\nYou can click either the namespaces \nor class names for filtering them and their\ndirect dependencies.\n\n==Select other==\n* preadapter.domain.ASTVisitor_DOT_ObjectType **simplified** :\n   [[preadapter.domain.ASTVisitor_DOT_ObjectType-diagram-simplified.svg]]\n* Full diagram **detailed** and **grouped per namespace**:\n   [[full-diagram-detailed-grouped-per-namespace.svg]]\n* Home:\n   [[index.html]]" as FloatingNote
  class preadapter.domain.ASTVisitor_DOT_ObjectType [[preadapter.domain.ASTVisitor_DOT_ObjectType-diagram-detailed.svg]] #yellow {
  }
  class preadapter.domain.ASTVisitor [[preadapter.domain.ASTVisitor-diagram-detailed.svg]]  {
    + logger: preadapter.Logger
    + datastructure: preadapter.domain.Datastructure
    + activeMethodList: list[String]
    + activeClassnameList: list[String]
    + namespaceList: list[String]
    + allUsing: list[String]
    + usingDict: dict[String,String]
    + deepness: HandleDeepness
    + ignoreType: list[String]
==
    + SimplifyType(<font color="6060BB">type:String</font>): <font color="BB6060">String</font>
--
    + cleanClassName(<font color="6060BB">className:String</font>): <font color="BB6060">String</font>
    - <font color="909090">cleanClassName.namespace: String</font>
    - <font color="909090">cleanClassName.namespaceLength: int</font>
--
    + CreateClassInterface(<font color="6060BB">node:ClassOrInterfaceDeclaration</font>): <font color="BB6060">String</font>
    - <font color="909090">CreateClassInterface.fqdnCurrentClassName: String</font>
    - <font color="909090">CreateClassInterface.fqdnParentClassName: String</font>
    - <font color="909090">CreateClassInterface.parentSubDataStructure: preadapter.domain.Datastructure_DOT_SubDataStructure</font>
    - <font color="909090">CreateClassInterface.subDataStructure: preadapter.domain.Datastructure_DOT_SubDataStructure</font>
    - <font color="909090">CreateClassInterface.fqdnCurrentClassNameFinal: String</font>
    - <font color="909090">CreateClassInterface.extendedTypeStr: String</font>
--
    - addArgumentType(<font color="6060BB">methodName:String, fqdnParentClassName:String, parameterType:Type, parameterName:String, argumentsTuple:list[tuple[String,String,String]]</font>): <font color="BB6060">void</font>
    - <font color="909090">addArgumentType.argumentTypeString: String</font>
    - <font color="909090">addArgumentType.mostProbableNS: String</font>
--
    + visit(<font color="6060BB">n:MethodDeclaration, arg:Void</font>): <font color="BB6060">void</font>
    - <font color="909090">visit.methodName: String</font>
    - <font color="909090">visit.fqdnParentClassName: String</font>
    - <font color="909090">visit.subDataStructure: preadapter.domain.Datastructure_DOT_SubDataStructure</font>
    - <font color="909090">visit.argument: Optional_DOT_empty</font>
    - <font color="909090">visit.className: String</font>
    - <font color="909090">visit.fqdnParentClassName: String</font>
    - <font color="909090">visit.subDataStructure: preadapter.domain.Datastructure_DOT_SubDataStructure</font>
    - <font color="909090">visit.argumentTypeString: String</font>
    - <font color="909090">visit.mostProbableNS: String</font>
    - <font color="909090">visit.variableDeclarator: VariableDeclarator</font>
    - <font color="909090">visit.importName: String</font>
    - <font color="909090">visit.enumValueName: String</font>
    - <font color="909090">visit.fqdnParentClassName: String</font>
    - <font color="909090">visit.subDataStructure: preadapter.domain.Datastructure_DOT_SubDataStructure</font>
    - <font color="909090">visit.fqdnCurrentClassName: String</font>
    - <font color="909090">visit.fqdnParentClassName: String</font>
    - <font color="909090">visit.subDataStructureParent: preadapter.domain.Datastructure_DOT_SubDataStructure</font>
    - <font color="909090">visit.subDataStructureChild: preadapter.domain.Datastructure_DOT_SubDataStructure</font>
    - <font color="909090">visit.fqdnParentClassName: String</font>
    - <font color="909090">visit.subDataStructureParent: preadapter.domain.Datastructure_DOT_SubDataStructure</font>
    - <font color="909090">visit.methodName: String</font>
    - <font color="909090">visit.method: preadapter.domain.Datastructure_DOT_Method</font>
--
    + visit(<font color="6060BB">n:ClassOrInterfaceDeclaration, arg:Void</font>): <font color="BB6060">void</font>
    + visit(<font color="6060BB">n:FieldDeclaration, arg:Void</font>): <font color="BB6060">void</font>
    + visit(<font color="6060BB">n:PackageDeclaration, arg:Void</font>): <font color="BB6060">void</font>
    + visit(<font color="6060BB">n:ImportDeclaration, arg:Void</font>): <font color="BB6060">void</font>
    + visit(<font color="6060BB">n:EnumConstantDeclaration, arg:Void</font>): <font color="BB6060">void</font>
    + visit(<font color="6060BB">n:EnumDeclaration, arg:Void</font>): <font color="BB6060">void</font>
    + visit(<font color="6060BB">n:VariableDeclarator, arg:Void</font>): <font color="BB6060">void</font>
--
    + main(<font color="6060BB">args:String</font>): <font color="BB6060">void</font>
    - <font color="909090">main.cu: CompilationUnit</font>
    - <font color="909090">main.file: String</font>
--
  }
 ' *************************************** 
 ' *************************************** 
 ' *************************************** 
' Class relations extracted from namespace:
' preadapter.domain
preadapter.domain.ASTVisitor +-[#10BBBB]- preadapter.domain.ASTVisitor_DOT_ObjectType 
@enduml