@startuml
title <size:20>preadapter.LoggingType **detailed** and **grouped per namespace**</size>
note "Your are analyzing:\npreadapter.LoggingType **detailed** and **grouped per namespace**\n\n==Filter==\nYou can click either the namespaces \nor class names for filtering them and their\ndirect dependencies.\n\n==Select other==\n* preadapter.LoggingType **simplified** and **grouped per namespace**:\n   [[preadapter.LoggingType-diagram-simplified-grouped-per-namespace.svg]]\n* Full diagram **detailed** and **grouped per namespace**:\n   [[full-diagram-detailed-grouped-per-namespace.svg]]\n* Home:\n   [[index.html]]" as FloatingNote
class EnumTypePlaceHolder [[EnumTypePlaceHolder-diagram-detailed-grouped-per-namespace.svg]] #MintCream {
}
' Closing all previous_sub_namespace_list namespace None because file analysis is finished.
namespace preadapter [[preadapter-diagram-detailed-grouped-per-namespace.svg]] {
class preadapter.LoggingType [[preadapter.LoggingType-diagram-detailed-grouped-per-namespace.svg]] #yellow {
  + TRACE: EnumTypePlaceHolder
  + DEBUG: EnumTypePlaceHolder
  + INFO: EnumTypePlaceHolder
  + WARNING: EnumTypePlaceHolder
  + ERROR: EnumTypePlaceHolder
==
  + getValue(<font color="6060BB"></font>)
}
class preadapter.Logger [[preadapter.Logger-diagram-detailed-grouped-per-namespace.svg]]  {
  + loggingType: preadapter.LoggingType
==
  - log(<font color="6060BB"></font>)
  - <font color="909090">log.result: String_BRQTO__BRQTC</font>
--
  + logError(<font color="6060BB"></font>)
  + logError(<font color="6060BB"></font>)
  + logWarning(<font color="6060BB"></font>)
  + logWarning(<font color="6060BB"></font>)
  + logInfo(<font color="6060BB"></font>)
  + logInfo(<font color="6060BB"></font>)
  + logDebug(<font color="6060BB"></font>)
  + logDebug(<font color="6060BB"></font>)
  + logTrace(<font color="6060BB"></font>)
  + logTrace(<font color="6060BB"></font>)
}
'Compared namespace preadapter [[preadapter-diagram-detailed-grouped-per-namespace.svg]] { with last element of }
' Closing all previous_sub_namespace_list namespace None because file analysis is finished.
' Closing namespace preadapter
}
 ' *************************************** 
 ' *************************************** 
 ' *************************************** 
' Class relations extracted from namespace:
' 
' Class relations extracted from namespace:
' preadapter
preadapter.LoggingType .[#6060BB].> EnumTypePlaceHolder  : uses 
preadapter.Logger .[#6060BB].> preadapter.LoggingType  : uses 
@enduml