@startuml
skinparam linetype ortho
title <size:20>preadapter.LoggingType **detailed** </size>
note "Your are analyzing:\npreadapter.LoggingType **detailed** \n\n==Filter==\nYou can click either the namespaces \nor class names for filtering them and their\ndirect dependencies.\n\n==Select other==\n* preadapter.LoggingType **simplified** :\n   [[preadapter.LoggingType-diagram-simplified.svg]]\n* Full diagram **detailed** and **grouped per namespace**:\n   [[full-diagram-detailed-grouped-per-namespace.svg]]\n* Home:\n   [[index.html]]" as FloatingNote
class preadapter.LoggingType [[preadapter.LoggingType-diagram-detailed.svg]] #yellow {
  + TRACE: EnumTypePlaceHolder
  + DEBUG: EnumTypePlaceHolder
  + INFO: EnumTypePlaceHolder
  + WARNING: EnumTypePlaceHolder
  + ERROR: EnumTypePlaceHolder
==
  + getValue(<font color="6060BB"></font>): <font color="BB6060">int</font>
}
class preadapter.Logger [[preadapter.Logger-diagram-detailed.svg]]  {
  + loggingType: preadapter.LoggingType
==
  - log(<font color="6060BB">logType:String, text:String, startText:String</font>): <font color="BB6060">void</font>
  - <font color="909090">log.result: String[]</font>
--
  + logError(<font color="6060BB">text:String, startText:String</font>): <font color="BB6060">void</font>
  + logError(<font color="6060BB">text:String</font>): <font color="BB6060">void</font>
  + logWarning(<font color="6060BB">text:String, startText:String</font>): <font color="BB6060">void</font>
  + logWarning(<font color="6060BB">text:String</font>): <font color="BB6060">void</font>
  + logInfo(<font color="6060BB">text:String, startText:String</font>): <font color="BB6060">void</font>
  + logInfo(<font color="6060BB">text:String</font>): <font color="BB6060">void</font>
  + logDebug(<font color="6060BB">text:String, startText:String</font>): <font color="BB6060">void</font>
  + logDebug(<font color="6060BB">text:String</font>): <font color="BB6060">void</font>
  + logTrace(<font color="6060BB">text:String, startText:String</font>): <font color="BB6060">void</font>
  + logTrace(<font color="6060BB">text:String</font>): <font color="BB6060">void</font>
}
 ' *************************************** 
 ' *************************************** 
 ' *************************************** 
' Class relations extracted from namespace:
' preadapter
preadapter.Logger *-[#10BB10]- preadapter.LoggingType 
@enduml