@startuml
title <size:20>preadapter.service.AnalyzeAST **simplified** </size>
note "Your are analyzing:\npreadapter.service.AnalyzeAST **simplified** \n\n==Filter==\nYou can click either the namespaces \nor class names for filtering them and their\ndirect dependencies.\n\n==Select other==\n* preadapter.service.AnalyzeAST **detailed** :\n   [[preadapter.service.AnalyzeAST-diagram-detailed.svg]]\n* Full diagram **simplified** and **grouped per namespace**:\n   [[full-diagram-simplified-grouped-per-namespace.svg]]\n* Home:\n   [[index.html]]" as FloatingNote
class RecursiveFileProcessor_BRQTO__BRQTC [[RecursiveFileProcessor_BRQTO__BRQTC-diagram-simplified.svg]] #MintCream {
}
class list_BRQTO_String_BRQTC [[list_BRQTO_String_BRQTC-diagram-simplified.svg]] #MintCream {
}
class CompilationUnit [[CompilationUnit-diagram-simplified.svg]] #MintCream {
}
class preadapter.Logger [[preadapter.Logger-diagram-simplified.svg]]  {
}
  class preadapter.domain.Datastructure [[preadapter.domain.Datastructure-diagram-simplified.svg]]  {
  }
  class preadapter.service.AnalyzeAST [[preadapter.service.AnalyzeAST-diagram-simplified.svg]] #yellow {
  }
 ' *************************************** 
 ' *************************************** 
 ' *************************************** 
' Class relations extracted from namespace:
' 
' Class relations extracted from namespace:
' preadapter
' Class relations extracted from namespace:
' preadapter.domain
preadapter.domain.Datastructure .[#6060BB].> preadapter.Logger  : uses 
preadapter.domain.Datastructure .[#6060BB].> list_BRQTO_String_BRQTC  : uses 
preadapter.domain.Datastructure -[#909090]-> list_BRQTO_String_BRQTC  : uses 
' Class relations extracted from namespace:
' preadapter.service
preadapter.service.AnalyzeAST .[#6060BB].> preadapter.Logger  : uses 
preadapter.service.AnalyzeAST -[#909090]-> preadapter.domain.Datastructure  : uses 
preadapter.service.AnalyzeAST -[#909090]-> RecursiveFileProcessor_BRQTO__BRQTC  : uses 
preadapter.service.AnalyzeAST -[#909090]-> list_BRQTO_String_BRQTC  : uses 
preadapter.service.AnalyzeAST -[#909090]-> CompilationUnit  : uses 
@enduml