@startuml
skinparam linetype ortho
title <size:20>String **simplified** </size>
note "Your are analyzing:\nString **simplified** \n\n==Filter==\nYou can click either the namespaces \nor class names for filtering them and their\ndirect dependencies.\n\n==Select other==\n* String **detailed** :\n   [[String-diagram-detailed.svg]]\n* Full diagram **simplified** and **grouped per namespace**:\n   [[full-diagram-simplified-grouped-per-namespace.svg]]\n* Home:\n   [[index.html]]" as FloatingNote
class String [[String-diagram-simplified.svg]] #yellow {
}
  class Examples.BadDesign.DB [[Examples.BadDesign.DB-diagram-simplified.svg]]  {
  }
  class Examples.BetterDesign.DBCar [[Examples.BetterDesign.DBCar-diagram-simplified.svg]]  {
  }
class preadapter.Logger [[preadapter.Logger-diagram-simplified.svg]]  {
}
class preadapter.Revenger [[preadapter.Revenger-diagram-simplified.svg]]  {
}
  class preadapter.domain.Datastructure [[preadapter.domain.Datastructure-diagram-simplified.svg]]  {
  }
  class preadapter.domain.ASTVisitorDebug [[preadapter.domain.ASTVisitorDebug-diagram-simplified.svg]]  {
  }
  class preadapter.domain.ASTVisitor [[preadapter.domain.ASTVisitor-diagram-simplified.svg]]  {
  }
  class preadapter.infrastructure.CreateYML [[preadapter.infrastructure.CreateYML-diagram-simplified.svg]]  {
  }
  class preadapter.service.AnalyzeAST [[preadapter.service.AnalyzeAST-diagram-simplified.svg]]  {
  }
  class preadapter.service.RecursiveFileProcessor [[preadapter.service.RecursiveFileProcessor-diagram-simplified.svg]]  {
  }
 ' *************************************** 
 ' *************************************** 
 ' *************************************** 
' Class relations extracted from namespace:
' 
' Class relations extracted from namespace:
' Examples.BadDesign
Examples.BadDesign.DB .[#6060BB].> String  : uses 
' Class relations extracted from namespace:
' Examples.BetterDesign
Examples.BetterDesign.DBCar .[#6060BB].> String  : uses 
' Class relations extracted from namespace:
' preadapter
preadapter.Logger .[#6060BB].> String  : uses 
preadapter.Revenger .[#6060BB].> String  : uses 
preadapter.Revenger -[#909090]-> String  : uses 
preadapter.Revenger -[#909090]-> preadapter.Logger  : uses 
' Class relations extracted from namespace:
' preadapter.domain
preadapter.domain.Datastructure *-[#10BB10]- preadapter.Logger 
preadapter.domain.Datastructure .[#6060BB].> String  : uses 
preadapter.domain.Datastructure -[#909090]-> String  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> String  : uses 
preadapter.domain.ASTVisitorDebug -[#909090]-> String  : uses 
preadapter.domain.ASTVisitor *-[#10BB10]- preadapter.Logger 
preadapter.domain.ASTVisitor *-[#10BB10]- preadapter.domain.Datastructure 
preadapter.domain.ASTVisitor .[#6060BB].> String  : uses 
preadapter.domain.ASTVisitor -[#909090]-> String  : uses 
' Class relations extracted from namespace:
' preadapter.infrastructure
preadapter.infrastructure.CreateYML .[#6060BB].> String  : uses 
preadapter.infrastructure.CreateYML .[#6060BB].> preadapter.domain.Datastructure  : uses 
preadapter.infrastructure.CreateYML .[#6060BB].> preadapter.Logger  : uses 
' Class relations extracted from namespace:
' preadapter.service
preadapter.service.AnalyzeAST .[#6060BB].> String  : uses 
preadapter.service.AnalyzeAST .[#6060BB].> preadapter.Logger  : uses 
preadapter.service.AnalyzeAST -[#909090]-> preadapter.domain.Datastructure  : uses 
preadapter.service.AnalyzeAST -[#909090]-> String  : uses 
preadapter.service.RecursiveFileProcessor .[#6060BB].> String  : uses 
@enduml