@startuml
title <size:20>DumperOptions **detailed** and **grouped per namespace**</size>
note "Your are analyzing:\nDumperOptions **detailed** and **grouped per namespace**\n\n==Filter==\nYou can click either the namespaces \nor class names for filtering them and their\ndirect dependencies.\n\n==Select other==\n* DumperOptions **simplified** and **grouped per namespace**:\n   [[DumperOptions-diagram-simplified-grouped-per-namespace.svg]]\n* Full diagram **detailed** and **grouped per namespace**:\n   [[full-diagram-detailed-grouped-per-namespace.svg]]\n* Home:\n   [[index.html]]" as FloatingNote
class DumperOptions.FlowStyle [[DumperOptions.FlowStyle-diagram-detailed-grouped-per-namespace.svg]] #yellow {
}
' Closing all previous_sub_namespace_list namespace None because file analysis is finished.
namespace preadapter [[preadapter-diagram-detailed-grouped-per-namespace.svg]] {
namespace preadapter.infrastructure [[preadapter.infrastructure-diagram-detailed-grouped-per-namespace.svg]] {
  class preadapter.infrastructure.CreateYML [[preadapter.infrastructure.CreateYML-diagram-detailed-grouped-per-namespace.svg]]  {
    + dummperOptions: DumperOptions.FlowStyle
    + startMark: Mark
    + endMark: Mark
==
    - appendTupleNodeValueSequenceNode(<font color="6060BB">appendTupleNodeValueSequenceNode:dictpingNode, appendTupleNodeValueSequenceNode:SequenceNode</font>)
    - appendTupleNodeValueString(<font color="6060BB">appendTupleNodeValueString:dictpingNode</font>)
--
    - appendTupleNodeValueStringToSequenceNode(<font color="6060BB">appendTupleNodeValueStringToSequenceNode:SequenceNode</font>)
    - <font color="909090">appendTupleNodeValueStringToSequenceNode.mappingNode: dictpingNode_BRQTO_Tag_DOT_MAP_COMMA__SPC_Arraylist_BRQTO__BRQTC_BRQTO__BRQTC_COMMA__SPC_dummperOptions_BRQTC</font>
--
    - appendSequence(<font color="6060BB">appendSequence:dictpingNode, appendSequence:list_BRQTO_String_BRQTC</font>)
    - <font color="909090">appendSequence.subSequenceNode: SequenceNode</font>
--
    + Create(<font color="6060BB">Create:preadapter.domain.Datastructure, Create:preadapter.Logger</font>)
    - <font color="909090">Create.subDataStructureSequenceYmlNode: SequenceNode_BRQTO_Tag_DOT_SEQ_COMMA__SPC_Arraylist_BRQTO__BRQTC_BRQTO__BRQTC_COMMA__SPC_dummperOptions_BRQTC</font>
    - <font color="909090">Create.subDataStructureMappingYmlNode: dictpingNode_BRQTO_Tag_DOT_MAP_COMMA__SPC_Arraylist_BRQTO__BRQTC_BRQTO__BRQTC_COMMA__SPC_dummperOptions_BRQTC</font>
    - <font color="909090">Create.subDataStructure: preadapter.domain.Datastructure_DOT_SubDataStructure</font>
    - <font color="909090">Create.fromImportsSequenceNode: SequenceNode_BRQTO_Tag_DOT_SEQ_COMMA__SPC_Arraylist_BRQTO__BRQTC_BRQTO__BRQTC_COMMA__SPC_dummperOptions_BRQTC</font>
    - <font color="909090">Create.fromImportsMappingNode: dictpingNode_BRQTO_Tag_DOT_MAP_COMMA__SPC_Arraylist_BRQTO__BRQTC_BRQTO__BRQTC_COMMA__SPC_dummperOptions_BRQTC</font>
    - <font color="909090">Create.staticsSequenceNode: SequenceNode_BRQTO_Tag_DOT_SEQ_COMMA__SPC_Arraylist_BRQTO__BRQTC_BRQTO__BRQTC_COMMA__SPC_dummperOptions_BRQTC</font>
    - <font color="909090">Create.staticsMappingNode: dictpingNode_BRQTO_Tag_DOT_MAP_COMMA__SPC_Arraylist_BRQTO__BRQTC_BRQTO__BRQTC_COMMA__SPC_dummperOptions_BRQTC</font>
    - <font color="909090">Create.variablesSequenceNode: SequenceNode_BRQTO_Tag_DOT_SEQ_COMMA__SPC_Arraylist_BRQTO__BRQTC_BRQTO__BRQTC_COMMA__SPC_dummperOptions_BRQTC</font>
    - <font color="909090">Create.variablesMappingNode: dictpingNode_BRQTO_Tag_DOT_MAP_COMMA__SPC_Arraylist_BRQTO__BRQTC_BRQTO__BRQTC_COMMA__SPC_dummperOptions_BRQTC</font>
    - <font color="909090">Create.methodsSequenceNode: SequenceNode_BRQTO_Tag_DOT_SEQ_COMMA__SPC_Arraylist_BRQTO__BRQTC_BRQTO__BRQTC_COMMA__SPC_dummperOptions_BRQTC</font>
    - <font color="909090">Create.parameters: SequenceNode_BRQTO_Tag_DOT_SEQ_COMMA__SPC_Arraylist_BRQTO__BRQTC_BRQTO__BRQTC_COMMA__SPC_dummperOptions_BRQTC</font>
    - <font color="909090">Create.methodParametersMappingNode: dictpingNode_BRQTO_Tag_DOT_MAP_COMMA__SPC_Arraylist_BRQTO__BRQTC_BRQTO__BRQTC_COMMA__SPC_dummperOptions_BRQTC</font>
    - <font color="909090">Create.methodVariables: SequenceNode_BRQTO_Tag_DOT_SEQ_COMMA__SPC_Arraylist_BRQTO__BRQTC_BRQTO__BRQTC_COMMA__SPC_dummperOptions_BRQTC</font>
    - <font color="909090">Create.methodVariablesMappingNode: dictpingNode_BRQTO_Tag_DOT_MAP_COMMA__SPC_Arraylist_BRQTO__BRQTC_BRQTO__BRQTC_COMMA__SPC_dummperOptions_BRQTC</font>
    - <font color="909090">Create.methodNode: dictpingNode_BRQTO_Tag_DOT_MAP_COMMA__SPC_Arraylist_BRQTO__BRQTC_BRQTO__BRQTC_COMMA__SPC_dummperOptions_BRQTC</font>
    - <font color="909090">Create.tmpMappingNode: dictpingNode_BRQTO_Tag_DOT_MAP_COMMA__SPC_Arraylist_BRQTO__BRQTC_BRQTO__BRQTC_COMMA__SPC_dummperOptions_BRQTC</font>
    - <font color="909090">Create.yaml: Yaml</font>
    - <font color="909090">Create.writer: PrintWriter</font>
--
  }
'Compared namespace preadapter.infrastructure [[preadapter.infrastructure-diagram-detailed-grouped-per-namespace.svg]] { with last element of   }
' Closing all previous_sub_namespace_list namespace None because file analysis is finished.
' Closing namespace infrastructure
}
' Closing namespace preadapter
}
 ' *************************************** 
 ' *************************************** 
 ' *************************************** 
' Class relations extracted from namespace:
' 
' Class relations extracted from namespace:
' preadapter.infrastructure
preadapter.infrastructure.CreateYML .[#6060BB].> DumperOptions.FlowStyle  : uses 
@enduml