@startuml
title <size:20>Example.BaseExample_DOT_EnumTest **detailed** </size>
note "Your are analyzing:\nExample.BaseExample_DOT_EnumTest **detailed** \n\n==Filter==\nYou can click either the namespaces \nor class names for filtering them and their\ndirect dependencies.\n\n==Select other==\n* Example.BaseExample_DOT_EnumTest **simplified** :\n   [[Example.BaseExample_DOT_EnumTest-diagram-simplified.svg]]\n* Full diagram **detailed** and **grouped per namespace**:\n   [[full-diagram-detailed-grouped-per-namespace.svg]]\n* Home:\n   [[index.html]]" as FloatingNote
class Example.BaseExample_DOT_EnumTest [[Example.BaseExample_DOT_EnumTest-diagram-detailed.svg]] #yellow {
}
class Example.BaseExample [[Example.BaseExample-diagram-detailed.svg]]  {
  + exampleAbstract(<font color="6060BB">exampleAbstract:Example.Useless, exampleAbstract:Example.Useless</font>)
  + otherExample(<font color="6060BB"></font>)
}
 ' *************************************** 
 ' *************************************** 
 ' *************************************** 
' Class relations extracted from namespace:
' Example
Example.BaseExample +-[#10BBBB]- Example.BaseExample_DOT_EnumTest 
@enduml