@startuml
title <size:20>Example **detailed** </size>
note "Your are analyzing:\nExample **detailed** \n\n==Filter==\nYou can click either the namespaces \nor class names for filtering them and their\ndirect dependencies.\n\n==Select other==\n* Example **simplified** :\n   [[Example-diagram-simplified.svg]]\n* Full diagram **detailed** and **grouped per namespace**:\n   [[full-diagram-detailed-grouped-per-namespace.svg]]\n* Home:\n   [[index.html]]" as FloatingNote
class EnumTest [[EnumTest-diagram-detailed.svg]] #MintCream {
}
class EnumTypePlaceHolder [[EnumTypePlaceHolder-diagram-detailed.svg]] #MintCream {
}
class Example.ClassExample [[Example.ClassExample-diagram-detailed.svg]] #yellow {
  + memberVarUseless: Example.Useless
  + memberVarEnumTest: EnumTest
==
  + example(<font color="6060BB">example:Example.Useless, example:Example.Useless</font>)
  - <font color="909090">example.localVarBaseExample: Example.BaseExample</font>
--
  + getExample(<font color="6060BB"></font>)
  + exampleAbstract(<font color="6060BB">exampleAbstract:Example.Useless, exampleAbstract:Example.Useless</font>)
}
class Example.BaseExample [[Example.BaseExample-diagram-detailed.svg]] #yellow {
  + exampleAbstract(<font color="6060BB">exampleAbstract:Example.Useless, exampleAbstract:Example.Useless</font>)
  + otherExample(<font color="6060BB"></font>)
}
class Example.Useless [[Example.Useless-diagram-detailed.svg]] #yellow {
  + useless(<font color="6060BB"></font>)
  - <font color="909090">useless.testEnum: Example.SideExample.SideTestEnum</font>
--
}
class Example.ClassExample_DOT_InnerClassExample [[Example.ClassExample_DOT_InnerClassExample-diagram-detailed.svg]] #yellow {
}
class Example.ClassExample_DOT_InnerClassExample_DOT_classInMethodExample [[Example.ClassExample_DOT_InnerClassExample_DOT_classInMethodExample-diagram-detailed.svg]] #yellow {
}
interface Example.IExample [[Example.IExample-diagram-detailed.svg]] #yellow {
  + example(<font color="6060BB">example:Example.Useless, example:Example.Useless</font>)
}
class Example.BaseExample_DOT_EnumTest [[Example.BaseExample_DOT_EnumTest-diagram-detailed.svg]] #yellow {
}
abstract class Example.AbstractBaseExample [[Example.AbstractBaseExample-diagram-detailed.svg]] #yellow {
  + exampleAbstract(<font color="6060BB">exampleAbstract:Example.Useless, exampleAbstract:Example.Useless</font>)
}
  class Example.SideExample.SideTestEnum [[Example.SideExample.SideTestEnum-diagram-detailed.svg]] #yellow {
    + TestEnumValue1: EnumTypePlaceHolder
    + TestEnumValue2: EnumTypePlaceHolder
==
  }
  class Example.SideExample.SideExample [[Example.SideExample.SideExample-diagram-detailed.svg]] #yellow {
    + test(<font color="6060BB">test:Example.SideExample.SideTestEnum</font>)
    + testNoParameter(<font color="6060BB"></font>)
  }
 ' *************************************** 
 ' *************************************** 
 ' *************************************** 
' Class relations extracted from namespace:
' 
' Class relations extracted from namespace:
' Example
Example.BaseExample <|-[#red]- Example.ClassExample
Example.ClassExample +-[#10BBBB]- Example.ClassExample_DOT_InnerClassExample 
Example.ClassExample .[#6060BB].> Example.Useless  : uses 
Example.ClassExample .[#6060BB].> EnumTest  : uses 
Example.ClassExample -[#909090]-> Example.BaseExample  : uses 
Example.AbstractBaseExample <|-[#red]- Example.BaseExample
Example.BaseExample +-[#10BBBB]- Example.BaseExample_DOT_EnumTest 
Example.BaseExample .[#6060BB].> Example.Useless  : uses 
Example.Useless -[#909090]-> Example.SideExample.SideTestEnum  : uses 
Example.ClassExample_DOT_InnerClassExample +-[#10BBBB]- Example.ClassExample_DOT_InnerClassExample_DOT_classInMethodExample 
Example.IExample .[#6060BB].> Example.Useless  : uses 
Example.AbstractBaseExample .[#6060BB].> Example.Useless  : uses 
' Class relations extracted from namespace:
' Example.SideExample
Example.SideExample.SideTestEnum .[#6060BB].> EnumTypePlaceHolder  : uses 
Example.SideExample.SideExample .[#6060BB].> Example.SideExample.SideTestEnum  : uses 
@enduml