@startuml
title <size:20>Example.BaseExample **detailed** and **grouped per namespace**</size>
note "Your are analyzing:\nExample.BaseExample **detailed** and **grouped per namespace**\n\n==Filter==\nYou can click either the namespaces \nor class names for filtering them and their\ndirect dependencies.\n\n==Select other==\n* Example.BaseExample **simplified** and **grouped per namespace**:\n   [[Example.BaseExample-diagram-simplified-grouped-per-namespace.svg]]\n* Full diagram **detailed** and **grouped per namespace**:\n   [[full-diagram-detailed-grouped-per-namespace.svg]]\n* Home:\n   [[index.html]]" as FloatingNote
namespace Example [[Example-diagram-detailed-grouped-per-namespace.svg]] {
class Example.BaseExample [[Example.BaseExample-diagram-detailed-grouped-per-namespace.svg]] #yellow {
  + exampleAbstract(<font color="6060BB">exampleAbstract:Example.Useless, exampleAbstract:Example.Useless</font>)
  + otherExample(<font color="6060BB"></font>)
}
abstract class Example.AbstractBaseExample [[Example.AbstractBaseExample-diagram-detailed-grouped-per-namespace.svg]]  {
  + exampleAbstract(<font color="6060BB">exampleAbstract:Example.Useless, exampleAbstract:Example.Useless</font>)
}
class Example.Useless [[Example.Useless-diagram-detailed-grouped-per-namespace.svg]]  {
  + useless(<font color="6060BB"></font>)
  - <font color="909090">useless.testEnum: Example.SideExample.SideTestEnum</font>
--
}
class Example.BaseExample_DOT_EnumTest [[Example.BaseExample_DOT_EnumTest-diagram-detailed-grouped-per-namespace.svg]]  {
}
class Example.ClassExample [[Example.ClassExample-diagram-detailed-grouped-per-namespace.svg]]  {
  + memberVarUseless: Example.Useless
  + memberVarEnumTest: EnumTest
==
  + example(<font color="6060BB">example:Example.Useless, example:Example.Useless</font>)
  - <font color="909090">example.localVarBaseExample: Example.BaseExample</font>
--
  + getExample(<font color="6060BB"></font>)
  + exampleAbstract(<font color="6060BB">exampleAbstract:Example.Useless, exampleAbstract:Example.Useless</font>)
}
'Compared namespace Example [[Example-diagram-detailed-grouped-per-namespace.svg]] { with last element of }
' Closing all previous_sub_namespace_list namespace None because file analysis is finished.
' Closing namespace Example
}
 ' *************************************** 
 ' *************************************** 
 ' *************************************** 
' Class relations extracted from namespace:
' Example
Example.AbstractBaseExample <|-[#red]- Example.BaseExample
Example.BaseExample +-[#10BBBB]- Example.BaseExample_DOT_EnumTest 
Example.BaseExample .[#6060BB].> Example.Useless  : uses 
Example.AbstractBaseExample .[#6060BB].> Example.Useless  : uses 
Example.BaseExample <|-[#red]- Example.ClassExample
Example.ClassExample .[#6060BB].> Example.Useless  : uses 
Example.ClassExample -[#909090]-> Example.BaseExample  : uses 
@enduml