@startuml
title <size:20>Optional_DOT_empty **simplified** </size>
note "Your are analyzing:\nOptional_DOT_empty **simplified** \n\n==Filter==\nYou can click either the namespaces \nor class names for filtering them and their\ndirect dependencies.\n\n==Select other==\n* Optional_DOT_empty **detailed** :\n   [[Optional_DOT_empty-diagram-detailed.svg]]\n* Full diagram **simplified** and **grouped per namespace**:\n   [[full-diagram-simplified-grouped-per-namespace.svg]]\n* Home:\n   [[index.html]]" as FloatingNote
class Optional_DOT_empty [[Optional_DOT_empty-diagram-simplified.svg]] #yellow {
}
  class preadapter.domain.ASTVisitor [[preadapter.domain.ASTVisitor-diagram-simplified.svg]]  {
  }
 ' *************************************** 
 ' *************************************** 
 ' *************************************** 
' Class relations extracted from namespace:
' 
' Class relations extracted from namespace:
' preadapter.domain
preadapter.domain.ASTVisitor -[#909090]-> Optional_DOT_empty  : uses 
@enduml