@startuml
title <size:20>preadapter.domain.ASTVisitor_DOT_HandleDeepness **simplified** </size>
note "Your are analyzing:\npreadapter.domain.ASTVisitor_DOT_HandleDeepness **simplified** \n\n==Filter==\nYou can click either the namespaces \nor class names for filtering them and their\ndirect dependencies.\n\n==Select other==\n* preadapter.domain.ASTVisitor_DOT_HandleDeepness **detailed** :\n   [[preadapter.domain.ASTVisitor_DOT_HandleDeepness-diagram-detailed.svg]]\n* Full diagram **simplified** and **grouped per namespace**:\n   [[full-diagram-simplified-grouped-per-namespace.svg]]\n* Home:\n   [[index.html]]" as FloatingNote
  class preadapter.domain.ASTVisitor_DOT_HandleDeepness [[preadapter.domain.ASTVisitor_DOT_HandleDeepness-diagram-simplified.svg]] #yellow {
  }
  class preadapter.domain.ASTVisitor [[preadapter.domain.ASTVisitor-diagram-simplified.svg]]  {
  }
 ' *************************************** 
 ' *************************************** 
 ' *************************************** 
' Class relations extracted from namespace:
' preadapter.domain
preadapter.domain.ASTVisitor +-[#10BBBB]- preadapter.domain.ASTVisitor_DOT_HandleDeepness 
@enduml