@startuml
title <size:20>preadapter.domain **detailed** and **grouped per namespace**</size>
note "Your are analyzing:\npreadapter.domain **detailed** and **grouped per namespace**\n\n==Filter==\nYou can click either the namespaces \nor class names for filtering them and their\ndirect dependencies.\n\n==Select other==\n* preadapter.domain **simplified** and **grouped per namespace**:\n   [[preadapter.domain-diagram-simplified-grouped-per-namespace.svg]]\n* Full diagram **detailed** and **grouped per namespace**:\n   [[full-diagram-detailed-grouped-per-namespace.svg]]\n* Home:\n   [[index.html]]" as FloatingNote
class list_BRQTO_Variable_BRQTC [[list_BRQTO_Variable_BRQTC-diagram-detailed-grouped-per-namespace.svg]] #MintCream {
}
class Variable [[Variable-diagram-detailed-grouped-per-namespace.svg]] #MintCream {
}
class Method [[Method-diagram-detailed-grouped-per-namespace.svg]] #MintCream {
}
class SubDataStructure [[SubDataStructure-diagram-detailed-grouped-per-namespace.svg]] #MintCream {
}
class list_BRQTO_String_BRQTC [[list_BRQTO_String_BRQTC-diagram-detailed-grouped-per-namespace.svg]] #MintCream {
}
class String_BRQTO__BRQTC [[String_BRQTO__BRQTC-diagram-detailed-grouped-per-namespace.svg]] #MintCream {
}
class VoidVisitorAdapter_BRQTO_Void_BRQTC [[VoidVisitorAdapter_BRQTO_Void_BRQTC-diagram-detailed-grouped-per-namespace.svg]] #MintCream {
}
class HandleDeepness [[HandleDeepness-diagram-detailed-grouped-per-namespace.svg]] #MintCream {
}
class ClassOrInterfaceDeclaration [[ClassOrInterfaceDeclaration-diagram-detailed-grouped-per-namespace.svg]] #MintCream {
}
class MethodDeclaration [[MethodDeclaration-diagram-detailed-grouped-per-namespace.svg]] #MintCream {
}
class Void [[Void-diagram-detailed-grouped-per-namespace.svg]] #MintCream {
}
class list_BRQTO_tuple_BRQTO_String_COMMA_String_COMMA_String_BRQTC_BRQTC [[list_BRQTO_tuple_BRQTO_String_COMMA_String_COMMA_String_BRQTC_BRQTC-diagram-detailed-grouped-per-namespace.svg]] #MintCream {
}
class Optional_DOT_empty [[Optional_DOT_empty-diagram-detailed-grouped-per-namespace.svg]] #MintCream {
}
class VariableDeclarator [[VariableDeclarator-diagram-detailed-grouped-per-namespace.svg]] #MintCream {
}
class n_DOT_getNameAsString_BRQTO__BRQTC [[n_DOT_getNameAsString_BRQTO__BRQTC-diagram-detailed-grouped-per-namespace.svg]] #MintCream {
}
class n_DOT_getTypeAsString_BRQTO__BRQTC [[n_DOT_getTypeAsString_BRQTO__BRQTC-diagram-detailed-grouped-per-namespace.svg]] #MintCream {
}
class n_DOT_getInitializer_BRQTO__BRQTC_DOT_toString_BRQTO__BRQTC [[n_DOT_getInitializer_BRQTO__BRQTC_DOT_toString_BRQTO__BRQTC-diagram-detailed-grouped-per-namespace.svg]] #MintCream {
}
class FieldDeclaration [[FieldDeclaration-diagram-detailed-grouped-per-namespace.svg]] #MintCream {
}
class PackageDeclaration [[PackageDeclaration-diagram-detailed-grouped-per-namespace.svg]] #MintCream {
}
class ImportDeclaration [[ImportDeclaration-diagram-detailed-grouped-per-namespace.svg]] #MintCream {
}
class EnumConstantDeclaration [[EnumConstantDeclaration-diagram-detailed-grouped-per-namespace.svg]] #MintCream {
}
class EnumDeclaration [[EnumDeclaration-diagram-detailed-grouped-per-namespace.svg]] #MintCream {
}
class CompilationUnit [[CompilationUnit-diagram-detailed-grouped-per-namespace.svg]] #MintCream {
}
class PrintStream [[PrintStream-diagram-detailed-grouped-per-namespace.svg]] #MintCream {
}
class AnnotationDeclaration [[AnnotationDeclaration-diagram-detailed-grouped-per-namespace.svg]] #MintCream {
}
class AnnotationMemberDeclaration [[AnnotationMemberDeclaration-diagram-detailed-grouped-per-namespace.svg]] #MintCream {
}
class ArrayAccessExpr [[ArrayAccessExpr-diagram-detailed-grouped-per-namespace.svg]] #MintCream {
}
class ArrayCreationExpr [[ArrayCreationExpr-diagram-detailed-grouped-per-namespace.svg]] #MintCream {
}
class ArrayCreationLevel [[ArrayCreationLevel-diagram-detailed-grouped-per-namespace.svg]] #MintCream {
}
class ArrayInitializerExpr [[ArrayInitializerExpr-diagram-detailed-grouped-per-namespace.svg]] #MintCream {
}
class ArrayType [[ArrayType-diagram-detailed-grouped-per-namespace.svg]] #MintCream {
}
class AssertStmt [[AssertStmt-diagram-detailed-grouped-per-namespace.svg]] #MintCream {
}
class AssignExpr [[AssignExpr-diagram-detailed-grouped-per-namespace.svg]] #MintCream {
}
class BinaryExpr [[BinaryExpr-diagram-detailed-grouped-per-namespace.svg]] #MintCream {
}
class BlockComment [[BlockComment-diagram-detailed-grouped-per-namespace.svg]] #MintCream {
}
class BlockStmt [[BlockStmt-diagram-detailed-grouped-per-namespace.svg]] #MintCream {
}
class BooleanLiteralExpr [[BooleanLiteralExpr-diagram-detailed-grouped-per-namespace.svg]] #MintCream {
}
class BreakStmt [[BreakStmt-diagram-detailed-grouped-per-namespace.svg]] #MintCream {
}
class CastExpr [[CastExpr-diagram-detailed-grouped-per-namespace.svg]] #MintCream {
}
class CatchClause [[CatchClause-diagram-detailed-grouped-per-namespace.svg]] #MintCream {
}
class CharLiteralExpr [[CharLiteralExpr-diagram-detailed-grouped-per-namespace.svg]] #MintCream {
}
class ClassExpr [[ClassExpr-diagram-detailed-grouped-per-namespace.svg]] #MintCream {
}
class ClassOrInterfaceType [[ClassOrInterfaceType-diagram-detailed-grouped-per-namespace.svg]] #MintCream {
}
class ConditionalExpr [[ConditionalExpr-diagram-detailed-grouped-per-namespace.svg]] #MintCream {
}
class ConstructorDeclaration [[ConstructorDeclaration-diagram-detailed-grouped-per-namespace.svg]] #MintCream {
}
class ContinueStmt [[ContinueStmt-diagram-detailed-grouped-per-namespace.svg]] #MintCream {
}
class DoStmt [[DoStmt-diagram-detailed-grouped-per-namespace.svg]] #MintCream {
}
class DoubleLiteralExpr [[DoubleLiteralExpr-diagram-detailed-grouped-per-namespace.svg]] #MintCream {
}
class EmptyStmt [[EmptyStmt-diagram-detailed-grouped-per-namespace.svg]] #MintCream {
}
class EnclosedExpr [[EnclosedExpr-diagram-detailed-grouped-per-namespace.svg]] #MintCream {
}
class ExplicitConstructorInvocationStmt [[ExplicitConstructorInvocationStmt-diagram-detailed-grouped-per-namespace.svg]] #MintCream {
}
class ExpressionStmt [[ExpressionStmt-diagram-detailed-grouped-per-namespace.svg]] #MintCream {
}
class FieldAccessExpr [[FieldAccessExpr-diagram-detailed-grouped-per-namespace.svg]] #MintCream {
}
class ForEachStmt [[ForEachStmt-diagram-detailed-grouped-per-namespace.svg]] #MintCream {
}
class ForStmt [[ForStmt-diagram-detailed-grouped-per-namespace.svg]] #MintCream {
}
class IfStmt [[IfStmt-diagram-detailed-grouped-per-namespace.svg]] #MintCream {
}
class InitializerDeclaration [[InitializerDeclaration-diagram-detailed-grouped-per-namespace.svg]] #MintCream {
}
class InstanceOfExpr [[InstanceOfExpr-diagram-detailed-grouped-per-namespace.svg]] #MintCream {
}
class IntegerLiteralExpr [[IntegerLiteralExpr-diagram-detailed-grouped-per-namespace.svg]] #MintCream {
}
class IntersectionType [[IntersectionType-diagram-detailed-grouped-per-namespace.svg]] #MintCream {
}
class JavadocComment [[JavadocComment-diagram-detailed-grouped-per-namespace.svg]] #MintCream {
}
class LabeledStmt [[LabeledStmt-diagram-detailed-grouped-per-namespace.svg]] #MintCream {
}
class LambdaExpr [[LambdaExpr-diagram-detailed-grouped-per-namespace.svg]] #MintCream {
}
class LineComment [[LineComment-diagram-detailed-grouped-per-namespace.svg]] #MintCream {
}
class LocalClassDeclarationStmt [[LocalClassDeclarationStmt-diagram-detailed-grouped-per-namespace.svg]] #MintCream {
}
class LongLiteralExpr [[LongLiteralExpr-diagram-detailed-grouped-per-namespace.svg]] #MintCream {
}
class MarkerAnnotationExpr [[MarkerAnnotationExpr-diagram-detailed-grouped-per-namespace.svg]] #MintCream {
}
class MemberValuetuple [[MemberValuetuple-diagram-detailed-grouped-per-namespace.svg]] #MintCream {
}
class MethodCallExpr [[MethodCallExpr-diagram-detailed-grouped-per-namespace.svg]] #MintCream {
}
class MethodReferenceExpr [[MethodReferenceExpr-diagram-detailed-grouped-per-namespace.svg]] #MintCream {
}
class ModuleDeclaration [[ModuleDeclaration-diagram-detailed-grouped-per-namespace.svg]] #MintCream {
}
class ModuleExportsDirective [[ModuleExportsDirective-diagram-detailed-grouped-per-namespace.svg]] #MintCream {
}
class ModuleOpensDirective [[ModuleOpensDirective-diagram-detailed-grouped-per-namespace.svg]] #MintCream {
}
class ModuleProvidesDirective [[ModuleProvidesDirective-diagram-detailed-grouped-per-namespace.svg]] #MintCream {
}
class ModuleRequiresDirective [[ModuleRequiresDirective-diagram-detailed-grouped-per-namespace.svg]] #MintCream {
}
class ModuleUsesDirective [[ModuleUsesDirective-diagram-detailed-grouped-per-namespace.svg]] #MintCream {
}
class Name [[Name-diagram-detailed-grouped-per-namespace.svg]] #MintCream {
}
class NameExpr [[NameExpr-diagram-detailed-grouped-per-namespace.svg]] #MintCream {
}
class Nodelist [[Nodelist-diagram-detailed-grouped-per-namespace.svg]] #MintCream {
}
class NormalAnnotationExpr [[NormalAnnotationExpr-diagram-detailed-grouped-per-namespace.svg]] #MintCream {
}
class NullLiteralExpr [[NullLiteralExpr-diagram-detailed-grouped-per-namespace.svg]] #MintCream {
}
class ObjectCreationExpr [[ObjectCreationExpr-diagram-detailed-grouped-per-namespace.svg]] #MintCream {
}
class Parameter [[Parameter-diagram-detailed-grouped-per-namespace.svg]] #MintCream {
}
class PrimitiveType [[PrimitiveType-diagram-detailed-grouped-per-namespace.svg]] #MintCream {
}
class ReturnStmt [[ReturnStmt-diagram-detailed-grouped-per-namespace.svg]] #MintCream {
}
class SimpleName [[SimpleName-diagram-detailed-grouped-per-namespace.svg]] #MintCream {
}
class SingleMemberAnnotationExpr [[SingleMemberAnnotationExpr-diagram-detailed-grouped-per-namespace.svg]] #MintCream {
}
class StringLiteralExpr [[StringLiteralExpr-diagram-detailed-grouped-per-namespace.svg]] #MintCream {
}
class SuperExpr [[SuperExpr-diagram-detailed-grouped-per-namespace.svg]] #MintCream {
}
class SwitchEntry [[SwitchEntry-diagram-detailed-grouped-per-namespace.svg]] #MintCream {
}
class SwitchStmt [[SwitchStmt-diagram-detailed-grouped-per-namespace.svg]] #MintCream {
}
class SynchronizedStmt [[SynchronizedStmt-diagram-detailed-grouped-per-namespace.svg]] #MintCream {
}
class ThisExpr [[ThisExpr-diagram-detailed-grouped-per-namespace.svg]] #MintCream {
}
class ThrowStmt [[ThrowStmt-diagram-detailed-grouped-per-namespace.svg]] #MintCream {
}
class TryStmt [[TryStmt-diagram-detailed-grouped-per-namespace.svg]] #MintCream {
}
class TypeExpr [[TypeExpr-diagram-detailed-grouped-per-namespace.svg]] #MintCream {
}
class TypeParameter [[TypeParameter-diagram-detailed-grouped-per-namespace.svg]] #MintCream {
}
class UnaryExpr [[UnaryExpr-diagram-detailed-grouped-per-namespace.svg]] #MintCream {
}
class UnionType [[UnionType-diagram-detailed-grouped-per-namespace.svg]] #MintCream {
}
class UnknownType [[UnknownType-diagram-detailed-grouped-per-namespace.svg]] #MintCream {
}
class UnparsableStmt [[UnparsableStmt-diagram-detailed-grouped-per-namespace.svg]] #MintCream {
}
class VariableDeclarationExpr [[VariableDeclarationExpr-diagram-detailed-grouped-per-namespace.svg]] #MintCream {
}
class VoidType [[VoidType-diagram-detailed-grouped-per-namespace.svg]] #MintCream {
}
class WhileStmt [[WhileStmt-diagram-detailed-grouped-per-namespace.svg]] #MintCream {
}
class WildcardType [[WildcardType-diagram-detailed-grouped-per-namespace.svg]] #MintCream {
}
' Closing all previous_sub_namespace_list namespace None because file analysis is finished.
namespace preadapter [[preadapter-diagram-detailed-grouped-per-namespace.svg]] {
class preadapter.Logger [[preadapter.Logger-diagram-detailed-grouped-per-namespace.svg]]  {
  + loggingType: preadapter.LoggingType
==
  - log(<font color="6060BB"></font>)
  - <font color="909090">log.result: String_BRQTO__BRQTC</font>
--
  + logError(<font color="6060BB"></font>)
  + logError(<font color="6060BB"></font>)
  + logWarning(<font color="6060BB"></font>)
  + logWarning(<font color="6060BB"></font>)
  + logInfo(<font color="6060BB"></font>)
  + logInfo(<font color="6060BB"></font>)
  + logDebug(<font color="6060BB"></font>)
  + logDebug(<font color="6060BB"></font>)
  + logTrace(<font color="6060BB"></font>)
  + logTrace(<font color="6060BB"></font>)
}
'Compared namespace preadapter [[preadapter-diagram-detailed-grouped-per-namespace.svg]] { with last element of }
' Closing all previous_sub_namespace_list namespace None because file analysis is finished.
' Closing namespace preadapter
}
namespace preadapter [[preadapter-diagram-detailed-grouped-per-namespace.svg]] {
namespace preadapter.domain [[preadapter.domain-diagram-detailed-grouped-per-namespace.svg]] {
  class preadapter.domain.Datastructure [[preadapter.domain.Datastructure-diagram-detailed-grouped-per-namespace.svg]] #yellow {
    + class_to_datastructure: dict[String,SubDataStructure]
    + namespace_to_datastructures: dict[String,list[SubDataStructure]]
    + namespace_to_namespace_list: dict[String,list[String]]
    + skip_types: list[String]
    + logger: preadapter.Logger
==
    + ResolveClassNames(<font color="6060BB"></font>)
    - <font color="909090">ResolveClassNames.variables: list_BRQTO_Variable_BRQTC</font>
    - <font color="909090">ResolveClassNames.variable: Variable</font>
    - <font color="909090">ResolveClassNames.method: Method</font>
    - <font color="909090">ResolveClassNames.subDataStructure: SubDataStructure</font>
--
    - CorrectClassScope(<font color="6060BB">CorrectClassScope:SubDataStructure, CorrectClassScope:list_BRQTO_String_BRQTC</font>)
--
    + GetFQDNForUsedClassName(<font color="6060BB">GetFQDNForUsedClassName:SubDataStructure</font>)
    - <font color="909090">GetFQDNForUsedClassName.classnameList: list_BRQTO_String_BRQTC</font>
    - <font color="909090">GetFQDNForUsedClassName.fittingClassNames: String_BRQTO__BRQTC</font>
    - <font color="909090">GetFQDNForUsedClassName.bestFittingClassNames: String_BRQTO__BRQTC</font>
--
    + get_skip_types(<font color="6060BB"></font>)
    + append_sub_datastructure(<font color="6060BB">append_sub_datastructure:SubDataStructure</font>)
--
    + append_class(<font color="6060BB">append_class:list_BRQTO_String_BRQTC, append_class:list_BRQTO_String_BRQTC</font>)
    - <font color="909090">append_class.sub_datastructure: SubDataStructure</font>
--
    + get_classname_list(<font color="6060BB"></font>)
    + get_datastructures_from_class_name(<font color="6060BB"></font>)
  }
  class preadapter.domain.Datastructure_DOT_Method [[preadapter.domain.Datastructure_DOT_Method-diagram-detailed-grouped-per-namespace.svg]] #yellow {
  }
  class preadapter.domain.Datastructure_DOT_Static [[preadapter.domain.Datastructure_DOT_Static-diagram-detailed-grouped-per-namespace.svg]] #yellow {
  }
  class preadapter.domain.Datastructure_DOT_Variable [[preadapter.domain.Datastructure_DOT_Variable-diagram-detailed-grouped-per-namespace.svg]] #yellow {
  }
  class preadapter.domain.Datastructure_DOT_SubDataStructure [[preadapter.domain.Datastructure_DOT_SubDataStructure-diagram-detailed-grouped-per-namespace.svg]] #yellow {
  }
  class preadapter.domain.ASTVisitor [[preadapter.domain.ASTVisitor-diagram-detailed-grouped-per-namespace.svg]] #yellow {
    + logger: preadapter.Logger
    + datastructure: preadapter.domain.Datastructure
    + activeMethodList: list[String]
    + activeClassnameList: list[String]
    + namespaceList: list[String]
    + allUsing: list[String]
    + usingDict: dict[String,String]
    + deepness: HandleDeepness
    + ignoreType: list[String]
==
    + SimplifyType(<font color="6060BB"></font>)
    + cleanClassName(<font color="6060BB"></font>)
--
    + CreateClassInterface(<font color="6060BB">CreateClassInterface:ClassOrInterfaceDeclaration</font>)
    - <font color="909090">CreateClassInterface.parentSubDataStructure: preadapter.domain.Datastructure_DOT_SubDataStructure</font>
    - <font color="909090">CreateClassInterface.subDataStructure: preadapter.domain.Datastructure_DOT_SubDataStructure</font>
--
    + visit(<font color="6060BB">visit:MethodDeclaration, visit:Void</font>)
    - <font color="909090">visit.subDataStructure: preadapter.domain.Datastructure_DOT_SubDataStructure</font>
    - <font color="909090">visit.argumentsTuple: list_BRQTO_tuple_BRQTO_String_COMMA_String_COMMA_String_BRQTC_BRQTC</font>
    - <font color="909090">visit.argument: Optional_DOT_empty</font>
    - <font color="909090">visit.subDataStructure: preadapter.domain.Datastructure_DOT_SubDataStructure</font>
    - <font color="909090">visit.variableDeclarator: VariableDeclarator</font>
    - <font color="909090">visit.subDataStructure: preadapter.domain.Datastructure_DOT_SubDataStructure</font>
    - <font color="909090">visit.subDataStructureParent: preadapter.domain.Datastructure_DOT_SubDataStructure</font>
    - <font color="909090">visit.subDataStructureChild: preadapter.domain.Datastructure_DOT_SubDataStructure</font>
    - <font color="909090">visit.subDataStructureParent: preadapter.domain.Datastructure_DOT_SubDataStructure</font>
    - <font color="909090">visit.variableName: n_DOT_getNameAsString_BRQTO__BRQTC</font>
    - <font color="909090">visit.variableType: n_DOT_getTypeAsString_BRQTO__BRQTC</font>
    - <font color="909090">visit.initializer: n_DOT_getInitializer_BRQTO__BRQTC_DOT_toString_BRQTO__BRQTC</font>
    - <font color="909090">visit.method: preadapter.domain.Datastructure_DOT_Method</font>
--
    + visit(<font color="6060BB">visit:ClassOrInterfaceDeclaration, visit:Void</font>)
    + visit(<font color="6060BB">visit:FieldDeclaration, visit:Void</font>)
    + visit(<font color="6060BB">visit:PackageDeclaration, visit:Void</font>)
    + visit(<font color="6060BB">visit:ImportDeclaration, visit:Void</font>)
    + visit(<font color="6060BB">visit:EnumConstantDeclaration, visit:Void</font>)
    + visit(<font color="6060BB">visit:EnumDeclaration, visit:Void</font>)
    + visit(<font color="6060BB">visit:VariableDeclarator, visit:Void</font>)
--
    + main(<font color="6060BB">main:String_BRQTO__BRQTC</font>)
    - <font color="909090">main.cu: CompilationUnit</font>
--
  }
  class preadapter.domain.ASTVisitor_DOT_ObjectType [[preadapter.domain.ASTVisitor_DOT_ObjectType-diagram-detailed-grouped-per-namespace.svg]] #yellow {
  }
  class preadapter.domain.ASTVisitor_DOT_HandleDeepness [[preadapter.domain.ASTVisitor_DOT_HandleDeepness-diagram-detailed-grouped-per-namespace.svg]] #yellow {
  }
  class preadapter.domain.Datastructure_DOT_Method_DOT_ParameterType [[preadapter.domain.Datastructure_DOT_Method_DOT_ParameterType-diagram-detailed-grouped-per-namespace.svg]] #yellow {
  }
  class preadapter.domain.Datastructure_DOT_Method_DOT_Variable [[preadapter.domain.Datastructure_DOT_Method_DOT_Variable-diagram-detailed-grouped-per-namespace.svg]] #yellow {
  }
  class preadapter.domain.ASTVisitorDebug_DOT_HandleDeepness [[preadapter.domain.ASTVisitorDebug_DOT_HandleDeepness-diagram-detailed-grouped-per-namespace.svg]] #yellow {
  }
  class preadapter.domain.ASTVisitorDebug [[preadapter.domain.ASTVisitorDebug-diagram-detailed-grouped-per-namespace.svg]] #yellow {
    + out: PrintStream
    + deepness: HandleDeepness
==
    + visit(<font color="6060BB">visit:AnnotationDeclaration, visit:Void</font>)
    + visit(<font color="6060BB">visit:AnnotationMemberDeclaration, visit:Void</font>)
    + visit(<font color="6060BB">visit:ArrayAccessExpr, visit:Void</font>)
    + visit(<font color="6060BB">visit:ArrayCreationExpr, visit:Void</font>)
    + visit(<font color="6060BB">visit:ArrayCreationLevel, visit:Void</font>)
    + visit(<font color="6060BB">visit:ArrayInitializerExpr, visit:Void</font>)
    + visit(<font color="6060BB">visit:ArrayType, visit:Void</font>)
    + visit(<font color="6060BB">visit:AssertStmt, visit:Void</font>)
    + visit(<font color="6060BB">visit:AssignExpr, visit:Void</font>)
    + visit(<font color="6060BB">visit:BinaryExpr, visit:Void</font>)
    + visit(<font color="6060BB">visit:BlockComment, visit:Void</font>)
    + visit(<font color="6060BB">visit:BlockStmt, visit:Void</font>)
    + visit(<font color="6060BB">visit:BooleanLiteralExpr, visit:Void</font>)
    + visit(<font color="6060BB">visit:BreakStmt, visit:Void</font>)
    + visit(<font color="6060BB">visit:CastExpr, visit:Void</font>)
    + visit(<font color="6060BB">visit:CatchClause, visit:Void</font>)
    + visit(<font color="6060BB">visit:CharLiteralExpr, visit:Void</font>)
    + visit(<font color="6060BB">visit:ClassExpr, visit:Void</font>)
    + visit(<font color="6060BB">visit:ClassOrInterfaceDeclaration, visit:Void</font>)
    + visit(<font color="6060BB">visit:ClassOrInterfaceType, visit:Void</font>)
    + visit(<font color="6060BB">visit:CompilationUnit, visit:Void</font>)
    + visit(<font color="6060BB">visit:ConditionalExpr, visit:Void</font>)
    + visit(<font color="6060BB">visit:ConstructorDeclaration, visit:Void</font>)
    + visit(<font color="6060BB">visit:ContinueStmt, visit:Void</font>)
    + visit(<font color="6060BB">visit:DoStmt, visit:Void</font>)
    + visit(<font color="6060BB">visit:DoubleLiteralExpr, visit:Void</font>)
    + visit(<font color="6060BB">visit:EmptyStmt, visit:Void</font>)
    + visit(<font color="6060BB">visit:EnclosedExpr, visit:Void</font>)
    + visit(<font color="6060BB">visit:EnumConstantDeclaration, visit:Void</font>)
    + visit(<font color="6060BB">visit:EnumDeclaration, visit:Void</font>)
    + visit(<font color="6060BB">visit:ExplicitConstructorInvocationStmt, visit:Void</font>)
    + visit(<font color="6060BB">visit:ExpressionStmt, visit:Void</font>)
    + visit(<font color="6060BB">visit:FieldAccessExpr, visit:Void</font>)
    + visit(<font color="6060BB">visit:FieldDeclaration, visit:Void</font>)
    + visit(<font color="6060BB">visit:ForEachStmt, visit:Void</font>)
    + visit(<font color="6060BB">visit:ForStmt, visit:Void</font>)
    + visit(<font color="6060BB">visit:IfStmt, visit:Void</font>)
    + visit(<font color="6060BB">visit:ImportDeclaration, visit:Void</font>)
    + visit(<font color="6060BB">visit:InitializerDeclaration, visit:Void</font>)
    + visit(<font color="6060BB">visit:InstanceOfExpr, visit:Void</font>)
    + visit(<font color="6060BB">visit:IntegerLiteralExpr, visit:Void</font>)
    + visit(<font color="6060BB">visit:IntersectionType, visit:Void</font>)
    + visit(<font color="6060BB">visit:JavadocComment, visit:Void</font>)
    + visit(<font color="6060BB">visit:LabeledStmt, visit:Void</font>)
    + visit(<font color="6060BB">visit:LambdaExpr, visit:Void</font>)
    + visit(<font color="6060BB">visit:LineComment, visit:Void</font>)
    + visit(<font color="6060BB">visit:LocalClassDeclarationStmt, visit:Void</font>)
    + visit(<font color="6060BB">visit:LongLiteralExpr, visit:Void</font>)
    + visit(<font color="6060BB">visit:MarkerAnnotationExpr, visit:Void</font>)
    + visit(<font color="6060BB">visit:MemberValuetuple, visit:Void</font>)
    + visit(<font color="6060BB">visit:MethodCallExpr, visit:Void</font>)
    + visit(<font color="6060BB">visit:MethodDeclaration, visit:Void</font>)
    + visit(<font color="6060BB">visit:MethodReferenceExpr, visit:Void</font>)
    + visit(<font color="6060BB">visit:ModuleDeclaration, visit:Void</font>)
    + visit(<font color="6060BB">visit:ModuleExportsDirective, visit:Void</font>)
    + visit(<font color="6060BB">visit:ModuleOpensDirective, visit:Void</font>)
    + visit(<font color="6060BB">visit:ModuleProvidesDirective, visit:Void</font>)
    + visit(<font color="6060BB">visit:ModuleRequiresDirective, visit:Void</font>)
    + visit(<font color="6060BB">visit:ModuleUsesDirective, visit:Void</font>)
    + visit(<font color="6060BB">visit:Name, visit:Void</font>)
    + visit(<font color="6060BB">visit:NameExpr, visit:Void</font>)
    + visit(<font color="6060BB">visit:Nodelist, visit:Void</font>)
    + visit(<font color="6060BB">visit:NormalAnnotationExpr, visit:Void</font>)
    + visit(<font color="6060BB">visit:NullLiteralExpr, visit:Void</font>)
    + visit(<font color="6060BB">visit:ObjectCreationExpr, visit:Void</font>)
    + visit(<font color="6060BB">visit:PackageDeclaration, visit:Void</font>)
    + visit(<font color="6060BB">visit:Parameter, visit:Void</font>)
    + visit(<font color="6060BB">visit:PrimitiveType, visit:Void</font>)
    + visit(<font color="6060BB">visit:ReturnStmt, visit:Void</font>)
    + visit(<font color="6060BB">visit:SimpleName, visit:Void</font>)
    + visit(<font color="6060BB">visit:SingleMemberAnnotationExpr, visit:Void</font>)
    + visit(<font color="6060BB">visit:StringLiteralExpr, visit:Void</font>)
    + visit(<font color="6060BB">visit:SuperExpr, visit:Void</font>)
    + visit(<font color="6060BB">visit:SwitchEntry, visit:Void</font>)
    + visit(<font color="6060BB">visit:SwitchStmt, visit:Void</font>)
    + visit(<font color="6060BB">visit:SynchronizedStmt, visit:Void</font>)
    + visit(<font color="6060BB">visit:ThisExpr, visit:Void</font>)
    + visit(<font color="6060BB">visit:ThrowStmt, visit:Void</font>)
    + visit(<font color="6060BB">visit:TryStmt, visit:Void</font>)
    + visit(<font color="6060BB">visit:TypeExpr, visit:Void</font>)
    + visit(<font color="6060BB">visit:TypeParameter, visit:Void</font>)
    + visit(<font color="6060BB">visit:UnaryExpr, visit:Void</font>)
    + visit(<font color="6060BB">visit:UnionType, visit:Void</font>)
    + visit(<font color="6060BB">visit:UnknownType, visit:Void</font>)
    + visit(<font color="6060BB">visit:UnparsableStmt, visit:Void</font>)
    + visit(<font color="6060BB">visit:VariableDeclarationExpr, visit:Void</font>)
    + visit(<font color="6060BB">visit:VariableDeclarator, visit:Void</font>)
    + visit(<font color="6060BB">visit:VoidType, visit:Void</font>)
    + visit(<font color="6060BB">visit:WhileStmt, visit:Void</font>)
    + visit(<font color="6060BB">visit:WildcardType, visit:Void</font>)
--
    + main(<font color="6060BB">main:String_BRQTO__BRQTC</font>)
    - <font color="909090">main.cu: CompilationUnit</font>
--
  }
'Compared namespace preadapter.domain [[preadapter.domain-diagram-detailed-grouped-per-namespace.svg]] { with last element of   }
' Closing all previous_sub_namespace_list namespace None because file analysis is finished.
' Closing namespace domain
}
' Closing namespace preadapter
}
namespace preadapter [[preadapter-diagram-detailed-grouped-per-namespace.svg]] {
namespace preadapter.infrastructure [[preadapter.infrastructure-diagram-detailed-grouped-per-namespace.svg]] {
  class preadapter.infrastructure.CreateYML [[preadapter.infrastructure.CreateYML-diagram-detailed-grouped-per-namespace.svg]]  {
    + dummperOptions: DumperOptions.FlowStyle
    + startMark: Mark
    + endMark: Mark
==
    - appendTupleNodeValueSequenceNode(<font color="6060BB">appendTupleNodeValueSequenceNode:dictpingNode, appendTupleNodeValueSequenceNode:SequenceNode</font>)
    - appendTupleNodeValueString(<font color="6060BB">appendTupleNodeValueString:dictpingNode</font>)
--
    - appendTupleNodeValueStringToSequenceNode(<font color="6060BB">appendTupleNodeValueStringToSequenceNode:SequenceNode</font>)
    - <font color="909090">appendTupleNodeValueStringToSequenceNode.mappingNode: dictpingNode_BRQTO_Tag_DOT_MAP_COMMA__SPC_Arraylist_BRQTO__BRQTC_BRQTO__BRQTC_COMMA__SPC_dummperOptions_BRQTC</font>
--
    - appendSequence(<font color="6060BB">appendSequence:dictpingNode, appendSequence:list_BRQTO_String_BRQTC</font>)
    - <font color="909090">appendSequence.subSequenceNode: SequenceNode</font>
--
    + Create(<font color="6060BB">Create:preadapter.domain.Datastructure, Create:preadapter.Logger</font>)
    - <font color="909090">Create.subDataStructureSequenceYmlNode: SequenceNode_BRQTO_Tag_DOT_SEQ_COMMA__SPC_Arraylist_BRQTO__BRQTC_BRQTO__BRQTC_COMMA__SPC_dummperOptions_BRQTC</font>
    - <font color="909090">Create.subDataStructureMappingYmlNode: dictpingNode_BRQTO_Tag_DOT_MAP_COMMA__SPC_Arraylist_BRQTO__BRQTC_BRQTO__BRQTC_COMMA__SPC_dummperOptions_BRQTC</font>
    - <font color="909090">Create.subDataStructure: preadapter.domain.Datastructure_DOT_SubDataStructure</font>
    - <font color="909090">Create.fromImportsSequenceNode: SequenceNode_BRQTO_Tag_DOT_SEQ_COMMA__SPC_Arraylist_BRQTO__BRQTC_BRQTO__BRQTC_COMMA__SPC_dummperOptions_BRQTC</font>
    - <font color="909090">Create.fromImportsMappingNode: dictpingNode_BRQTO_Tag_DOT_MAP_COMMA__SPC_Arraylist_BRQTO__BRQTC_BRQTO__BRQTC_COMMA__SPC_dummperOptions_BRQTC</font>
    - <font color="909090">Create.staticsSequenceNode: SequenceNode_BRQTO_Tag_DOT_SEQ_COMMA__SPC_Arraylist_BRQTO__BRQTC_BRQTO__BRQTC_COMMA__SPC_dummperOptions_BRQTC</font>
    - <font color="909090">Create.staticsMappingNode: dictpingNode_BRQTO_Tag_DOT_MAP_COMMA__SPC_Arraylist_BRQTO__BRQTC_BRQTO__BRQTC_COMMA__SPC_dummperOptions_BRQTC</font>
    - <font color="909090">Create.variablesSequenceNode: SequenceNode_BRQTO_Tag_DOT_SEQ_COMMA__SPC_Arraylist_BRQTO__BRQTC_BRQTO__BRQTC_COMMA__SPC_dummperOptions_BRQTC</font>
    - <font color="909090">Create.variablesMappingNode: dictpingNode_BRQTO_Tag_DOT_MAP_COMMA__SPC_Arraylist_BRQTO__BRQTC_BRQTO__BRQTC_COMMA__SPC_dummperOptions_BRQTC</font>
    - <font color="909090">Create.methodsSequenceNode: SequenceNode_BRQTO_Tag_DOT_SEQ_COMMA__SPC_Arraylist_BRQTO__BRQTC_BRQTO__BRQTC_COMMA__SPC_dummperOptions_BRQTC</font>
    - <font color="909090">Create.parameters: SequenceNode_BRQTO_Tag_DOT_SEQ_COMMA__SPC_Arraylist_BRQTO__BRQTC_BRQTO__BRQTC_COMMA__SPC_dummperOptions_BRQTC</font>
    - <font color="909090">Create.methodParametersMappingNode: dictpingNode_BRQTO_Tag_DOT_MAP_COMMA__SPC_Arraylist_BRQTO__BRQTC_BRQTO__BRQTC_COMMA__SPC_dummperOptions_BRQTC</font>
    - <font color="909090">Create.methodVariables: SequenceNode_BRQTO_Tag_DOT_SEQ_COMMA__SPC_Arraylist_BRQTO__BRQTC_BRQTO__BRQTC_COMMA__SPC_dummperOptions_BRQTC</font>
    - <font color="909090">Create.methodVariablesMappingNode: dictpingNode_BRQTO_Tag_DOT_MAP_COMMA__SPC_Arraylist_BRQTO__BRQTC_BRQTO__BRQTC_COMMA__SPC_dummperOptions_BRQTC</font>
    - <font color="909090">Create.methodNode: dictpingNode_BRQTO_Tag_DOT_MAP_COMMA__SPC_Arraylist_BRQTO__BRQTC_BRQTO__BRQTC_COMMA__SPC_dummperOptions_BRQTC</font>
    - <font color="909090">Create.tmpMappingNode: dictpingNode_BRQTO_Tag_DOT_MAP_COMMA__SPC_Arraylist_BRQTO__BRQTC_BRQTO__BRQTC_COMMA__SPC_dummperOptions_BRQTC</font>
    - <font color="909090">Create.yaml: Yaml</font>
    - <font color="909090">Create.writer: PrintWriter</font>
--
  }
'Compared namespace preadapter.infrastructure [[preadapter.infrastructure-diagram-detailed-grouped-per-namespace.svg]] { with last element of   }
' Closing all previous_sub_namespace_list namespace None because file analysis is finished.
' Closing namespace infrastructure
}
' Closing namespace preadapter
}
namespace preadapter [[preadapter-diagram-detailed-grouped-per-namespace.svg]] {
namespace preadapter.service [[preadapter.service-diagram-detailed-grouped-per-namespace.svg]] {
  class preadapter.service.AnalyzeAST [[preadapter.service.AnalyzeAST-diagram-detailed-grouped-per-namespace.svg]]  {
    + SearchRecurseCSharpToYAML(<font color="6060BB">SearchRecurseCSharpToYAML:preadapter.Logger</font>)
    - <font color="909090">SearchRecurseCSharpToYAML.datastructure: preadapter.domain.Datastructure</font>
    - <font color="909090">SearchRecurseCSharpToYAML.recurseFileProcess: RecursiveFileProcessor_BRQTO__BRQTC</font>
    - <font color="909090">SearchRecurseCSharpToYAML.listFilePaths: list_BRQTO_String_BRQTC</font>
    - <font color="909090">SearchRecurseCSharpToYAML.cu: CompilationUnit</font>
--
  }
'Compared namespace preadapter.service [[preadapter.service-diagram-detailed-grouped-per-namespace.svg]] { with last element of   }
' Closing all previous_sub_namespace_list namespace None because file analysis is finished.
' Closing namespace service
}
' Closing namespace preadapter
}
 ' *************************************** 
 ' *************************************** 
 ' *************************************** 
' Class relations extracted from namespace:
' 
' Class relations extracted from namespace:
' preadapter
preadapter.Logger -[#909090]-> String_BRQTO__BRQTC  : uses 
' Class relations extracted from namespace:
' preadapter.domain
preadapter.domain.Datastructure +-[#10BBBB]- preadapter.domain.Datastructure_DOT_Method 
preadapter.domain.Datastructure +-[#10BBBB]- preadapter.domain.Datastructure_DOT_Static 
preadapter.domain.Datastructure +-[#10BBBB]- preadapter.domain.Datastructure_DOT_Variable 
preadapter.domain.Datastructure +-[#10BBBB]- preadapter.domain.Datastructure_DOT_SubDataStructure 
preadapter.domain.Datastructure .[#6060BB].> preadapter.Logger  : uses 
preadapter.domain.Datastructure -[#909090]-> list_BRQTO_Variable_BRQTC  : uses 
preadapter.domain.Datastructure -[#909090]-> Variable  : uses 
preadapter.domain.Datastructure -[#909090]-> Method  : uses 
preadapter.domain.Datastructure -[#909090]-> SubDataStructure  : uses 
preadapter.domain.Datastructure .[#6060BB].> SubDataStructure  : uses 
preadapter.domain.Datastructure .[#6060BB].> list_BRQTO_String_BRQTC  : uses 
preadapter.domain.Datastructure -[#909090]-> list_BRQTO_String_BRQTC  : uses 
preadapter.domain.Datastructure -[#909090]-> String_BRQTO__BRQTC  : uses 
preadapter.domain.Datastructure_DOT_Method +-[#10BBBB]- preadapter.domain.Datastructure_DOT_Method_DOT_ParameterType 
preadapter.domain.Datastructure_DOT_Method +-[#10BBBB]- preadapter.domain.Datastructure_DOT_Method_DOT_Variable 
VoidVisitorAdapter_BRQTO_Void_BRQTC <|-[#red]- preadapter.domain.ASTVisitor
preadapter.domain.ASTVisitor +-[#10BBBB]- preadapter.domain.ASTVisitor_DOT_ObjectType 
preadapter.domain.ASTVisitor +-[#10BBBB]- preadapter.domain.ASTVisitor_DOT_HandleDeepness 
preadapter.domain.ASTVisitor .[#6060BB].> preadapter.Logger  : uses 
preadapter.domain.ASTVisitor .[#6060BB].> preadapter.domain.Datastructure  : uses 
preadapter.domain.ASTVisitor .[#6060BB].> HandleDeepness  : uses 
preadapter.domain.ASTVisitor .[#6060BB].> ClassOrInterfaceDeclaration  : uses 
preadapter.domain.ASTVisitor -[#909090]-> preadapter.domain.Datastructure_DOT_SubDataStructure  : uses 
preadapter.domain.ASTVisitor .[#6060BB].> MethodDeclaration  : uses 
preadapter.domain.ASTVisitor .[#6060BB].> Void  : uses 
preadapter.domain.ASTVisitor -[#909090]-> list_BRQTO_tuple_BRQTO_String_COMMA_String_COMMA_String_BRQTC_BRQTC  : uses 
preadapter.domain.ASTVisitor -[#909090]-> Optional_DOT_empty  : uses 
preadapter.domain.ASTVisitor -[#909090]-> VariableDeclarator  : uses 
preadapter.domain.ASTVisitor -[#909090]-> n_DOT_getNameAsString_BRQTO__BRQTC  : uses 
preadapter.domain.ASTVisitor -[#909090]-> n_DOT_getTypeAsString_BRQTO__BRQTC  : uses 
preadapter.domain.ASTVisitor -[#909090]-> n_DOT_getInitializer_BRQTO__BRQTC_DOT_toString_BRQTO__BRQTC  : uses 
preadapter.domain.ASTVisitor -[#909090]-> preadapter.domain.Datastructure_DOT_Method  : uses 
preadapter.domain.ASTVisitor .[#6060BB].> FieldDeclaration  : uses 
preadapter.domain.ASTVisitor .[#6060BB].> PackageDeclaration  : uses 
preadapter.domain.ASTVisitor .[#6060BB].> ImportDeclaration  : uses 
preadapter.domain.ASTVisitor .[#6060BB].> EnumConstantDeclaration  : uses 
preadapter.domain.ASTVisitor .[#6060BB].> EnumDeclaration  : uses 
preadapter.domain.ASTVisitor .[#6060BB].> VariableDeclarator  : uses 
preadapter.domain.ASTVisitor .[#6060BB].> String_BRQTO__BRQTC  : uses 
preadapter.domain.ASTVisitor -[#909090]-> CompilationUnit  : uses 
VoidVisitorAdapter_BRQTO_Void_BRQTC <|-[#red]- preadapter.domain.ASTVisitorDebug
preadapter.domain.ASTVisitorDebug +-[#10BBBB]- preadapter.domain.ASTVisitorDebug_DOT_HandleDeepness 
preadapter.domain.ASTVisitorDebug .[#6060BB].> PrintStream  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> HandleDeepness  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> AnnotationDeclaration  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> Void  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> AnnotationMemberDeclaration  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> ArrayAccessExpr  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> ArrayCreationExpr  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> ArrayCreationLevel  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> ArrayInitializerExpr  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> ArrayType  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> AssertStmt  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> AssignExpr  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> BinaryExpr  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> BlockComment  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> BlockStmt  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> BooleanLiteralExpr  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> BreakStmt  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> CastExpr  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> CatchClause  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> CharLiteralExpr  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> ClassExpr  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> ClassOrInterfaceDeclaration  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> ClassOrInterfaceType  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> CompilationUnit  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> ConditionalExpr  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> ConstructorDeclaration  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> ContinueStmt  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> DoStmt  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> DoubleLiteralExpr  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> EmptyStmt  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> EnclosedExpr  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> EnumConstantDeclaration  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> EnumDeclaration  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> ExplicitConstructorInvocationStmt  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> ExpressionStmt  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> FieldAccessExpr  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> FieldDeclaration  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> ForEachStmt  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> ForStmt  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> IfStmt  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> ImportDeclaration  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> InitializerDeclaration  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> InstanceOfExpr  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> IntegerLiteralExpr  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> IntersectionType  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> JavadocComment  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> LabeledStmt  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> LambdaExpr  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> LineComment  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> LocalClassDeclarationStmt  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> LongLiteralExpr  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> MarkerAnnotationExpr  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> MemberValuetuple  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> MethodCallExpr  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> MethodDeclaration  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> MethodReferenceExpr  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> ModuleDeclaration  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> ModuleExportsDirective  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> ModuleOpensDirective  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> ModuleProvidesDirective  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> ModuleRequiresDirective  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> ModuleUsesDirective  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> Name  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> NameExpr  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> Nodelist  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> NormalAnnotationExpr  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> NullLiteralExpr  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> ObjectCreationExpr  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> PackageDeclaration  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> Parameter  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> PrimitiveType  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> ReturnStmt  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> SimpleName  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> SingleMemberAnnotationExpr  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> StringLiteralExpr  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> SuperExpr  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> SwitchEntry  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> SwitchStmt  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> SynchronizedStmt  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> ThisExpr  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> ThrowStmt  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> TryStmt  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> TypeExpr  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> TypeParameter  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> UnaryExpr  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> UnionType  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> UnknownType  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> UnparsableStmt  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> VariableDeclarationExpr  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> VariableDeclarator  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> VoidType  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> WhileStmt  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> WildcardType  : uses 
preadapter.domain.ASTVisitorDebug .[#6060BB].> String_BRQTO__BRQTC  : uses 
preadapter.domain.ASTVisitorDebug -[#909090]-> CompilationUnit  : uses 
' Class relations extracted from namespace:
' preadapter.infrastructure
preadapter.infrastructure.CreateYML .[#6060BB].> list_BRQTO_String_BRQTC  : uses 
preadapter.infrastructure.CreateYML .[#6060BB].> preadapter.domain.Datastructure  : uses 
preadapter.infrastructure.CreateYML .[#6060BB].> preadapter.Logger  : uses 
preadapter.infrastructure.CreateYML -[#909090]-> preadapter.domain.Datastructure_DOT_SubDataStructure  : uses 
' Class relations extracted from namespace:
' preadapter.service
preadapter.service.AnalyzeAST .[#6060BB].> preadapter.Logger  : uses 
preadapter.service.AnalyzeAST -[#909090]-> preadapter.domain.Datastructure  : uses 
preadapter.service.AnalyzeAST -[#909090]-> list_BRQTO_String_BRQTC  : uses 
preadapter.service.AnalyzeAST -[#909090]-> CompilationUnit  : uses 
@enduml