@startuml
title <size:20>TypeParameter **simplified** </size>
note "Your are analyzing:\nTypeParameter **simplified** \n\n==Filter==\nYou can click either the namespaces \nor class names for filtering them and their\ndirect dependencies.\n\n==Select other==\n* TypeParameter **detailed** :\n   [[TypeParameter-diagram-detailed.svg]]\n* Full diagram **simplified** and **grouped per namespace**:\n   [[full-diagram-simplified-grouped-per-namespace.svg]]\n* Home:\n   [[index.html]]" as FloatingNote
class TypeParameter [[TypeParameter-diagram-simplified.svg]] #yellow {
}
  class preadapter.domain.ASTVisitorDebug [[preadapter.domain.ASTVisitorDebug-diagram-simplified.svg]]  {
  }
 ' *************************************** 
 ' *************************************** 
 ' *************************************** 
' Class relations extracted from namespace:
' 
' Class relations extracted from namespace:
' preadapter.domain
preadapter.domain.ASTVisitorDebug .[#6060BB].> TypeParameter  : uses 
@enduml