@startuml
skinparam linetype ortho
title <size:20>DotNetPreAdapter.InnerClassBase **detailed** </size>
note "Your are analyzing:\nDotNetPreAdapter.InnerClassBase **detailed** \n\n==Filter==\nYou can click either the namespaces \nor class names for filtering them and their\ndirect dependencies.\n\n==Select other==\n* DotNetPreAdapter.InnerClassBase **simplified** :\n   [[DotNetPreAdapter.InnerClassBase-diagram-simplified.svg]]\n* Full diagram **detailed** and **grouped per namespace**:\n   [[full-diagram-detailed-grouped-per-namespace.svg]]\n* Home:\n   [[index.html]]" as FloatingNote
abstract class DotNetPreAdapter.InnerClassBase [[DotNetPreAdapter.InnerClassBase-diagram-detailed.svg]] #yellow {
}
abstract class DotNetPreAdapter.InnerClass [[DotNetPreAdapter.InnerClass-diagram-detailed.svg]]  {
  + unused(<font color="6060BB"></font>)
}
 ' *************************************** 
 ' *************************************** 
 ' *************************************** 
' Class relations extracted from namespace:
' DotNetPreAdapter
DotNetPreAdapter.InnerClassBase <|-[#red]- DotNetPreAdapter.InnerClass
@enduml