@startuml
skinparam linetype ortho
title <size:20>DotNetPreAdapter.Domain.ClassDeclarationSyntax **simplified** </size>
note "Your are analyzing:\nDotNetPreAdapter.Domain.ClassDeclarationSyntax **simplified** \n\n==Filter==\nYou can click either the namespaces \nor class names for filtering them and their\ndirect dependencies.\n\n==Select other==\n* DotNetPreAdapter.Domain.ClassDeclarationSyntax **detailed** :\n   [[DotNetPreAdapter.Domain.ClassDeclarationSyntax-diagram-detailed.svg]]\n* Full diagram **simplified** and **grouped per namespace**:\n   [[full-diagram-simplified-grouped-per-namespace.svg]]\n* Home:\n   [[index.html]]" as FloatingNote
class DotNetPreAdapter.Domain.ClassDeclarationSyntax [[DotNetPreAdapter.Domain.ClassDeclarationSyntax-diagram-simplified.svg]] #yellow {
}
  abstract class DotNetPreAdapter.Domain.ASTVisitor [[DotNetPreAdapter.Domain.ASTVisitor-diagram-simplified.svg]]  {
  }
 ' *************************************** 
 ' *************************************** 
 ' *************************************** 
' Class relations extracted from namespace:
' 
' Class relations extracted from namespace:
' DotNetPreAdapter.Domain
DotNetPreAdapter.Domain.ASTVisitor .[#6060BB].> DotNetPreAdapter.Domain.ClassDeclarationSyntax  : uses 
@enduml