@startuml
skinparam linetype ortho
title <size:20>DotNetPreAdapter.RecursiveFileProcessor **detailed** </size>
note "Your are analyzing:\nDotNetPreAdapter.RecursiveFileProcessor **detailed** \n\n==Filter==\nYou can click either the namespaces \nor class names for filtering them and their\ndirect dependencies.\n\n==Select other==\n* DotNetPreAdapter.RecursiveFileProcessor **simplified** :\n   [[DotNetPreAdapter.RecursiveFileProcessor-diagram-simplified.svg]]\n* Full diagram **detailed** and **grouped per namespace**:\n   [[full-diagram-detailed-grouped-per-namespace.svg]]\n* Home:\n   [[index.html]]" as FloatingNote
  abstract class DotNetPreAdapter.RecursiveFileProcessor.InnerClass [[DotNetPreAdapter.RecursiveFileProcessor.InnerClass-diagram-detailed.svg]] #yellow {
  }
 ' *************************************** 
 ' *************************************** 
 ' *************************************** 
' Class relations extracted from namespace:
' DotNetPreAdapter.RecursiveFileProcessor
@enduml