@startuml
skinparam linetype ortho
title <size:20>DotNetPreAdapter.Domain.ASTVisitor **simplified** and **grouped per namespace**</size>
note "Your are analyzing:\nDotNetPreAdapter.Domain.ASTVisitor **simplified** and **grouped per namespace**\n\n==Filter==\nYou can click either the namespaces \nor class names for filtering them and their\ndirect dependencies.\n\n==Select other==\n* DotNetPreAdapter.Domain.ASTVisitor **detailed** and **grouped per namespace**:\n   [[DotNetPreAdapter.Domain.ASTVisitor-diagram-detailed-grouped-per-namespace.svg]]\n* Full diagram **simplified** and **grouped per namespace**:\n   [[full-diagram-simplified-grouped-per-namespace.svg]]\n* Home:\n   [[index.html]]" as FloatingNote
class CSharpSyntaxWalker [[CSharpSyntaxWalker-diagram-simplified-grouped-per-namespace.svg]] #MintCream {
}
class SemanticModel [[SemanticModel-diagram-simplified-grouped-per-namespace.svg]] #MintCream {
}
class SyntaxNode [[SyntaxNode-diagram-simplified-grouped-per-namespace.svg]] #MintCream {
}
class ITypeSymbol [[ITypeSymbol-diagram-simplified-grouped-per-namespace.svg]] #MintCream {
}
class T [[T-diagram-simplified-grouped-per-namespace.svg]] #MintCream {
}
class NamespaceDeclarationSyntax [[NamespaceDeclarationSyntax-diagram-simplified-grouped-per-namespace.svg]] #MintCream {
}
class UsingDirectiveSyntax [[UsingDirectiveSyntax-diagram-simplified-grouped-per-namespace.svg]] #MintCream {
}
class EnumDeclarationSyntax [[EnumDeclarationSyntax-diagram-simplified-grouped-per-namespace.svg]] #MintCream {
}
class InterfaceDeclarationSyntax [[InterfaceDeclarationSyntax-diagram-simplified-grouped-per-namespace.svg]] #MintCream {
}
class ClassDeclarationSyntax [[ClassDeclarationSyntax-diagram-simplified-grouped-per-namespace.svg]] #MintCream {
}
class MethodDeclarationSyntax [[MethodDeclarationSyntax-diagram-simplified-grouped-per-namespace.svg]] #MintCream {
}
class IParameterSymbol [[IParameterSymbol-diagram-simplified-grouped-per-namespace.svg]] #MintCream {
}
class VariableDeclarationSyntax [[VariableDeclarationSyntax-diagram-simplified-grouped-per-namespace.svg]] #MintCream {
}
class IAliasSymbol [[IAliasSymbol-diagram-simplified-grouped-per-namespace.svg]] #MintCream {
}
' Closing all previous_sub_namespace_list namespace None because file analysis is finished.
namespace DotNetPreAdapter [[DotNetPreAdapter-diagram-simplified-grouped-per-namespace.svg]] {
namespace DotNetPreAdapter.Domain [[DotNetPreAdapter.Domain-diagram-simplified-grouped-per-namespace.svg]] {
  abstract class DotNetPreAdapter.Domain.ASTVisitor [[DotNetPreAdapter.Domain.ASTVisitor-diagram-simplified-grouped-per-namespace.svg]] #yellow {
  }
  abstract class DotNetPreAdapter.Domain.Datastructure [[DotNetPreAdapter.Domain.Datastructure-diagram-simplified-grouped-per-namespace.svg]]  {
  }
  abstract class DotNetPreAdapter.Domain.Datastructure_DOT_SubDataStructure [[DotNetPreAdapter.Domain.Datastructure.SubDataStructure-diagram-simplified-grouped-per-namespace.svg]]  {
  }
  abstract class DotNetPreAdapter.Domain.Datastructure_DOT_Method [[DotNetPreAdapter.Domain.Datastructure.Method-diagram-simplified-grouped-per-namespace.svg]]  {
  }
'Compared namespace DotNetPreAdapter.Domain [[DotNetPreAdapter.Domain-diagram-simplified-grouped-per-namespace.svg]] { with last element of   }
' Closing all previous_sub_namespace_list namespace None because file analysis is finished.
' Closing namespace Domain
}
' Closing namespace DotNetPreAdapter
}
namespace DotNetPreAdapter [[DotNetPreAdapter-diagram-simplified-grouped-per-namespace.svg]] {
namespace DotNetPreAdapter.Service [[DotNetPreAdapter.Service-diagram-simplified-grouped-per-namespace.svg]] {
  abstract class DotNetPreAdapter.Service.AnalyzeAST [[DotNetPreAdapter.Service.AnalyzeAST-diagram-simplified-grouped-per-namespace.svg]]  {
  }
'Compared namespace DotNetPreAdapter.Service [[DotNetPreAdapter.Service-diagram-simplified-grouped-per-namespace.svg]] { with last element of   }
' Closing all previous_sub_namespace_list namespace None because file analysis is finished.
' Closing namespace Service
}
' Closing namespace DotNetPreAdapter
}
namespace DotNetPreAdapter [[DotNetPreAdapter-diagram-simplified-grouped-per-namespace.svg]] {
namespace DotNetPreAdapter.Utils [[DotNetPreAdapter.Utils-diagram-simplified-grouped-per-namespace.svg]] {
  abstract class DotNetPreAdapter.Utils.Logger [[DotNetPreAdapter.Utils.Logger-diagram-simplified-grouped-per-namespace.svg]]  {
  }
'Compared namespace DotNetPreAdapter.Utils [[DotNetPreAdapter.Utils-diagram-simplified-grouped-per-namespace.svg]] { with last element of   }
' Closing all previous_sub_namespace_list namespace None because file analysis is finished.
' Closing namespace Utils
}
' Closing namespace DotNetPreAdapter
}
 ' *************************************** 
 ' *************************************** 
 ' *************************************** 
' Class relations extracted from namespace:
' 
' Class relations extracted from namespace:
' DotNetPreAdapter.Domain
CSharpSyntaxWalker <|-[#red]- DotNetPreAdapter.Domain.ASTVisitor
DotNetPreAdapter.Domain.ASTVisitor *-[#10BB10]- DotNetPreAdapter.Domain.Datastructure 
DotNetPreAdapter.Domain.ASTVisitor *-[#10BB10]- SemanticModel 
DotNetPreAdapter.Domain.ASTVisitor *-[#10BB10]- DotNetPreAdapter.Utils.Logger 
DotNetPreAdapter.Domain.ASTVisitor .[#6060BB].> SyntaxNode  : uses 
DotNetPreAdapter.Domain.ASTVisitor -[#909090]-> ITypeSymbol  : uses 
DotNetPreAdapter.Domain.ASTVisitor .[#6060BB].> T  : uses 
DotNetPreAdapter.Domain.ASTVisitor -[#909090]-> DotNetPreAdapter.Domain.Datastructure_DOT_SubDataStructure  : uses 
DotNetPreAdapter.Domain.ASTVisitor .[#6060BB].> NamespaceDeclarationSyntax  : uses 
DotNetPreAdapter.Domain.ASTVisitor .[#6060BB].> UsingDirectiveSyntax  : uses 
DotNetPreAdapter.Domain.ASTVisitor .[#6060BB].> EnumDeclarationSyntax  : uses 
DotNetPreAdapter.Domain.ASTVisitor .[#6060BB].> InterfaceDeclarationSyntax  : uses 
DotNetPreAdapter.Domain.ASTVisitor .[#6060BB].> ClassDeclarationSyntax  : uses 
DotNetPreAdapter.Domain.ASTVisitor .[#6060BB].> MethodDeclarationSyntax  : uses 
DotNetPreAdapter.Domain.ASTVisitor -[#909090]-> IParameterSymbol  : uses 
DotNetPreAdapter.Domain.ASTVisitor .[#6060BB].> VariableDeclarationSyntax  : uses 
DotNetPreAdapter.Domain.ASTVisitor -[#909090]-> IAliasSymbol  : uses 
DotNetPreAdapter.Domain.ASTVisitor -[#909090]-> DotNetPreAdapter.Domain.Datastructure_DOT_Method  : uses 
DotNetPreAdapter.Domain.Datastructure +-[#10BBBB]- DotNetPreAdapter.Domain.Datastructure_DOT_Method 
DotNetPreAdapter.Domain.Datastructure +-[#10BBBB]- DotNetPreAdapter.Domain.Datastructure_DOT_SubDataStructure 
DotNetPreAdapter.Domain.Datastructure *-[#10BB10]- DotNetPreAdapter.Utils.Logger 
DotNetPreAdapter.Domain.Datastructure .[#6060BB].> DotNetPreAdapter.Domain.Datastructure_DOT_SubDataStructure  : uses 
DotNetPreAdapter.Domain.Datastructure -[#909090]-> DotNetPreAdapter.Domain.Datastructure_DOT_SubDataStructure  : uses 
' Class relations extracted from namespace:
' DotNetPreAdapter.Service
DotNetPreAdapter.Service.AnalyzeAST .[#6060BB].> DotNetPreAdapter.Utils.Logger  : uses 
DotNetPreAdapter.Service.AnalyzeAST -[#909090]-> DotNetPreAdapter.Domain.Datastructure  : uses 
DotNetPreAdapter.Service.AnalyzeAST -[#909090]-> SemanticModel  : uses 
DotNetPreAdapter.Service.AnalyzeAST -[#909090]-> DotNetPreAdapter.Domain.ASTVisitor  : uses 
' Class relations extracted from namespace:
' DotNetPreAdapter.Utils
@enduml