@startuml
skinparam linetype ortho
title <size:20>DotNetPreAdapter.Domain.ITypeSymbol **simplified** </size>
note "Your are analyzing:\nDotNetPreAdapter.Domain.ITypeSymbol **simplified** \n\n==Filter==\nYou can click either the namespaces \nor class names for filtering them and their\ndirect dependencies.\n\n==Select other==\n* DotNetPreAdapter.Domain.ITypeSymbol **detailed** :\n   [[DotNetPreAdapter.Domain.ITypeSymbol-diagram-detailed.svg]]\n* Full diagram **simplified** and **grouped per namespace**:\n   [[full-diagram-simplified-grouped-per-namespace.svg]]\n* Home:\n   [[index.html]]" as FloatingNote
class DotNetPreAdapter.Domain.ITypeSymbol [[DotNetPreAdapter.Domain.ITypeSymbol-diagram-simplified.svg]] #yellow {
}
  abstract class DotNetPreAdapter.Domain.ASTVisitor [[DotNetPreAdapter.Domain.ASTVisitor-diagram-simplified.svg]]  {
  }
 ' *************************************** 
 ' *************************************** 
 ' *************************************** 
' Class relations extracted from namespace:
' 
' Class relations extracted from namespace:
' DotNetPreAdapter.Domain
DotNetPreAdapter.Domain.ASTVisitor -[#909090]-> DotNetPreAdapter.Domain.ITypeSymbol  : uses 
@enduml