@startuml
skinparam linetype ortho
title <size:20>DotNetPreAdapter.Domain.Datastructure.Static **simplified** and **grouped per namespace**</size>
note "Your are analyzing:\nDotNetPreAdapter.Domain.Datastructure.Static **simplified** and **grouped per namespace**\n\n==Filter==\nYou can click either the namespaces \nor class names for filtering them and their\ndirect dependencies.\n\n==Select other==\n* DotNetPreAdapter.Domain.Datastructure.Static **detailed** and **grouped per namespace**:\n   [[DotNetPreAdapter.Domain.Datastructure.Static-diagram-detailed-grouped-per-namespace.svg]]\n* Full diagram **simplified** and **grouped per namespace**:\n   [[full-diagram-simplified-grouped-per-namespace.svg]]\n* Home:\n   [[index.html]]" as FloatingNote
namespace DotNetPreAdapter [[DotNetPreAdapter-diagram-simplified-grouped-per-namespace.svg]] {
namespace DotNetPreAdapter.Domain [[DotNetPreAdapter.Domain-diagram-simplified-grouped-per-namespace.svg]] {
  abstract class DotNetPreAdapter.Domain.Datastructure_DOT_Static [[DotNetPreAdapter.Domain.Datastructure.Static-diagram-simplified-grouped-per-namespace.svg]] #yellow {
  }
  abstract class DotNetPreAdapter.Domain.Datastructure [[DotNetPreAdapter.Domain.Datastructure-diagram-simplified-grouped-per-namespace.svg]]  {
  }
'Compared namespace DotNetPreAdapter.Domain [[DotNetPreAdapter.Domain-diagram-simplified-grouped-per-namespace.svg]] { with last element of   }
' Closing all previous_sub_namespace_list namespace None because file analysis is finished.
' Closing namespace Domain
}
' Closing namespace DotNetPreAdapter
}
 ' *************************************** 
 ' *************************************** 
 ' *************************************** 
' Class relations extracted from namespace:
' DotNetPreAdapter.Domain
DotNetPreAdapter.Domain.Datastructure +-[#10BBBB]- DotNetPreAdapter.Domain.Datastructure_DOT_Static 
@enduml