@startuml
skinparam linetype ortho
title <size:20>DotNetPreAdapter.InnerClassBase **simplified** </size>
note "Your are analyzing:\nDotNetPreAdapter.InnerClassBase **simplified** \n\n==Filter==\nYou can click either the namespaces \nor class names for filtering them and their\ndirect dependencies.\n\n==Select other==\n* DotNetPreAdapter.InnerClassBase **detailed** :\n   [[DotNetPreAdapter.InnerClassBase-diagram-detailed.svg]]\n* Full diagram **simplified** and **grouped per namespace**:\n   [[full-diagram-simplified-grouped-per-namespace.svg]]\n* Home:\n   [[index.html]]" as FloatingNote
abstract class DotNetPreAdapter.InnerClassBase [[DotNetPreAdapter.InnerClassBase-diagram-simplified.svg]] #yellow {
}
abstract class DotNetPreAdapter.InnerClass [[DotNetPreAdapter.InnerClass-diagram-simplified.svg]]  {
}
 ' *************************************** 
 ' *************************************** 
 ' *************************************** 
' Class relations extracted from namespace:
' DotNetPreAdapter
DotNetPreAdapter.InnerClassBase <|-[#red]- DotNetPreAdapter.InnerClass
@enduml