@startuml
skinparam linetype ortho
title <size:20>DotNetPreAdapter.Utils.LoggingType **detailed** and **grouped per namespace**</size>
note "Your are analyzing:\nDotNetPreAdapter.Utils.LoggingType **detailed** and **grouped per namespace**\n\n==Filter==\nYou can click either the namespaces \nor class names for filtering them and their\ndirect dependencies.\n\n==Select other==\n* DotNetPreAdapter.Utils.LoggingType **simplified** and **grouped per namespace**:\n   [[DotNetPreAdapter.Utils.LoggingType-diagram-simplified-grouped-per-namespace.svg]]\n* Full diagram **detailed** and **grouped per namespace**:\n   [[full-diagram-detailed-grouped-per-namespace.svg]]\n* Home:\n   [[index.html]]" as FloatingNote
class Enum [[Enum-diagram-detailed-grouped-per-namespace.svg]] #MintCream {
}
class IComparable [[IComparable-diagram-detailed-grouped-per-namespace.svg]] #MintCream {
}
class IFormattable [[IFormattable-diagram-detailed-grouped-per-namespace.svg]] #MintCream {
}
class IConvertible [[IConvertible-diagram-detailed-grouped-per-namespace.svg]] #MintCream {
}
' Closing all previous_sub_namespace_list namespace None because file analysis is finished.
namespace DotNetPreAdapter [[DotNetPreAdapter-diagram-detailed-grouped-per-namespace.svg]] {
namespace DotNetPreAdapter.Utils [[DotNetPreAdapter.Utils-diagram-detailed-grouped-per-namespace.svg]] {
  abstract class DotNetPreAdapter.Utils.LoggingType [[DotNetPreAdapter.Utils.LoggingType-diagram-detailed-grouped-per-namespace.svg]] #yellow {
  }
  abstract class DotNetPreAdapter.Utils.Logger [[DotNetPreAdapter.Utils.Logger-diagram-detailed-grouped-per-namespace.svg]]  {
    + loggingType: DotNetPreAdapter.Utils.LoggingType
==
    - log(<font color="6060BB"></font>)
    + LogError(<font color="6060BB"></font>)
    + LogWarning(<font color="6060BB"></font>)
    + LogInfo(<font color="6060BB"></font>)
    + LogDebug(<font color="6060BB"></font>)
    + LogTrace(<font color="6060BB"></font>)
  }
'Compared namespace DotNetPreAdapter.Utils [[DotNetPreAdapter.Utils-diagram-detailed-grouped-per-namespace.svg]] { with last element of   }
' Closing all previous_sub_namespace_list namespace None because file analysis is finished.
' Closing namespace Utils
}
' Closing namespace DotNetPreAdapter
}
 ' *************************************** 
 ' *************************************** 
 ' *************************************** 
' Class relations extracted from namespace:
' 
' Class relations extracted from namespace:
' DotNetPreAdapter.Utils
Enum <|-[#red]- DotNetPreAdapter.Utils.LoggingType
IComparable <|-[#red]- DotNetPreAdapter.Utils.LoggingType
IFormattable <|-[#red]- DotNetPreAdapter.Utils.LoggingType
IConvertible <|-[#red]- DotNetPreAdapter.Utils.LoggingType
DotNetPreAdapter.Utils.Logger *-[#10BB10]- DotNetPreAdapter.Utils.LoggingType 
@enduml