@startuml
skinparam linetype ortho
title <size:20>DotNetPreAdapter.RecursiveFileProcessor **simplified** and **grouped per namespace**</size>
note "Your are analyzing:\nDotNetPreAdapter.RecursiveFileProcessor **simplified** and **grouped per namespace**\n\n==Filter==\nYou can click either the namespaces \nor class names for filtering them and their\ndirect dependencies.\n\n==Select other==\n* DotNetPreAdapter.RecursiveFileProcessor **detailed** and **grouped per namespace**:\n   [[DotNetPreAdapter.RecursiveFileProcessor-diagram-detailed-grouped-per-namespace.svg]]\n* Full diagram **simplified** and **grouped per namespace**:\n   [[full-diagram-simplified-grouped-per-namespace.svg]]\n* Home:\n   [[index.html]]" as FloatingNote
namespace DotNetPreAdapter [[DotNetPreAdapter-diagram-simplified-grouped-per-namespace.svg]] {
namespace DotNetPreAdapter.RecursiveFileProcessor [[DotNetPreAdapter.RecursiveFileProcessor-diagram-simplified-grouped-per-namespace.svg]] {
  abstract class DotNetPreAdapter.RecursiveFileProcessor.InnerClass [[DotNetPreAdapter.RecursiveFileProcessor.InnerClass-diagram-simplified-grouped-per-namespace.svg]] #yellow {
  }
'Compared namespace DotNetPreAdapter.RecursiveFileProcessor [[DotNetPreAdapter.RecursiveFileProcessor-diagram-simplified-grouped-per-namespace.svg]] { with last element of   }
' Closing all previous_sub_namespace_list namespace None because file analysis is finished.
' Closing namespace RecursiveFileProcessor
}
' Closing namespace DotNetPreAdapter
}
 ' *************************************** 
 ' *************************************** 
 ' *************************************** 
' Class relations extracted from namespace:
' DotNetPreAdapter.RecursiveFileProcessor
@enduml