@startuml
skinparam linetype ortho
title <size:20>DotNetPreAdapter.RecursiveFileProcessor.InnerClass **simplified** </size>
note "Your are analyzing:\nDotNetPreAdapter.RecursiveFileProcessor.InnerClass **simplified** \n\n==Filter==\nYou can click either the namespaces \nor class names for filtering them and their\ndirect dependencies.\n\n==Select other==\n* DotNetPreAdapter.RecursiveFileProcessor.InnerClass **detailed** :\n   [[DotNetPreAdapter.RecursiveFileProcessor.InnerClass-diagram-detailed.svg]]\n* Full diagram **simplified** and **grouped per namespace**:\n   [[full-diagram-simplified-grouped-per-namespace.svg]]\n* Home:\n   [[index.html]]" as FloatingNote
  abstract class DotNetPreAdapter.RecursiveFileProcessor.InnerClass [[DotNetPreAdapter.RecursiveFileProcessor.InnerClass-diagram-simplified.svg]] #yellow {
  }
 ' *************************************** 
 ' *************************************** 
 ' *************************************** 
' Class relations extracted from namespace:
' DotNetPreAdapter.RecursiveFileProcessor
@enduml