@startuml
skinparam linetype ortho
title <size:20>Examples.BadDesign.CarExample.WarehouseEntities.Invoice **detailed** </size>
note "Your are analyzing:\nExamples.BadDesign.CarExample.WarehouseEntities.Invoice **detailed** \n\n==Filter==\nYou can click either the namespaces \nor class names for filtering them and their\ndirect dependencies.\n\n==Select other==\n* Examples.BadDesign.CarExample.WarehouseEntities.Invoice **simplified** :\n   [[Examples.BadDesign.CarExample.WarehouseEntities.Invoice-diagram-simplified.svg]]\n* Full diagram **detailed** and **grouped per namespace**:\n   [[full-diagram-detailed-grouped-per-namespace.svg]]\n* Home:\n   [[index.html]]" as FloatingNote
      abstract class Examples.BadDesign.CarExample.WarehouseEntities.Invoice [[Examples.BadDesign.CarExample.WarehouseEntities.Invoice-diagram-detailed.svg]] #yellow {
      }
 ' *************************************** 
 ' *************************************** 
 ' *************************************** 
' Class relations extracted from namespace:
' Examples.BadDesign.CarExample.WarehouseEntities
@enduml