@startuml
skinparam linetype ortho
title <size:20>Examples.BadDesign.CarExample.CarParts.Doors **detailed** and **grouped per namespace**</size>
note "Your are analyzing:\nExamples.BadDesign.CarExample.CarParts.Doors **detailed** and **grouped per namespace**\n\n==Filter==\nYou can click either the namespaces \nor class names for filtering them and their\ndirect dependencies.\n\n==Select other==\n* Examples.BadDesign.CarExample.CarParts.Doors **simplified** and **grouped per namespace**:\n   [[Examples.BadDesign.CarExample.CarParts.Doors-diagram-simplified-grouped-per-namespace.svg]]\n* Full diagram **detailed** and **grouped per namespace**:\n   [[full-diagram-detailed-grouped-per-namespace.svg]]\n* Home:\n   [[index.html]]" as FloatingNote
namespace Examples [[Examples-diagram-detailed-grouped-per-namespace.svg]] {
namespace Examples.BadDesign [[Examples.BadDesign-diagram-detailed-grouped-per-namespace.svg]] {
namespace Examples.BadDesign.CarExample [[Examples.BadDesign.CarExample-diagram-detailed-grouped-per-namespace.svg]] {
    abstract class Examples.BadDesign.CarExample.DB [[Examples.BadDesign.CarExample.DB-diagram-detailed-grouped-per-namespace.svg]]  {
      - get(<font color="6060BB"></font>)
      - getCarsWhere(<font color="6060BB"></font>)
      - set(<font color="6060BB"></font>)
      - update(<font color="6060BB"></font>)
      - getUserWhere(<font color="6060BB"></font>)
      - getCustomerWhere(<font color="6060BB"></font>)
      - getWarehouseCarWhere(<font color="6060BB"></font>)
      - getInvoiceWhere(<font color="6060BB"></font>)
      - getComplaintsWhere(<font color="6060BB"></font>)
      - getFirstCustomerWhere(<font color="6060BB"></font>)
      - getUserFromWarehouseCar(<font color="6060BB">item:Examples.BadDesign.CarExample.WarehouseEntities.Car</font>)
      - getCustomerFromComplaint(<font color="6060BB">complaint:Examples.BadDesign.CarExample.WarehouseEntities.Complaints</font>)
      - getWarehouseCarFromUser(<font color="6060BB">user:Examples.BadDesign.CarExample.WarehouseEntities.Car</font>)
      - getInvoiceFromCustomer(<font color="6060BB">c:Examples.BadDesign.CarExample.WarehouseEntities.Customer</font>)
      - getComplaintsFromWarehouseCar(<font color="6060BB">item:Examples.BadDesign.CarExample.WarehouseEntities.Car</font>)
      - getCarFromDriver(<font color="6060BB">d:Examples.BadDesign.CarExample.CarParts.Driver</font>)
      - getDriverFromCar(<font color="6060BB">c:Examples.BadDesign.CarExample.Car</font>)
      - getWheelsFromCar(<font color="6060BB">c:Examples.BadDesign.CarExample.Car</font>)
      - getDoorsFromCar(<font color="6060BB">c:Examples.BadDesign.CarExample.Car</font>)
      - getSeatsFromCar(<font color="6060BB">c:Examples.BadDesign.CarExample.Car</font>)
    }
    abstract class Examples.BadDesign.CarExample.Car [[Examples.BadDesign.CarExample.Car-diagram-detailed-grouped-per-namespace.svg]]  {
      + wheels: Examples.BadDesign.CarExample.CarParts.Wheels
      + vehicle: Examples.BadDesign.CarExample.Vehicle
      + db: Examples.BadDesign.CarExample.DB
==
      - createCar(<font color="6060BB">doors:Examples.BadDesign.CarExample.CarParts.Doors</font>)
      - <font color="909090">createCar.seats: Examples.BadDesign.CarExample.CarParts.Seats</font>
--
    }
'Compared namespace Examples.BadDesign.CarExample [[Examples.BadDesign.CarExample-diagram-detailed-grouped-per-namespace.svg]] { with last element of     }
' Closing all previous_sub_namespace_list namespace None because file analysis is finished.
' Closing namespace CarExample
}
' Closing namespace BadDesign
}
' Closing namespace Examples
}
namespace Examples [[Examples-diagram-detailed-grouped-per-namespace.svg]] {
namespace Examples.BadDesign [[Examples.BadDesign-diagram-detailed-grouped-per-namespace.svg]] {
namespace Examples.BadDesign.CarExample [[Examples.BadDesign.CarExample-diagram-detailed-grouped-per-namespace.svg]] {
namespace Examples.BadDesign.CarExample.CarParts [[Examples.BadDesign.CarExample.CarParts-diagram-detailed-grouped-per-namespace.svg]] {
      abstract class Examples.BadDesign.CarExample.CarParts.Doors [[Examples.BadDesign.CarExample.CarParts.Doors-diagram-detailed-grouped-per-namespace.svg]] #yellow {
        + db: Examples.BadDesign.CarExample.DB
==
        - getWeight(<font color="6060BB"></font>)
      }
'Compared namespace Examples.BadDesign.CarExample.CarParts [[Examples.BadDesign.CarExample.CarParts-diagram-detailed-grouped-per-namespace.svg]] { with last element of       }
' Closing all previous_sub_namespace_list namespace None because file analysis is finished.
' Closing namespace CarParts
}
' Closing namespace CarExample
}
' Closing namespace BadDesign
}
' Closing namespace Examples
}
 ' *************************************** 
 ' *************************************** 
 ' *************************************** 
' Class relations extracted from namespace:
' Examples.BadDesign.CarExample
Examples.BadDesign.CarExample.DB .[#6060BB].> Examples.BadDesign.CarExample.Car  : uses 
Examples.BadDesign.CarExample.Car *-[#10BB10]- Examples.BadDesign.CarExample.DB 
Examples.BadDesign.CarExample.Car .[#6060BB].> Examples.BadDesign.CarExample.CarParts.Doors  : uses 
' Class relations extracted from namespace:
' Examples.BadDesign.CarExample.CarParts
Examples.BadDesign.CarExample.CarParts.Doors *-[#10BB10]- Examples.BadDesign.CarExample.DB 
@enduml