@startuml
skinparam linetype ortho
title <size:20>MyNamespace.DotNetPreAdapter.DotNetPreAdapter.RecursiveFileProcessor **simplified** </size>
note "Your are analyzing:\nMyNamespace.DotNetPreAdapter.DotNetPreAdapter.RecursiveFileProcessor **simplified** \n\n==Filter==\nYou can click either the namespaces \nor class names for filtering them and their\ndirect dependencies.\n\n==Select other==\n* MyNamespace.DotNetPreAdapter.DotNetPreAdapter.RecursiveFileProcessor **detailed** :\n   [[MyNamespace.DotNetPreAdapter.DotNetPreAdapter.RecursiveFileProcessor-diagram-detailed.svg]]\n* Full diagram **simplified** and **grouped per namespace**:\n   [[full-diagram-simplified-grouped-per-namespace.svg]]\n* Home:\n   [[index.html]]" as FloatingNote
      abstract class MyNamespace.DotNetPreAdapter.DotNetPreAdapter.RecursiveFileProcessor.InnerClass [[MyNamespace.DotNetPreAdapter.DotNetPreAdapter.RecursiveFileProcessor.InnerClass-diagram-simplified.svg]] #yellow {
      }
 ' *************************************** 
 ' *************************************** 
 ' *************************************** 
' Class relations extracted from namespace:
' MyNamespace.DotNetPreAdapter.DotNetPreAdapter.RecursiveFileProcessor
@enduml