@startuml
skinparam linetype ortho
title <size:20>MyNamespace.DotNetPreAdapter.InnerClassBase **simplified** </size>
note "Your are analyzing:\nMyNamespace.DotNetPreAdapter.InnerClassBase **simplified** \n\n==Filter==\nYou can click either the namespaces \nor class names for filtering them and their\ndirect dependencies.\n\n==Select other==\n* MyNamespace.DotNetPreAdapter.InnerClassBase **detailed** :\n   [[MyNamespace.DotNetPreAdapter.InnerClassBase-diagram-detailed.svg]]\n* Full diagram **simplified** and **grouped per namespace**:\n   [[full-diagram-simplified-grouped-per-namespace.svg]]\n* Home:\n   [[index.html]]" as FloatingNote
  abstract class MyNamespace.DotNetPreAdapter.InnerClassBase [[MyNamespace.DotNetPreAdapter.InnerClassBase-diagram-simplified.svg]] #yellow {
  }
  abstract class MyNamespace.DotNetPreAdapter.InnerClass [[MyNamespace.DotNetPreAdapter.InnerClass-diagram-simplified.svg]]  {
  }
 ' *************************************** 
 ' *************************************** 
 ' *************************************** 
' Class relations extracted from namespace:
' MyNamespace.DotNetPreAdapter
MyNamespace.DotNetPreAdapter.InnerClassBase <|-[#red]- MyNamespace.DotNetPreAdapter.InnerClass
@enduml