@startuml
skinparam linetype ortho
title <size:20>MyNamespace.DotNetPreAdapter.InnerClass **simplified** and **grouped per namespace**</size>
note "Your are analyzing:\nMyNamespace.DotNetPreAdapter.InnerClass **simplified** and **grouped per namespace**\n\n==Filter==\nYou can click either the namespaces \nor class names for filtering them and their\ndirect dependencies.\n\n==Select other==\n* MyNamespace.DotNetPreAdapter.InnerClass **detailed** and **grouped per namespace**:\n   [[MyNamespace.DotNetPreAdapter.InnerClass-diagram-detailed-grouped-per-namespace.svg]]\n* Full diagram **simplified** and **grouped per namespace**:\n   [[full-diagram-simplified-grouped-per-namespace.svg]]\n* Home:\n   [[index.html]]" as FloatingNote
class Enum [[Enum-diagram-simplified-grouped-per-namespace.svg]] #MintCream {
}
class IComparable [[IComparable-diagram-simplified-grouped-per-namespace.svg]] #MintCream {
}
class IFormattable [[IFormattable-diagram-simplified-grouped-per-namespace.svg]] #MintCream {
}
class IConvertible [[IConvertible-diagram-simplified-grouped-per-namespace.svg]] #MintCream {
}
' Closing all previous_sub_namespace_list namespace None because file analysis is finished.
namespace MyNamespace [[MyNamespace-diagram-simplified-grouped-per-namespace.svg]] {
namespace MyNamespace.DotNetPreAdapter [[MyNamespace.DotNetPreAdapter-diagram-simplified-grouped-per-namespace.svg]] {
  abstract class MyNamespace.DotNetPreAdapter.InnerClassBase [[MyNamespace.DotNetPreAdapter.InnerClassBase-diagram-simplified-grouped-per-namespace.svg]] #yellow {
  }
  abstract class MyNamespace.DotNetPreAdapter.InnerClass [[MyNamespace.DotNetPreAdapter.InnerClass-diagram-simplified-grouped-per-namespace.svg]] #yellow {
  }
  interface MyNamespace.DotNetPreAdapter.IMyTest [[MyNamespace.DotNetPreAdapter.IMyTest-diagram-simplified-grouped-per-namespace.svg]]  {
  }
  abstract class MyNamespace.DotNetPreAdapter.InnerClass_DOT_InnerTestUnusedInInnerClass [[MyNamespace.DotNetPreAdapter.InnerClass.InnerTestUnusedInInnerClass-diagram-simplified-grouped-per-namespace.svg]] #yellow {
  }
'Compared namespace MyNamespace.DotNetPreAdapter [[MyNamespace.DotNetPreAdapter-diagram-simplified-grouped-per-namespace.svg]] { with last element of   }
' Closing all previous_sub_namespace_list namespace None because file analysis is finished.
' Closing namespace DotNetPreAdapter
}
' Closing namespace MyNamespace
}
 ' *************************************** 
 ' *************************************** 
 ' *************************************** 
' Class relations extracted from namespace:
' 
' Class relations extracted from namespace:
' MyNamespace.DotNetPreAdapter
MyNamespace.DotNetPreAdapter.InnerClassBase <|-[#red]- MyNamespace.DotNetPreAdapter.InnerClass
MyNamespace.DotNetPreAdapter.IMyTest <|-[#red]- MyNamespace.DotNetPreAdapter.InnerClass
MyNamespace.DotNetPreAdapter.InnerClass +-[#10BBBB]- MyNamespace.DotNetPreAdapter.InnerClass_DOT_InnerTestUnusedInInnerClass 
Enum <|-[#red]- MyNamespace.DotNetPreAdapter.InnerClass_DOT_InnerTestUnusedInInnerClass
IComparable <|-[#red]- MyNamespace.DotNetPreAdapter.InnerClass_DOT_InnerTestUnusedInInnerClass
IFormattable <|-[#red]- MyNamespace.DotNetPreAdapter.InnerClass_DOT_InnerTestUnusedInInnerClass
IConvertible <|-[#red]- MyNamespace.DotNetPreAdapter.InnerClass_DOT_InnerTestUnusedInInnerClass
@enduml