@startuml
skinparam linetype ortho
title <size:20>SyntaxTree **simplified** </size>
note "Your are analyzing:\nSyntaxTree **simplified** \n\n==Filter==\nYou can click either the namespaces \nor class names for filtering them and their\ndirect dependencies.\n\n==Select other==\n* SyntaxTree **detailed** :\n   [[SyntaxTree-diagram-detailed.svg]]\n* Full diagram **simplified** and **grouped per namespace**:\n   [[full-diagram-simplified-grouped-per-namespace.svg]]\n* Home:\n   [[index.html]]" as FloatingNote
class SyntaxTree [[SyntaxTree-diagram-simplified.svg]] #yellow {
}
  abstract class DotNetPreAdapter.Service.AnalyzeAST [[DotNetPreAdapter.Service.AnalyzeAST-diagram-simplified.svg]]  {
  }
 ' *************************************** 
 ' *************************************** 
 ' *************************************** 
' Class relations extracted from namespace:
' 
' Class relations extracted from namespace:
' DotNetPreAdapter.Service
DotNetPreAdapter.Service.AnalyzeAST -[#909090]-> SyntaxTree  : uses 
@enduml