@startuml
skinparam linetype ortho
title <size:20>Vehicle **detailed** </size>
note "Your are analyzing:\nVehicle **detailed** \n\n==Filter==\nYou can click either the namespaces \nor class names for filtering them and their\ndirect dependencies.\n\n==Select other==\n* Vehicle **simplified** :\n   [[Vehicle-diagram-simplified.svg]]\n* Full diagram **detailed** and **grouped per namespace**:\n   [[full-diagram-detailed-grouped-per-namespace.svg]]\n* Home:\n   [[index.html]]" as FloatingNote
class Vehicle [[Vehicle-diagram-detailed.svg]] #yellow {
}
      abstract class Examples.BetterDesign.Repository.CarExample.Car [[Examples.BetterDesign.Repository.CarExample.Car-diagram-detailed.svg]]  {
        + wheels: Examples.BetterDesign.Repository.CarExample.CarParts.Wheels
        + seats: Examples.BetterDesign.Repository.CarExample.CarParts.Seats
        + driver: Examples.BetterDesign.Repository.CarExample.CarParts.Driver
        + doors: Examples.BetterDesign.Repository.CarExample.CarParts.Doors
==
        + createCar(<font color="6060BB">doors:Examples.BetterDesign.Repository.CarExample.CarParts.Doors</font>)
      }
 ' *************************************** 
 ' *************************************** 
 ' *************************************** 
' Class relations extracted from namespace:
' 
' Class relations extracted from namespace:
' Examples.BetterDesign.Repository.CarExample
Vehicle <|-[#red]- Examples.BetterDesign.Repository.CarExample.Car
@enduml