@startuml
skinparam linetype ortho
title <size:20>YamlStream **detailed** and **grouped per namespace**</size>
note "Your are analyzing:\nYamlStream **detailed** and **grouped per namespace**\n\n==Filter==\nYou can click either the namespaces \nor class names for filtering them and their\ndirect dependencies.\n\n==Select other==\n* YamlStream **simplified** and **grouped per namespace**:\n   [[YamlStream-diagram-simplified-grouped-per-namespace.svg]]\n* Full diagram **detailed** and **grouped per namespace**:\n   [[full-diagram-detailed-grouped-per-namespace.svg]]\n* Home:\n   [[index.html]]" as FloatingNote
class YamlStream [[YamlStream-diagram-detailed-grouped-per-namespace.svg]] #yellow {
}
' Closing all previous_sub_namespace_list namespace None because file analysis is finished.
namespace DotNetPreAdapter [[DotNetPreAdapter-diagram-detailed-grouped-per-namespace.svg]] {
namespace DotNetPreAdapter.Infrastructure [[DotNetPreAdapter.Infrastructure-diagram-detailed-grouped-per-namespace.svg]] {
  abstract class DotNetPreAdapter.Infrastructure.CreateYml [[DotNetPreAdapter.Infrastructure.CreateYml-diagram-detailed-grouped-per-namespace.svg]]  {
    + Create(<font color="6060BB">datastructure:DotNetPreAdapter.Domain.Datastructure, logger:DotNetPreAdapter.Utils.Logger</font>)
    - <font color="909090">Create.subDatastructureYmlNode: YamlSequenceNode</font>
    - <font color="909090">Create.subDataStructure: DotNetPreAdapter.Domain.Datastructure.SubDataStructure</font>
    - <font color="909090">Create.fromImports: YamlSequenceNode</font>
    - <font color="909090">Create.innerClasses: YamlSequenceNode</font>
    - <font color="909090">Create.anonymousCalls: YamlSequenceNode</font>
    - <font color="909090">Create.baseClasses: YamlSequenceNode</font>
    - <font color="909090">Create.statics: YamlSequenceNode</font>
    - <font color="909090">Create.variables: YamlSequenceNode</font>
    - <font color="909090">Create.methods: YamlSequenceNode</font>
    - <font color="909090">Create.parameters: YamlSequenceNode</font>
    - <font color="909090">Create.methodVariables: YamlSequenceNode</font>
    - <font color="909090">Create.stream: YamlStream</font>
    - <font color="909090">Create.writer: System.IO.TextWriter</font>
--
  }
'Compared namespace DotNetPreAdapter.Infrastructure [[DotNetPreAdapter.Infrastructure-diagram-detailed-grouped-per-namespace.svg]] { with last element of   }
' Closing all previous_sub_namespace_list namespace None because file analysis is finished.
' Closing namespace Infrastructure
}
' Closing namespace DotNetPreAdapter
}
 ' *************************************** 
 ' *************************************** 
 ' *************************************** 
' Class relations extracted from namespace:
' 
' Class relations extracted from namespace:
' DotNetPreAdapter.Infrastructure
DotNetPreAdapter.Infrastructure.CreateYml -[#909090]-> YamlStream  : uses 
@enduml